### ISSUE TITLE
graylog报警时区问题

### ISSUE THREAD

**Issue by loveyang2012** [feiyu563/PrometheusAlert#10]
大神好，graylog3报警时，报警开始时间慢了8个小时，这个时区问题怎么处理？

**Comment by feiyu563** [comment]
时区应该从graylog的配置上调整下时区



---原始邮件---
发件人: "loveyang2012"<notifications@github.com&gt;
发送时间: 2020年3月8日(周日) 下午4:02
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] graylog报警时区问题 (#10)



大神好，graylog3报警时，报警开始时间慢了8个小时，这个时区问题怎么处理？

**Comment by feiyu563** [comment]
最新的版本里面已经默认将graylog的告警时间强制转换为cst时间了
