### ISSUE TITLE
是否有日志可以记录本次告警调用了哪些接口/发送给了哪些人

### ISSUE THREAD

**Issue by fzusuny** [feiyu563/PrometheusAlert#101]
您好，请问是否有相关日志记录了每次告警发送给了哪些告警终端。如阿里云电话告警，设置了8个人，只有6个人收到，查询阿里语音记录发现并没有呼叫记录。
是否有日志接口能查到当时alertmanager向PremetheusAlert发送的初始url(因为url中包含了告警人的电话)
我觉得这个功能非常有用~

**Comment by feiyu563** [comment]
默认的日志里面有记录



---原始邮件---
发件人: "fzusuny"<notifications@github.com&gt;
发送时间: 2021年1月28日(周四) 下午3:53
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 是否有日志可以记录本次告警调用了哪些接口/发送给了哪些人 (#101)




 
您好，请问是否有相关日志记录了每次告警发送给了哪些告警终端。如阿里云电话告警，设置了8个人，只有6个人收到，查询阿里语音记录发现并没有呼叫记录。
 是否有日志接口能查到当时alertmanager向PremetheusAlert发送的初始url(因为url中包含了告警人的电话)
 我觉得这个功能非常有用~

**Comment by fzusuny** [comment]
看到了，非常感谢，日志显示的是alertmanager中recevier的名字，如：
{
    "receiver":"prometheusalert-phone",
    "status":"firing",
    "alerts":[...]
}
