### ISSUE TITLE
我如何使用钉钉告警和阿里云自定义告警

### ISSUE THREAD

**Issue by yinglingqihang** [feiyu563/PrometheusAlert#102]
我现在单独的发送钉钉告警可以发送出来，单独的使用阿里云短信也可以发送出来，但是我配置上分级别进行钉钉和阿里云短信告警，这么配置的，就是发送不出来，配置如下：
global:
  resolve_timeout: 5m
route:
  group_by: ['hostalter']
  group_wait: 10m
  group_interval: 10s
  repeat_interval: 10m 
  receiver: 'web.hook.prometheusalert'
  routes:
  - receiver: 'prometheusalert-dingding'
    match:
      level: 3

  - receiver: 'prometheusalert-sms'
    match:
      level: 4

receivers:
- name: 'web.hook.prometheusalert'
  webhook_configs:
  - url: 'http://xxxx/prometheus/alert'

- name: 'prometheusalert-dingding'
  webhook_configs:
  - url: 'http://xxxx/prometheus/router?ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxxx'

- name: 'prometheusalert-sms'
  webhook_configs:
  - url: 'http://xxxx/prometheusalert?type=alydx&tpl=prometheus-alinyun-sms&phone=xxxx'

请帮忙指出我的问题，万分感谢！！！

**Comment by feiyu563** [comment]
你的rules里面有level的label吗，没有的话默认应该匹配到第一个

**Comment by yinglingqihang** [comment]
有label的标签
groups: 
    - name: hostalter 
      rules:           
      - alert: 主机不可达 
        expr: up == 0
        for: 5s
        labels:  
          level: 4
        annotations:  
          summary: "{{$labels.instance}}:服务器宕机或者客户端挂掉"

如果是3的时候会发送给钉钉，如果是4的时候也会发送给钉钉？

**Comment by yinglingqihang** [comment]
通过web上的test测试，钉钉和短信都可以接到测试报警的短信

**Comment by feiyu563** [comment]
你把你的日志贴上来我看下是哪个接口处理的消息，有可能alertmanager把消息都发给了 web.hook.prometheusalert

**Comment by yinglingqihang** [comment]
2021/02/03 16:56:24.196 [I] [asm_amd64.s:1373]  http server Running on http://:8080




2021/02/03 16:57:18.081 [I] [value.go:460]  [1612342638075601447] {"receiver":"web\\.hook\\.prometheusalert","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"主机不可达","env_name":"线上环境","hostname":"PC1","instance":"47.95.144.111:9100","job":"PC","project_name":"拍拍赚后台","severity":"3"},"annotations":{"mobile":"13720016210","summary":"47.95.144.111:9100:服务器宕机或者客户端挂掉"},"startsAt":"2021-02-03T08:36:42.73804936Z","endsAt":"2021-02-03T08:57:12.73804936Z","generatorURL":"http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"bd7fb3530b8eda96"}],"groupLabels":{},"commonLabels":{"alertname":"主机不可达","env_name":"线上环境","hostname":"PC1","instance":"47.95.144.111:9100","job":"PC","project_name":"拍拍赚后台","severity":"3"},"commonAnnotations":{"mobile":"13720016210","summary":"47.95.144.111:9100:服务器宕机或者客户端挂掉"},"externalURL":"http://alertmanager:9093","version":"4","groupKey":"{}:{}","truncatedAlerts":0}

2021/02/03 16:57:18.105 [I] [prometheus.go:149]  [1612342638075601447] [dingding] {"msgtype":"markdown","markdown":{"title":"PrometheusAlert故障恢复信息","text":"## [PrometheusAlertPrometheus故障恢复信息](http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1)\n\n#### [主机不可达](http://alertmanager:9093)\n\n###### 告警级别：信息\n\n###### 开始时间：2021-02-03T08:36:42.73804936Z\n\n###### 结束时间：2021-02-03T08:57:12.73804936Z\n\n###### 故障主机IP：47.95.144.111:9100\n\n##### \n\n![PrometheusAlert]()"},"at":{"atMobiles":["15395105573"],"isAtAll":true}}

2021/02/03 16:57:18.188 [I] [prometheus.go:149]  [1612342638075601447] [dingding] {"errcode":0,"errmsg":"ok"}
2021/02/03 16:57:18.188 [I] [prometheus.go:168]  [1612342638075601447] [weixin] {"msgtype":"markdown","markdown":{"content":"[PrometheusAlertPrometheus故障恢复信息](http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1)\n\u003e**[主机不可达](http://alertmanager:9093)**\n\u003e`告警级别:`信息\n`开始时间:`2021-02-03T08:36:42.73804936Z\n`结束时间:`2021-02-03T08:57:12.73804936Z\n`故障主机IP:`47.95.144.111:9100\n****"}}

2021/02/03 16:57:18.188 [E] [prometheus.go:168]  [1612342638075601447] [weixin] Post "": unsupported protocol scheme ""
2021/02/03 16:57:18.189 [C] [panic.go:967]  the request url is  /prometheus/alert
2021/02/03 16:57:18.192 [C] [panic.go:967]  Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2021/02/03 16:57:18.192 [C] [panic.go:967]  /usr/local/go/src/runtime/panic.go:967
2021/02/03 16:57:18.192 [C] [panic.go:967]  /usr/local/go/src/runtime/panic.go:212
2021/02/03 16:57:18.192 [C] [panic.go:967]  /usr/local/go/src/runtime/signal_unix.go:687
2021/02/03 16:57:18.192 [C] [panic.go:967]  /mnt/hgfs/code/golang/src/PrometheusAlert/controllers/weixin.go:56
2021/02/03 16:57:18.192 [C] [panic.go:967]  /mnt/hgfs/code/golang/src/PrometheusAlert/controllers/prometheus.go:168
2021/02/03 16:57:18.192 [C] [panic.go:967]  /mnt/hgfs/code/golang/src/PrometheusAlert/controllers/prometheus.go:67
2021/02/03 16:57:18.192 [C] [panic.go:967]  /usr/local/go/src/reflect/value.go:460
2021/02/03 16:57:18.192 [C] [panic.go:967]  /usr/local/go/src/reflect/value.go:321
2021/02/03 16:57:18.192 [C] [panic.go:967]  /mnt/hgfs/code/golang/src/PrometheusAlert/vendor/github.com/astaxie/beego/router.go:853
2021/02/03 16:57:18.192 [C] [panic.go:967]  /usr/local/go/src/net/http/server.go:2807
2021/02/03 16:57:18.192 [C] [panic.go:967]  /usr/local/go/src/net/http/server.go:1895
2021/02/03 16:57:18.192 [C] [panic.go:967]  /usr/local/go/src/runtime/asm_amd64.s:1373
2021/02/03 16:57:18.205 [server.go:3059]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)

**Comment by yinglingqihang** [comment]
没有调用短信接口

**Comment by yinglingqihang** [comment]
是我的配置错了吗？我调整成这样还是短信收不到
rules文件：
groups: 
    - name: hostalter 
      rules:           
      - alert: 主机不可达 
        expr: up == 0
        for: 5s
        labels:  
          level: 3
        annotations:  
          summary: "{{$labels.instance}}:服务器宕机或者客户端挂掉"

alertmanager.yml:
global:
  resolve_timeout: 5m
route:
  group_by: ['hostalter']
  group_wait: 10m
  group_interval: 10s
  repeat_interval: 10m
  receiver: 'web.hook.prometheusalert'
  routes:
  - receiver: 'prometheusalert-dingding'
    group_wait: 10s
    match:
      level: '2'
  - receiver: 'prometheusalert-sms'
    group_wait: 10s
    match:
      level: '3'

receivers:
- name: 'web.hook.prometheusalert'
  webhook_configs:
  - url: 'http://xxx:8080/prometheus/alert'

- name: 'prometheusalert-dingding'
  webhook_configs:
  - url: 'http://xx:8080/prometheus/router?ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxx'

- name: 'prometheusalert-sms'
  webhook_configs:
  - url: 'http://xxx:8080/prometheusalert?type=alydx&tpl=prometheus-alinyun-sms&phone=xx'

- name: 'prometheusalert-all'
  webhook_configs:
  - url: 'http://xx:8080/prometheus/router?ddurl=https://oapi.dingtalk.com/robot/send?access_token=xx&phone=xx'

**Comment by feiyu563** [comment]
这是因为消息被alertmanager发送给了 web.hook.prometheusalert 这个receiver，没有发给其他的

**Comment by yinglingqihang** [comment]
这个应该怎么更改，有相关的例子吗？

**Comment by feiyu563** [comment]
`
global:
resolve_timeout: 5m
route:
group_by: ['hostalter']
group_wait: 10m
group_interval: 10s
repeat_interval: 10m
receiver: 'none'
routes:

receiver: 'prometheusalert-dingding'
match:
level: 3

receiver: 'prometheusalert-sms'
match:
level: 4

receivers:

name: 'web.hook.prometheusalert'
webhook_configs:

url: 'http://xxxx/prometheus/alert'
name: 'prometheusalert-dingding'
webhook_configs:

url: 'http://xxxx/prometheus/router?ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxxx'
name: 'prometheusalert-sms'
webhook_configs:

url: 'http://xxxx/prometheusalert?type=alydx&tpl=prometheus-alinyun-sms&phone=xxxx'
`
试试这么写

**Comment by yinglingqihang** [comment]
level=error ts=2021-02-03T09:17:57.881Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/alertmanager.yml err="undefined receiver \"none\" used in route"
![image](https://user-images.githubusercontent.com/25978572/106725018-db1ec180-6643-11eb-9e37-66d1894d8292.png)

**Comment by yinglingqihang** [comment]
不能定义为none

**Comment by feiyu563** [comment]
我才发现你上面的日志里面的消息 rules没有level，所以默认就是走的 web.hook.prometheusalert

**Comment by feiyu563** [comment]
```
2021/02/03 16:57:18.081 [I] [value.go:460] [1612342638075601447] {"receiver":"web\.hook\.prometheusalert","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"主机不可达","env_name":"线上环境","hostname":"PC1","instance":"47.95.144.111:9100","job":"PC","project_name":"拍拍赚后台","severity":"3"},"annotations":{"mobile":"13720016210","summary":"47.95.144.111:9100:服务器宕机或者客户端挂掉"},"startsAt":"2021-02-03T08:36:42.73804936Z","endsAt":"2021-02-03T08:57:12.73804936Z","generatorURL":"http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"bd7fb3530b8eda96"}],"groupLabels":{},"commonLabels":{"alertname":"主机不可达","env_name":"线上环境","hostname":"PC1","instance":"47.95.144.111:9100","job":"PC","project_name":"拍拍赚后台","severity":"3"},"commonAnnotations":{"mobile":"13720016210","summary":"47.95.144.111:9100:服务器宕机或者客户端挂掉"},"externalURL":"http://alertmanager:9093","version":"4","groupKey":"{}:{}","truncatedAlerts":0}
```

**Comment by yinglingqihang** [comment]
日志里面是"severity":"3" 但是我的rules.yml文件是level ，alertmanager.yml文件也是level

**Comment by feiyu563** [comment]
那就是你的prometheus的问题了

**Comment by yinglingqihang** [comment]
我之前使用过这个参数，但是现在grep了下我的配置文件都没有找到这个参数 severity，并且我重启了所有的服务还是有这个severity 这个是因为是缓存吗？

**Comment by feiyu563** [comment]
应该是rules没有生效

**Comment by yinglingqihang** [comment]
问题解决了 我把历史数据清了  重新启动了下所有的插件

**Comment by yinglingqihang** [comment]
谢谢

**Comment by yinglingqihang** [comment]
麻烦您了，想在问一个问题，我现在短信的告警调通了，钉钉的默认模板是可以的，但是我自定义了钉钉的模板，然后进行调用：
rule.yml:
groups: 
    - name: hostalter
      rules:           
      - alert: 主机不可达
        expr: up == 0
        for: 5s
        labels:  
          level: 2
        annotations:  
          summary: "{{$labels.instance}}:服务器宕机或者客户端挂掉"
          description: "{{$labels.instance}}:服务器宕机或者客户端挂掉"
alertmanager,yml
global:
  resolve_timeout: 5m
route:
  group_by: ['hostalter']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 10m
  receiver: 'web.hook.prometheusalert'
  routes:
  - receiver: 'dingding'
    match:
      level: '2'
  - receiver: 'prometheusalert-sms'
    match:
      level: '3'

receivers:
- name: 'web.hook.prometheusalert'
  webhook_configs:
  - url: 'http://xxxx/prometheus/alert'

- name: 'dingding'
  webhook_configs:
  - url: 'http://xxx/prometheusalert?type=dd&tpl=prometheus-dingding-custom&ddurl=xxx'

- name: 'prometheusalert-sms'
  webhook_configs:
  - url: 'http://xxx:8080/prometheusalert?type=alydx&tpl=prometheus-alinyun-sms&phone=xxx'
 然后日志文件是：
{"receiver":"dingding","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"主机不可达","env_name":"线上环境-docker资源","hostname":"PC1","instance":"47.95.144.111:8080","job":"PC","level":"2","project_name":"拍拍赚后台"},"annotations":{"description":"47.95.144.111:8080:服务器宕机或者客户端挂掉","summary":"47.95.144.111:8080:服务器宕机或者客户端挂掉"},"startsAt":"2021-02-03T11:41:57.73804936Z","endsAt":"2021-02-03T11:49:12.73804936Z","generatorURL":"http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"6de5ad6649ac6820"}],"groupLabels":{},"commonLabels":{"alertname":"主机不可达","env_name":"线上环境-docker资源","hostname":"PC1","instance":"47.95.144.111:8080","job":"PC","level":"2","project_name":"拍拍赚后台"},"commonAnnotations":{"description":"47.95.144.111:8080:服务器宕机或者客户端挂掉","summary":"47.95.144.111:8080:服务器宕机或者客户端挂掉"},"externalURL":"http://alertmanager:9093","version":"4","groupKey":"{}/{level=\"2\"}:{}","truncatedAlerts":0}

这个消息已经发送到了receiver":"dingding, 这一块为什么钉钉接受不到，我配置的钉钉的webhook地址正确吗？
并且我在web端测试，钉钉是可以的接受成功的
