### ISSUE TITLE
钉钉自定义模板发送不出来

### ISSUE THREAD

**Issue by yinglingqihang** [feiyu563/PrometheusAlert#103]
想在问一个问题，我现在短信的告警模板调通了，钉钉的默认模板是可以的，但是不好看，我自定义了钉钉的模板，然后进行调用，发不出来，相关配置如下：
rule.yml:
groups:
- name: hostalter
rules:
- alert: 主机不可达
expr: up == 0
for: 5s
labels:
level: 2
annotations:
summary: "{{$labels.instance}}:服务器宕机或者客户端挂掉"
description: "{{$labels.instance}}:服务器宕机或者客户端挂掉"
alertmanager,yml
global:
resolve_timeout: 5m
route:
group_by: ['hostalter']
group_wait: 5s
group_interval: 10s
repeat_interval: 10m
receiver: 'web.hook.prometheusalert'
routes:

receiver: 'dingding'
match:
level: '2'
receiver: 'prometheusalert-sms'
match:
level: '3'
receivers:

name: 'web.hook.prometheusalert'
webhook_configs:

url: 'http://xxxx/prometheus/alert'
name: 'dingding'
webhook_configs:

url: 'http://xxx/prometheusalert?type=dd&tpl=prometheus-dingding-custom&ddurl=xxx'
name: 'prometheusalert-sms'
webhook_configs:

url: 'http://xxx:8080/prometheusalert?type=alydx&tpl=prometheus-alinyun-sms&phone=xxx'
然后日志文件是：
{"receiver":"dingding","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"主机不可达","env_name":"线上环境-docker资源","hostname":"PC1","instance":"ip:8080","job":"PC","level":"2","project_name":"拍拍赚后台"},"annotations":{"description":"ip:8080:服务器宕机或者客户端挂掉","summary":"ip:8080:服务器宕机或者客户端挂掉"},"startsAt":"2021-02-03T11:41:57.73804936Z","endsAt":"2021-02-03T11:49:12.73804936Z","generatorURL":"http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"6de5ad6649ac6820"}],"groupLabels":{},"commonLabels":{"alertname":"主机不可达","env_name":"线上环境-docker资源","hostname":"PC1","instance":"ip:8080","job":"PC","level":"2","project_name":"拍拍赚后台"},"commonAnnotations":{"description":"47.95.144.111:8080:服务器宕机或者客户端挂掉","summary":"ip:8080:服务器宕机或者客户端挂掉"},"externalURL":"http://alertmanager:9093","version":"4","groupKey":"{}/{level=\"2\"}:{}","truncatedAlerts":0}
这个消息已经发送到了receiver":"dingding, 这一块为什么钉钉接受不到，我配置的钉钉的webhook地址正确吗？
并且我在web端测试，钉钉是可以的接收成功的

感谢

**Comment by feiyu563** [comment]
模版发不出来是模版没改对

**Comment by yinglingqihang** [comment]
这是模板：
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }}
{{if eq $v.status "resolved"}}
Prometheus恢复信息
告警名称：{{$v.labels.alertname}}
告警级别：{{$v.labels.level}}
开始时间：{{$v.startsAt}}
结束时间：{{$v.endsAt}}
实例地址：{{$v.labels.instance}}
主机名称：{{$v.labels.hostname}}
{{$v.annotations.description}}
{{else}}
Prometheus告警信息
告警名称：{{$v.labels.alertname}}
告警级别：{{$v.labels.level}}
开始时间：{{$v.startsAt}}
结束时间：{{$v.endsAt}}
实例地址：{{$v.labels.instance}}
主机名称：{{$v.labels.hostname}}
{{$v.annotations.description}}
{{end}}
{{ end }}

**Comment by yinglingqihang** [comment]
官网上的几个模板我都试了 感觉好奇怪
