### ISSUE TITLE
在alertmanage里面怎么写多个电话号码？

### ISSUE THREAD

**Issue by yinglingqihang** [feiyu563/PrometheusAlert#104]
- name: 'prometheusalert-sms'
  webhook_configs:
  - url: 'http://xxx:8080/prometheusalert?type=alydx&tpl=prometheus-alinyun-sms&phone=13720016232,http://xxx:8080/prometheusalert?type=alydx&tpl=prometheus-alinyun-sms&phone=13720045533'

- name: 'prometheusalert-sms'
  webhook_configs:
  - url: 'http://xxx:8080/prometheusalert?type=alydx&tpl=prometheus-alinyun-sms&phone=13720016232&phone=13720045533'
  这两种方式都不可以，请问正确的写法是什么？

**Comment by feiyu563** [comment]
注意看文档，文档里面都有写，多个号码用逗号,分割

**Comment by yinglingqihang** [comment]
逗号的也试了，就是其他手机接不到短信，改了默认的conf/app.conf，defaultphone选项，其他的手机号能收到，但是这一块起不到分组的作用，怎么让他走alertmanage里面的配置呢？

**Comment by yinglingqihang** [comment]
把defaultphone 的参数改成xxxx 他会走user.csv，然后把user.csv的电话号码改成xxx，没有走alermanage.yaml的配置

**Comment by feiyu563** [comment]
查看你们的短信后台，看看是不是拦截了，或者看下Prometheusalert的日志，通常发送不成功会有错误日志

**Comment by yinglingqihang** [comment]
上面说错了  defaultphone改成xxxx之后，就发不出短信了  

日志是有打印的：
2021/02/04 17:09:13.051 [D] [value.go:460]  [1612429753051343132] {"receiver":"prometheusalert-sms","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"主机不可达","env_name":"线上环境-docker资源","hostname":"PC1","instance":"47.95.144.111:8080","job":"PC","level":"3","project_name":"拍拍赚后台"},"annotations":{"description":"47.95.144.111:8080:服务器宕机或者客户端挂掉","mobile":"13720045595","summary":"47.95.144.111:8080:服务器宕机或者客户端挂掉"},"startsAt":"2021-02-04T09:06:27.73804936Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"2991f7f48e34b63b"},{"status":"firing","labels":{"alertname":"主机不可达","env_name":"线上环境","hostname":"PC1","instance":"47.95.144.111:9100","job":"PC","level":"3","project_name":"拍拍赚后台"},"annotations":{"description":"47.95.144.111:9100:服务器宕机或者客户端挂掉","mobile":"13720045595","summary":"47.95.144.111:9100:服务器宕机或者客户端挂掉"},"startsAt":"2021-02-04T09:09:12.73804936Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"26f6b9d93411de23"}],"groupLabels":{},"commonLabels":{"alertname":"主机不可达","hostname":"PC1","job":"PC","level":"3","project_name":"拍拍赚后台"},"commonAnnotations":{"mobile":"13720045595"},"externalURL":"http://alertmanager:9093","version":"4","groupKey":"{}/{level=\"3\"}:{}","truncatedAlerts":0}
2021/02/04 17:09:13.173 [I] [prometheusalert.go:103]  [1612429753051343132] [alymessage] HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Requested-With, X-Sequence, _aop_secret, _aop_signature
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Max-Age: 172800
X-Acs-Request-Id: F138543F-3780-459B-8670-79F43DBFA6EF
Date: Thu, 04 Feb 2021 09:09:13 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 133
Connection: keep-alive

{"RequestId":"F138543F-3780-459B-8670-79F43DBFA6EF","Message":"xxxxxxxxxxx invalid mobile number","Code":"isv.MOBILE_NUMBER_ILLEGAL"}

**Comment by yinglingqihang** [comment]
查看了 短信平台没有发送失败记录

**Comment by yinglingqihang** [comment]
2021/02/04 17:24:48.170 [D] [server.go:2807]  |    182.92.2.20| 200 | 192.553317ms|   match| POST     /prometheusalert   r:/prometheusalert
2021/02/04 17:24:57.743 [D] [value.go:460]  [1612430697743486049] {"receiver":"prometheusalert-sms","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"主机不可达","env_name":"线上环境-docker资源","hostname":"PC1","instance":"47.95.144.111:8080","job":"PC","level":"3","project_name":"拍拍赚后台"},"annotations":{"description":"47.95.144.111:8080:服务器宕机或者客户端挂掉","mobile":"13720045595","summary":"47.95.144.111:8080:服务器宕机或者客户端挂掉"},"startsAt":"2021-02-04T09:24:42.73804936Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"2991f7f48e34b63b"},{"status":"resolved","labels":{"alertname":"主机不可达","env_name":"线上环境","hostname":"PC1","instance":"47.95.144.111:9100","job":"PC","level":"3","project_name":"拍拍赚后台"},"annotations":{"description":"47.95.144.111:9100:服务器宕机或者客户端挂掉","mobile":"13720045595","summary":"47.95.144.111:9100:服务器宕机或者客户端挂掉"},"startsAt":"2021-02-04T09:09:12.73804936Z","endsAt":"2021-02-04T09:14:57.73804936Z","generatorURL":"http://prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"26f6b9d93411de23"}],"groupLabels":{},"commonLabels":{"alertname":"主机不可达","hostname":"PC1","job":"PC","level":"3","project_name":"拍拍赚后台"},"commonAnnotations":{"mobile":"13720045595"},"externalURL":"http://alertmanager:9093","version":"4","groupKey":"{}/{level=\"3\"}:{}","truncatedAlerts":0}
2021/02/04 17:24:57.812 [I] [prometheusalert.go:103]  [1612430697743486049] [alymessage] HTTP/1.1 200 OK
Content-Length: 110
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, X-Sequence, _aop_secret, _aop_signature
Date: Thu, 04 Feb 2021 09:24:57 GMT
Content-Type: application/json;charset=utf-8
Access-Control-Max-Age: 172800
X-Acs-Request-Id: 1D37DE3F-B877-434D-B5AC-79B778265898

{"RequestId":"1D37DE3F-B877-434D-B5AC-79B778265898","Message":"OK","BizId":"760223612430697769^0","Code":"OK"}
这个发送成功的 并没有发送到日志里面的这个手机号："mobile":"13720045595

**Comment by yinglingqihang** [comment]
试了好多次还是一直走defaultphone 这个，他们的优先级是那个最大？defaultphpone/user.csv/alertmanage  alertamanage是自定义的模板

**Comment by feiyu563** [comment]
文档里面写的有



---原始邮件---
发件人: "yinglingqihang"<notifications@github.com&gt;
发送时间: 2021年2月4日(周四) 下午5:39
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "feiyu563"<244217140@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 在alertmanage里面怎么写多个电话号码？ (#104)




 
试了好多次还是一直走defaultphone 这个，他们的优先级是那个最大？defaultphpone/user.csv/alertmanage  alertamanage是自定义的模板

**Comment by yinglingqihang** [comment]
我把版本改成了4.0.2 然后支持了， 是不是版本有问题？

**Comment by yinglingqihang** [comment]
但是我昨天配置的模板不能用了，日志里面报错：
2021/02/04 18:22:30.033 [C] [panic.go:679]  the request url is  /prometheusalert
2021/02/04 18:22:30.033 [C] [panic.go:679]  Handler crashed with error runtime error: invalid memory address or nil pointer dereference

**Comment by yinglingqihang** [comment]
解决了 就是换了版本后好了
