### ISSUE TITLE
支持 Postgers 作为数据库

### ISSUE THREAD

**Issue by soloradish** [feiyu563/PrometheusAlert#107]
我看了下 beego orm 是支持 postgres 这个数据库的, 应该只需要在启动时注册一下 db 地址就可以了.

可以使用 `pg_` 这个前缀作为 postgres 的配置前缀. 
可能还需要添加 postgres driver 作为依赖 ( 这个我不清楚 )
然后还有就是需要一个 postgres 版本的 .sql 文件用于初始化数据库

我是不太会 golang, 本地起 go 环境又很不方便, 所以只能提个需求, 麻烦作者来实现啦

感谢感谢

**Comment by feiyu563** [comment]
等我抽空测试下接入

**Comment by feiyu563** [comment]
master分支的最新版本已经支持postgres数据库，sql需要自行导入下
