### ISSUE TITLE
阿里云告警url中传入的电话号还是不起作用？

### ISSUE THREAD

**Issue by chaishiqi** [feiyu563/PrometheusAlert#108]
RT，调用告警url，传入phone=手机号，实际还是会找配置文件中的defaultphone，用的是最新版本

**Comment by feiyu563** [comment]
把你的alertmanager里面配置的URL贴下，还有日志顺便也贴出来我看下

**Comment by chaishiqi** [comment]
![微信截图_20210301195322](https://user-images.githubusercontent.com/15074168/109497129-8ba9a500-7acc-11eb-917b-8effdc3f831f.png)
![微信截图_20210301201748](https://user-images.githubusercontent.com/15074168/109497144-92381c80-7acc-11eb-94cd-10755b5a86ec.png)
![微信截图_20210301202029](https://user-images.githubusercontent.com/15074168/109497154-95330d00-7acc-11eb-8319-6520206e0cc1.png)
![微信截图_20210301202322](https://user-images.githubusercontent.com/15074168/109497162-982dfd80-7acc-11eb-9c33-b4fb2a804b20.png)

图1: 日志报模板缺少对应参数
图2: grafana测试面板，造了个告警
图3: 配置的grafana告警渠道
图4: 阿里云电话的模板配置

**Comment by feiyu563** [comment]
从日志来看是你的自定义模板没有查询到，应该是模板没保存或者你部署的多个PrometheusAlert？

**Comment by chaishiqi** [comment]
![微信截图_20210302110726](https://user-images.githubusercontent.com/15074168/109590776-88073400-7b47-11eb-8952-5d98849496f7.png)
保存了鸭，也只有一个alert，确认地址是对的。有个疑问，模板测试填入的手机号，点击测试，call的也是配置文件里的defaultphone，这是正常的么？

**Comment by feiyu563** [comment]
看下你的日志有没有报错



---原始邮件---
发件人: "chaishiqi"<notifications@github.com&gt;
发送时间: 2021年3月2日(周二) 中午11:09
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "feiyu563"<244217140@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 阿里云告警url中传入的电话号还是不起作用？ (#108)




 

 保存了鸭，也只有一个alert，确认地址是对的。有个疑问，模板测试填入的手机号，点击测试，call的也是配置文件里的defaultphone，这是正常的么？

**Comment by feiyu563** [comment]
这确实是个bug，我马上修复下

**Comment by feiyu563** [comment]
最新的 v4.3.3版本已经修复该问题。 https://github.com/feiyu563/PrometheusAlert/releases/tag/v4.3.3

**Comment by chaishiqi** [comment]
好的我试试，辛苦啦
