### ISSUE TITLE
prometheus_cst_time=1不生效

### ISSUE THREAD

**Issue by xcrzh** [feiyu563/PrometheusAlert#109]
prometheus：
版本：2.24.0
时区：UTC
启动方式：docker容器

修改app.conf中的prometheus_cst_time=1配置项后，钉钉收到的报警信息的时间依然是UTC时区

告警级别：3
开始时间：2021-03-02T03:13:27.276720123Z
结束时间：0001-01-01T00:00:00Z
故障主机IP：10.0.0.130:389

**Comment by feiyu563** [comment]
用的自定义模板？自定义模板有



---原始邮件---单独的模版函数处理
发件人: "xcrzh"<notifications@github.com&gt;
发送时间: 2021年3月2日(周二) 中午11:22
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] prometheus_cst_time=1不生效 (#109)




 
prometheus：
 版本：2.24.0
 时区：UTC
 启动方式：docker容器
 
修改app.conf中的prometheus_cst_time=1配置项后，钉钉收到的报警信息的时间依然是UTC时区
 
告警级别：3
 开始时间：2021-03-02T03:13:27.276720123Z
 结束时间：0001-01-01T00:00:00Z
 故障主机IP：10.0.0.130:389

**Comment by xcrzh** [comment]
没有使用自定义模板，使用的默认的AlertTemplate中的钉钉模板

**Comment by feiyu563** [comment]
那就就是自定义模板



---原始邮件---
发件人: "xcrzh"<notifications@github.com&gt;
发送时间: 2021年3月2日(周二) 中午1:44
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "feiyu563"<244217140@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] prometheus_cst_time=1不生效 (#109)




 
没有使用自定义模板，使用的默认的AlertTemplate中的钉钉模板

**Comment by xcrzh** [comment]
嗯嗯 那就是使用了自定义模板。因为我发现容器启动的prometheus和alertmanager无论怎么修改，都是使用的UTC时区，正好看到了您的程序里有prometheus_cst_time这个配置项，但是发现修改了之后重新启动还是不行。请问有什么解决办法吗？

**Comment by feiyu563** [comment]
参考这个：https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/customtpl.md

**Comment by xcrzh** [comment]
已经解决了问题，非常感谢

**Comment by filcoplax** [comment]
> 已经解决了问题，非常感谢

怎么解决的能讲下吗?自定义模板的编写我看了几遍,感觉就是 GetCSTtime,没问题.可是发出来的消息就一直都是机器时间,没有转换.我这边用的 grafana到企业微信的默认自定义模板

```
2021/04/14 08:35:18.344 [D] [value.go:460]  [1618389318344805952] {"dashboardId":1,"evalMatches":[{"value":100,"metric":"High value","tags":null},{"value":200,"metric":"Higher Value","tags":null}],"message":"Someone is testing the alert notification within grafana.","orgId":0,"panelId":1,"ruleId":0,"ruleName":"Test notification","ruleUrl":"http://grafana.sy/grafana/","state":"alerting","tags":{},"title":"[Alerting] Test notification"}
2021/04/14 08:35:18.345 [I] [prometheusalert.go:76]  [1618389318344805952] [weixin] {"msgtype":"markdown","markdown":{"content":"\r\n[Grafana告警信息](http://grafana.sy/grafana/)\r\n\u003e**Test notification**\r\n\u003e告警级别:严重\r\n开始时间:2021-04-14 08:35:18\r\nSomeone is testing the alert notification within grafana.\r\n"}}

2021/04/14 08:35:18.614 [I] [prometheusalert.go:76]  [1618389318344805952] [weixin] {"errcode":0,"errmsg":"ok"}
2021/04/14 08:35:18.614 [D] [server.go:2836]  | 172.16.127.105| 200 | 269.526245ms|   match| POST     /prometheusalert   r:/prometheusalert
2021/04/14 08:35:20.217 [D] [server.go:2836]  |     172.20.0.1| 200 |   1.567648ms|   match| GET      /     r:/
```

**Comment by feiyu563** [comment]
参考这个文档https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/customtpl.md

**Comment by filcoplax** [comment]
> 参考这个文档https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/customtpl.md

文档我看了好多遍了, 感觉预设的自定义模板没什么问题,使用的是 prometheus的企业微信自定义模板

然后问题是文档里这部分
```
目前支持两种使用方式：

取的当前时间 {{GetCSTtime ""}} ,如：
```
说的是{{GetCSTtime ""}} 取当前时间.

然后模板里是
```
>告警级别:严重
开始时间: {{GetCSTtime ""}}
{{.message}}
```
因为grafana发的告警信息没有包含时间,所以我就理所当然的用了获取当前时间

然而最后获得的时间没有转换为 cst时间


然后我看了master下的代码
controller/public.go
```
//转换UTC时区到CST
func GetCSTtime(date string) string {
	var tm string
	tm = time.Now().Format("2006-01-02 15:04:05")
	if date != "" {
		T1 := date[0:10]
		T2 := date[11:19]
		T3 := T1 + " " + T2
		tm2, _ := time.Parse("2006-01-02 15:04:05", T3)
		h, _ := time.ParseDuration("-1h")
		tm3 := tm2.Add(-8 * h)
		tm = tm3.Format("2006-01-02 15:04:05")

	}
	return tm
}
```
所以, 如果我照文档里填的, GetCSTtime 的参数使用 ""的话, 那么就直接返回tm,而tm就是 time.now() ...

如有错误还请指正.

**Comment by feiyu563** [comment]
确实是取的当前时间

**Comment by filcoplax** [comment]
> 确实是取的当前时间

我有什么好办法用这个函数来取当前时间的cst形式

不然就只能改dockfile改容器内时区了.我以为

> 确实是取的当前时间

确实是取当前时间 -_-.
问题grafana报警不提供时间,只能获取当前时间,想了个办法总算曲线救国,搞定了.
感谢作者大大的热心回复.

grafana wechat告警模板内容:
```
{{if eq .state "ok"}}
[Grafana恢复信息]({{.ruleUrl}})
>**{{.ruleName}}**
>告警级别:严重
开始时间:{{GetCSTtime (GetCSTtime "")}}
{{.message}}
{{else}}
[Grafana告警信息]({{.ruleUrl}})
>**{{.ruleName}}**
>告警级别:严重
开始时间:{{GetCSTtime  (GetCSTtime "")}}
{{.message}}
{{end}}
```

**Comment by lusson-luo** [comment]
> GetCSTtime

使用 GetCSTtime 解决问题
