### ISSUE TITLE
能否考虑支持生产告警事件统计报表，方便运维人员查看统计

### ISSUE THREAD

**Issue by ilanni2460** [feiyu563/PrometheusAlert#112]
能否考虑支持生产告警事件统计报表，方便运维人员查看统计

**Comment by feiyu563** [comment]
目前有metrics可以用于统计



---原始邮件---
发件人: "烂泥行天下"<notifications@github.com&gt;
发送时间: 2021年3月3日(周三) 中午1:21
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 能否考虑支持生产告警事件统计报表，方便运维人员查看统计 (#112)




 
能否考虑支持生产告警事件统计报表，方便运维人员查看统计

**Comment by Zhang21** [comment]
目前支持告警落地到数据库或ES。
