### ISSUE TITLE
[Question] 当前是否还不支持加签的钉钉通知

### ISSUE THREAD

**Issue by liangyuanpeng** [feiyu563/PrometheusAlert#113]
首先感谢PrometheusAlert的维护人以及贡献者,这是一个不错的项目.  

我在配置钉钉通知时希望可以使用加签类型的通知,看了文档似乎没有找到有地方填写`secrets`

如果我漏看了文档请提示我,Thanks.

**Comment by feiyu563** [comment]
在app.conf的标题那里配置
