### ISSUE TITLE
权限验证设计

### ISSUE THREAD

**Issue by myselfghost** [feiyu563/PrometheusAlert#117]
有时候webhook不得不开放到外网，为了安全，部分路由需要做权限验证，对于这个部分，作者有什么规划吗？
没有的话，打算对 MainController ，做一个简单的session 校验。

**Comment by feiyu563** [comment]
目前还没有这方面的计划，主要考虑的各系统WebHook本身不一定都能兼容，但是后期可能会考虑在Url中加入token的方式来加强安全方面的设计

**Comment by myselfghost** [comment]
> 目前还没有这方面的计划，主要考虑的各系统WebHook本身不一定都能兼容，但是后期可能会考虑在Url中加入token的方式来加强安全方面的设计

确实是，有些系统不支持验证。
我只是说的UI 部分,模板修改部分，就是目前的MainController部分加简单的验证，避免陌生人打开UI 做一些不正常的操作。

**Comment by feiyu563** [comment]
这个容易，我抽时间加下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月12日(周一) 晚上6:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 权限验证设计 (#117)




  
目前还没有这方面的计划，主要考虑的各系统WebHook本身不一定都能兼容，但是后期可能会考虑在Url中加入token的方式来加强安全方面的设计
  
确实是，有些系统不支持验证。
 我只是说的UI 部分,模板修改部分，就是目前的MainController部分加简单的验证，避免陌生人打开UI 做一些不正常的操作。

**Comment by feiyu563** [comment]
#[v4.3.4版本](https://github.com/feiyu563/PrometheusAlert/releases/tag/v4.3.4)  已经更新UI登录
