### ISSUE TITLE
prometheus指标数大的话 会是科学计数法的值 是否支持转换

### ISSUE THREAD

**Issue by xlovepython** [feiyu563/PrometheusAlert#118]
```
"alerts": [
    {
        "status": "firing",
        "labels": {
            "alertname": "inode warning",
            "device": "/dev/mapper/centos-root",
            "fstype": "xfs",
            "group": "canary",
            "instance": "192.168.246.2:8082",
            "job": "node",
            "level": "3",
            "monitor": "codelab-monitor",
            "mountpoint": "/",
            "name": "prometheusalertcenter",
            "value": "8.831563e+06"
        },
```
类似上面的 8.831563e+06

**Comment by feiyu563** [comment]
Prometheusalert只负责转发消息，处理消息内容你可以用自定义模板试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月22日(周四) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] prometheus指标数大的话 会是科学计数法的值 是否支持转换 (#118)




 "alerts": [     {         "status": "firing",         "labels": {             "alertname": "inode warning",             "device": "/dev/mapper/centos-root",             "fstype": "xfs",             "group": "canary",             "instance": "192.168.246.2:8082",             "job": "node",             "level": "3",             "monitor": "codelab-monitor",             "mountpoint": "/",             "name": "prometheusalertcenter",     ###         "value": "8.831563e+06"         },
