### ISSUE TITLE
aliyun 短信发送失败

### ISSUE THREAD

**Issue by markliby** [feiyu563/PrometheusAlert#12]
阿里云短信发送失败
失败原因:
参数错误(isv.PARAM_LENGTH_LIMIT)
建议:
建议修改参数长度
是由于短信内容过长导致吗？是否可以精简阿里云短信信息呢？

**Comment by pzqu** [comment]
在公有云上配置告警都是有一样的套路，如果你不是政府企业，是个人测试的话，短信长度是被限制的。你必须配置相应的短信模板 来发送告警 信息。

### 为什么要限制长度呢？
* 通常公有云短信是被用来发送验证码的，所以会限制长度。
* 防止你胡乱发送告警信息，包含黄赌毒等违法信息

**Comment by feiyu563** [comment]
短信的长度部分平台确实有限制，腾讯云的之前似乎没有限制，华为和阿里的好像都限制了长度

**Comment by feiyu563** [comment]
PrometheusAlert方面做限制的意义似乎不大，只能在使用帮助里面做个提醒。

**Comment by mengshuai85** [comment]
其实可以把 短信的内容做一些精简，只需要发送 desc的内容就够了，其他的 可以清理掉
