### ISSUE TITLE
为什么我的告警通知时间比实际时间少8个小时？该怎么配置？app.conf里面我也开启了转CST了

### ISSUE THREAD

**Issue by luckydzj** [feiyu563/PrometheusAlert#122]
为什么我的告警通知时间比实际时间少8个小时？该怎么配置？app.conf里面我也开启了转CST了

**Comment by feiyu563** [comment]
app.conf里面配置的是针对接口/prometheus/alert的，如果你使用的是/prometheusalert这个自定义模板的接口，那么需要使用自定义模板函数处理，这些在文档里面有说明
