### ISSUE TITLE
飞书如何把链接转换为图片显示

### ISSUE THREAD

**Issue by Phoebus888** [feiyu563/PrometheusAlert#126]
![image](https://user-images.githubusercontent.com/45359605/123536292-08d3e680-d75c-11eb-9f69-390386f7cc07.png)

**Comment by feiyu563** [comment]
参考这个官方文档
https://open.feishu.cn/document/ukTMukTMukTM/uADOwUjLwgDM14CM4ATN

需要先上传图片到飞书，然后得到图片id，然后通过markdown嵌入

**Comment by yuhonglei666** [comment]
请问这个解决了吗？具体如何操作，我在markdown测试中可以正常显示图片

**Comment by yuhonglei666** [comment]
@feiyu563

**Comment by wanglongsxr** [comment]
> 请问这个解决了吗？具体如何操作，我在markdown测试中可以正常显示图片

应该没有，目前即便是已经把图片上传到飞书，也不支持markdown，看飞书的官方文档，markdown图片的支持是需要 tag:"markdown"的，但看了源码发现该项目没有
