### ISSUE TITLE
告警模板配置导入的问题

### ISSUE THREAD

**Issue by Auggie321** [feiyu563/PrometheusAlert#127]
您好，
目前是否支持告警模板本地配置导入的功能？
实际内网部署持久化的时候，想在本地提前编辑好告警模板的配置并导入，不用等web起来从web编辑templates alert模板。

**Comment by feiyu563** [comment]
看你用的哪种方式存储模板，默认的SQLite3可以直接复制db文件夹下面的文件到新部署的服务下面覆盖下就行了，如果用的MySQL这些，就导出数据库的SQL文件

---原始邮件---
发件人: "auggie ***@***.***&gt;
发送时间: 2021年7月6日(周二) 上午9:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] 告警模板配置导入的问题 (#127)




 
您好，
 目前是否支持告警模板本地配置导入的功能？
 实际内网部署持久化的时候，想在本地提前编辑好告警模板的配置并导入，不用等web起来从web编辑templates alert模板。

**Comment by Auggie321** [comment]
kubernetes内部deployment没有使用pvc挂载卷，
实际pod部署好，打开网页编辑template配置模板，删除pod.再次create, template会消失的问题；

kubernetes持久化保存template的问题，就要自行选择pvc或者别的方式了对吧。
是否考虑把template的东西加入configmap里面？

**Comment by feiyu563** [comment]
支持MySQL这些存储模板，configmap目前还不能支持



---原始邮件---
发件人: "auggie ***@***.***&gt;
发送时间: 2021年7月6日(周二) 上午10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 告警模板配置导入的问题 (#127)




 
kubernetes内部deployment没有使用pvc挂载卷，
 实际pod部署好，打开网页编辑template配置模板，删除pod.再次create, template会消失的问题；
 
kubernetes持久化保存template的问题，就要自行选择pvc或者别的方式了对吧。
 是否考虑把template的东西加入configmap里面？

**Comment by Auggie321** [comment]
如果要在pod内部提前加载自制的template可能需要定制dockerfile,自己build image镜像，后面是否考虑增加feiyu563/prometheus-alert的容器镜像的Dockerfile文件说明，谢谢了

**Comment by feiyu563** [comment]
默认dockerfile已经在项目里面有了



---原始邮件---
发件人: "auggie ***@***.***&gt;
发送时间: 2021年7月6日(周二) 中午11:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 告警模板配置导入的问题 (#127)




 
如果要在pod内部提前加载自制的template可能需要定制dockerfile,自己build image镜像，后面是否考虑增加feiyu563/prometheus-alert的容器镜像的Dockerfile文件说明，谢谢了
