### ISSUE TITLE
v4.4.0 版本报错：views/index.html 的template问题

### ISSUE THREAD

**Issue by superman-killig** [feiyu563/PrometheusAlert#128]
v4.4.0 版本报错，提示beego的main.go报错；v4.4.3版本同样配置可用。

**Comment by feiyu563** [comment]
是否有日志或者截图

**Comment by superman-killig** [comment]
日志报错信息：
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; the request url is&nbsp; /
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; Handler crashed with error can't find templatefile in the path:views/index.html
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /usr/local/go/src/runtime/panic.go:965
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /mnt/hgfs/code/golang/src/PrometheusAlert/vendor/github.com/astaxie/beego/template.go:75
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /mnt/hgfs/code/golang/src/PrometheusAlert/vendor/github.com/astaxie/beego/controller.go:306
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /mnt/hgfs/code/golang/src/PrometheusAlert/vendor/github.com/astaxie/beego/controller.go:257
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /mnt/hgfs/code/golang/src/PrometheusAlert/vendor/github.com/astaxie/beego/controller.go:237
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /mnt/hgfs/code/golang/src/PrometheusAlert/vendor/github.com/astaxie/beego/router.go:865
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /usr/local/go/src/net/http/server.go:2887
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /usr/local/go/src/net/http/server.go:1952
2021/07/12 10:26:21.993 [C] [panic.go:965]&nbsp; /usr/local/go/src/runtime/asm_amd64.s:1371
2021/07/12 10:26:21.993 [server.go:3137]&nbsp; [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "feiyu563/PrometheusAlert"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [feiyu563/PrometheusAlert] v4.4.0 版本报错：views/index.html 的template问题 (#128)





 
是否有日志或者截图

**Comment by feiyu563** [comment]
升级下最新的版本，4.4.0的版本web页面有点bug

**Comment by michael-liumh** [comment]
# 4.8 版本也遇到了

2022/05/09 19:37:35.906 [C] [panic.go:1038]  the request url is  /
2022/05/09 19:37:35.906 [C] [panic.go:1038]  Handler crashed with error can't find templatefile in the path:views/index.html
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /opt/go/src/runtime/panic.go:1038
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /data/zjk/src/PrometheusAlert/vendor/github.com/astaxie/beego/template.go:75
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /data/zjk/src/PrometheusAlert/vendor/github.com/astaxie/beego/controller.go:306
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /data/zjk/src/PrometheusAlert/vendor/github.com/astaxie/beego/controller.go:257
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /data/zjk/src/PrometheusAlert/vendor/github.com/astaxie/beego/controller.go:237
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /data/zjk/src/PrometheusAlert/vendor/github.com/astaxie/beego/router.go:909
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /opt/go/src/net/http/server.go:2879
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /opt/go/src/net/http/server.go:1930
2022/05/09 19:37:35.906 [C] [panic.go:1038]  /opt/go/src/runtime/asm_amd64.s:1581

**Comment by michael-liumh** [comment]
改动了默认的prometheus-fs模板，将标题的加粗和斜体分别改成了二级标题（##）和三级标题（###），保存后，测试没问题，但刷新后就这样了
