### ISSUE TITLE
如何在一条alermanager告警的同时,在prometheusalert的多个自定义模版的渠道通知

### ISSUE THREAD

**Issue by amao-code** [feiyu563/PrometheusAlert#131]
你好!
我使用下面这种模式,只会产生webhook的地址中第一个type类型的通知,我想在alertmanager告警时,在多个渠道使用自定义的模版进行通知,应该如何去配置呢
1、类似/prometheus/router的接口方式会产生多个告警,自定义模版进行一样的参数设置时,只会产生微信的告警通知,不会产生邮件的告警通知
![image](https://user-images.githubusercontent.com/59593082/125590665-8a856c04-a4e6-47d2-97de-cc7beee7af62.png)

**Comment by feiyu563** [comment]
通过alertmanager的路由功能处理
