### ISSUE TITLE
GetCSTtime获取当前时间的值是UTC时间,我这个要如何获取正确的当前时间

### ISSUE THREAD

**Issue by amao-code** [feiyu563/PrometheusAlert#132]
1、查看文档https://feiyu563.gitbook.io/prometheusalert/prometheus/customtpl中相关自定义模版时间修改,在其中使用GetCSTtime转换startAt已经正常转换为CST时间了,但是我用来获取当前时间时,获取到的值是UTC的时间,并没有转换成预期的CST时间.
2、可以查看模板的设置是正确且已写入数据库
![image](https://user-images.githubusercontent.com/59593082/125619966-287fdd56-ec68-498a-875f-c693089f6d51.png)

3、查看后台收到的消息和发送的消息时间,startAt已经转换正确,当前日志记录时间为UTC时间,使用GetCSTtime转化时间后输出的时间还是UTC时间
![image](https://user-images.githubusercontent.com/59593082/125620599-8e31d964-c28d-45dc-939b-3b05088b7d12.png)

4、微信告警具体的时间,和日志打印的一致
![image](https://user-images.githubusercontent.com/59593082/125620892-fd389c2a-d5b2-4800-890b-ccfab5060fd4.png)

**Comment by feiyu563** [comment]
把PrometheusAlert容器的时间配置和宿主机同步下就行了，就是挂载下时间文件
