### ISSUE TITLE
阿里云语音通知，是否支持 固定电话号码？

### ISSUE THREAD

**Issue by sun642514265** [feiyu563/PrometheusAlert#133]
申请阿里云专属号码时，后台提示没有手机号码了，需要换成 固定电话号码，不知道 prometheusalert 支不支持 固定电话号码。

**Comment by feiyu563** [comment]
这个需要阿里云那边支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月19日(周一) 下午4:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] 阿里云语音通知，是否支持 固定电话号码？ (#133)




 
申请阿里云专属号码时，后台提示没有手机号码了，需要换成 固定电话号码，不知道 prometheusalert 支不支持 固定电话号码。

**Comment by sun642514265** [comment]
额 可能我没说清楚，我的意思是说  prometheusalert  语音模块（ALY_DX_CalledShowNumber） 支持 固定电话不，例如：

#阿里云电话被叫显号，必须是已购买的号码
ALY_DX_CalledShowNumber=xxxxxxxxx

**Comment by sun642514265** [comment]
ALY_DX_CalledShowNumber=固定电话

**Comment by sun642514265** [comment]
因为手机号码  和 固定电话 号码 格式 不一样，怕有兼容问题，所以咨询下 大神。

**Comment by feiyu563** [comment]
一般不会影响



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月19日(周一) 晚上6:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 阿里云语音通知，是否支持 固定电话号码？ (#133)




 
因为手机号码  和 固定电话 号码 格式 不一样，怕有兼容问题，所以咨询下 大神。

**Comment by sun642514265** [comment]
好的，非常感谢，那我申请购买，试试看。
