### ISSUE TITLE
prometheusalert模板新建出问题，时区如何调整

### ISSUE THREAD

**Issue by SirBlues** [feiyu563/PrometheusAlert#134]
我发现prometheusalert创建完毕之后自定义模板会出问题，我新建了一个微信机器人告警，和第二个除了名字不一样外，剩下的都一样，但是依然无法使用[E] [value.go:476]  [1627011604425972787] template: :7: undefined variable "$alert"，用自己的模板也报错，只能用官方默认的模板才行，不知道为什么？

我发现时区比现实时间少了8小时，不知道时区在哪里修改？

**Comment by feiyu563** [comment]
你这报错说明你的模板里面缺少定义的变量alert，市区问题参考自定义模板函数部分

**Comment by SirBlues** [comment]
能不能详细点呢，不太懂

**Comment by feiyu563** [comment]
文档里面都有示例



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月23日(周五) 下午5:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] prometheusalert模板新建出问题，时区如何调整 (#134)




 
能不能详细点呢，不太懂
