### ISSUE TITLE
飞书机器人推送消息的日志中邮箱字段的值为开发者邮箱

### ISSUE THREAD

**Issue by srezone** [feiyu563/PrometheusAlert#135]
配置飞书自定义机器人后，使用默认的飞书模板推送告警信息，截取程序日志中的Json字段发现email字段的邮箱为开发者的邮箱。
Json内容如下：
{"msg_type":"interactive","email":"244217140@qq.com","card":{"config":{"wide_screen_mode":true,"enable_forward":true},"elements":[{"tag":"div","text":{"content":"\r\n\r\n**[Prometheus告警信息](http://......
请问这个email字段如何修改掉，作用是什么呢？我在自定义模板的编辑界面没有找到相关字段配置。

**Comment by feiyu563** [comment]
默认填充的，没有实际作用，可以在源代码或者@功能里面覆盖掉
