### ISSUE TITLE
阿里云短信报警模板怎么传内容到阿里云的短信模板中

### ISSUE THREAD

**Issue by BadMan008** [feiyu563/PrometheusAlert#136]
阿里云短信报警模板怎么传内容到阿里云的短信模板中
咱们这端有个模板 阿里云端有个模板两个怎么传内容啊。 有实例模板吗

**Comment by feiyu563** [comment]
PrometheusAlert的模板所生成的内容就是阿里云短信模板里面的参数



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月27日(周二) 晚上6:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] 阿里云短信报警模板怎么传内容到阿里云的短信模板中 (#136)




 
阿里云短信报警模板怎么传内容到阿里云的短信模板中
 咱们这端有个模板 阿里云端有个模板两个怎么传内容啊。 有实例模板吗

**Comment by BadMan008** [comment]
我在阿里云定义的模板为：告警${code}
在PrometheusAlert定义的{{ range $k,$v:=.alerts }}故障主机{{ $v.annotations.description | printf "%.25s" }}{{end}}
但是一直提示变量参数超过限制25长度
怎么才能把告警的详细信息传到短信啊？有阿里云的模板和prometheusalert的模板 参考下吗？  我看跟阿里云短信对接必须要有${code}才可以 这个变量取的内容是？

**Comment by feiyu563** [comment]
按照github上文档配置你的阿里云短信，PrometheusAlert的模板使用默认的腾讯短信的就可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月28日(周三) 下午2:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 阿里云短信报警模板怎么传内容到阿里云的短信模板中 (#136)




 
我在阿里云定义的模板为：告警${code}
 在PrometheusAlert定义的{{ range $k,$v:=.alerts }}故障主机{{ $v.annotations.description | printf "%.25s" }}{{end}}
 但是一直提示变量参数超过限制25长度
 怎么才能把告警的详细信息传到短信啊？有阿里云的模板和prometheusalert的模板 参考下吗？  我看跟阿里云短信对接必须要有${code}才可以 这个变量取的内容是？

**Comment by BadMan008** [comment]
好的 我测试一下

**Comment by BadMan008** [comment]
PrometheusAlert的模板使用默认的腾讯短信的就可以
------
模板
{{ range $k,$v:=.alerts }}{{if eq $v.status "resolved"}}
[Prometheus恢复信息]
{{$v.labels.alertname}}
告警级别：{{$v.labels.level}}
故障主机IP：{{$v.labels.instance}}
{{$v.annotations.description}}
{{else}}
Prometheus告警信息]
{{$v.labels.alertname}}
告警级别：{{$v.labels.level}}
故障主机IP：{{$v.labels.instance}}
{{$v.annotations.description}}
{{end}}
{{ end }}

阿里云端，短信模板为
![image](https://user-images.githubusercontent.com/22131840/127282706-217b821e-e1f3-49e4-a5cc-fea7e04d37ae.png)

测试报警一直报错：
{"RequestId":"C9AA7510-4F59-44BD-AD5D-9598B332444F","Message":"params over length limit is 25","Code":"isv.PARAM_LENGTH_LIMIT"}
![image](https://user-images.githubusercontent.com/22131840/127282921-5720a64e-7432-49f1-9588-4a38251a227b.png)

--------
以上 我需要怎么解决才可以获取正确的短信内容啊，还请指教下 感谢

**Comment by feiyu563** [comment]
短信有长度限制，你自己改的模板内容太长了

**Comment by feiyu563** [comment]
或者你可以联系阿里云放开限制

**Comment by BadMan008** [comment]
咱们这个配置是把PrometheusAlert的模板的所有内容作为${code}传到短信端模板中的code变量中吗
![image](https://user-images.githubusercontent.com/22131840/127286043-8723a981-b65b-4dad-aaf0-f4ca304ceef0.png)

**Comment by feiyu563** [comment]
对

**Comment by BadMan008** [comment]
可以分多个变量对应阿里云的多个变量吗？ 以为一个变量限制就是25   咱们变量都{{$v.labels.instance}}   v.labels.instance这个设置成变量 阿里云那边不合规范

**Comment by feiyu563** [comment]
阿里的不支持IP中的. 这个符号，需要你在Prometheus里面做下处理
