### ISSUE TITLE
golang mysql崩溃导致告警通知丢失

### ISSUE THREAD

**Issue by amao-code** [feiyu563/PrometheusAlert#139]
1、程序异常日志
今日在测试验证一些告警通知时发现,程序会由于golang mysql崩溃导致告警通知丢失,并且不会重发
其中的程序异常日志如下面截图中,mysql的相关异常,导致发送的context为空
![wecom-temp-e1e47c9ece6af6f81a1211b1a5f75c27](https://user-images.githubusercontent.com/59593082/128304540-013975ee-f8cd-47a6-ac9f-d9f92bc4b0db.png)
2、可以查看微信收到的信息,同样没有10.49分的这条信息
![image](https://user-images.githubusercontent.com/59593082/128305726-992d5a36-1bf4-4965-be7d-d89ce461a430.png)

这样会导致如果当条告警通知丢失,如果alertmanager分组的该条告警repeat_interval设置的很大的情况下,产生告警时间会误差较大
3、目前是参考了下面的博客,对prometheusalert的go.mod里面的github.com/go-sql-driver/mysql,替换到了1.5.0后重新打包的镜像
https://blog.csdn.net/weixin_42119866/article/details/114500012

4、重新按照上面的博客模拟mysql关闭后再重新启动,执行测试任务,可以看到日志里面,出现这一行错误,但是告警通知还是正常给微信发送了
[mysql] 2021/08/05 15:50:20 packets.go:122: closing bad idle connection: EOF
![wecom-temp-294ee6305ee614ef6dd5ae023c6e8700](https://user-images.githubusercontent.com/59593082/128315276-56354ae8-d8b1-4e3d-b012-a4c320f2b94d.png)

我不确定这样修改是否完全解决掉该问题(仅测试了mysql挂掉后又启动的情况,wait_timeout的情况没有进行测试),程序是否会产生其他的异常,希望作者能修复一下这个问题

**Comment by feiyu563** [comment]
我抽时间测试下，可能是数据库重连的问题

**Comment by feiyu563** [comment]
已经调整数据库连接池部分参数解决
