### ISSUE TITLE
告警显示问题

### ISSUE THREAD

**Issue by aluopy** [feiyu563/PrometheusAlert#147]
![16304838629236](https://user-images.githubusercontent.com/69625113/131636570-c36ba4d5-b156-4152-88a7-2053294ee2b1.png)
请问下我发送到企业微信机器人的告警信息里面为什么上面空出来那么多，感觉很影响美观啊。
用的这个模板：
```
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }}
{{if eq $v.status "resolved"}}
#### [Prometheus恢复信息]({{$v.generatorURL}})

> <font color="info">告警名称</font>：[{{$v.labels.alertname}}]({{$var}})
> <font color="info">告警级别</font>：{{$v.labels.severity}}
> <font color="info">开始时间</font>：{{$v.startsAt}}
> <font color="info">结束时间</font>：{{$v.endsAt}}
> <font color="info">实例地址</font>：{{$v.labels.instance}}
> <font color="info">主机名称</font>：{{$v.labels.hostname}}

**{{$v.annotations.description}}**
{{else}}
#### [Prometheus告警信息]({{$v.generatorURL}})

> <font color="#FF0000">告警名称</font>：[{{$v.labels.alertname}}]({{$var}})
> <font color="#FF0000">告警级别</font>：{{$v.labels.severity}}
> <font color="#FF0000">开始时间</font>：{{$v.startsAt}}
> <font color="#FF0000">结束时间</font>：{{$v.endsAt}}
> <font color="#FF0000">实例地址</font>：{{$v.labels.instance}}
> <font color="#FF0000">主机名称</font>：{{$v.labels.hostname}}

**{{$v.annotations.description}}**
{{end}}
{{ end }}
```

![企业微信截图_16304844566938](https://user-images.githubusercontent.com/69625113/131637644-85e04d9d-3a15-4fc1-853d-6fca272b136e.png)
但是我看到这个模板的作者发出的告警信息显示又是正常的：
![image](https://user-images.githubusercontent.com/69625113/131637322-bb376881-833e-47a2-9fe4-6cccb0a0c87e.png)

这个是什么情况呀，不知道怎么处理了。

**Comment by feiyu563** [comment]
调试下你的模板，应该有换行符

**Comment by aluopy** [comment]
> 调试下你的模板，应该有换行符

可是我用系统默认添加好的WX模板也是这样的呀，用的这个模板：
![image](https://user-images.githubusercontent.com/69625113/131935525-59e091b9-b59f-4b26-9979-5279322caeb3.png)
告警效果图：
![企业微信截图_16306316287908](https://user-images.githubusercontent.com/69625113/131935627-c1ac184b-181e-4f87-b053-2e8bdcc9a4c5.png)
测试界面截图：
![image](https://user-images.githubusercontent.com/69625113/131935831-d7565ab0-e832-428c-b327-a2ec925a628a.png)

**Comment by feiyu563** [comment]
试试把前三行合并到一行

**Comment by aluopy** [comment]
> 试试把前三行合并到一行

![image](https://user-images.githubusercontent.com/69625113/131972045-6dee0d8c-9485-4fcc-a117-ab8df8af0713.png)
![image](https://user-images.githubusercontent.com/69625113/131972083-7bc79413-3548-434a-90e5-73ba6f4868f1.png)
可以了，谢谢。

**Comment by yinyu985** [comment]
前面的空行解决了，下面还是有，搞不清楚哪里出问题了
![image](https://user-images.githubusercontent.com/51993157/148511236-cd71420c-4434-4fd9-8582-82c46ef986e2.png)
