### ISSUE TITLE
钉钉多机器人支持（问题反馈）

### ISSUE THREAD

**Issue by tay3223** [feiyu563/PrometheusAlert#148]
问题描述：

我有10个钉钉机器人，由于钉钉机器人每分钟的信息发送频次限制，过去我们把10个机器人的URL加入到一个数组中，然后向机器人推送消息时，从数组中随机取到一个机器人连接进行消息推送（PS：上一个已经取到的URL，至少下一次随机时，不再重复取用）

这样可以规避钉钉的每分钟消息发送频次，请问这么一种用法，在prometheusAlert中我该如何配置？（作者回复：下个版本支持）

此处备忘一下，辛苦作者大佬下个版本更新时支持一下添加多个钉钉机器人的URL；

作者辛苦了，开源社区的大佬们万岁！

**Comment by feiyu563** [comment]
4.6的版本已经增加上述功能
