### ISSUE TITLE
关于添加zabbix告警源的问题

### ISSUE THREAD

**Issue by hebaodanroot** [feiyu563/PrometheusAlert#149]
zabbix的客户端必须添加-t的参数吗，可以实现-t不是必须参数也没有默认值。而是读取配置文件app.conf的配置呢。实现./zabbix  -m 告警测试 -type dd -d http://127.0.0.1:8080/zabbix/alert 就可以发送到钉钉呢

**Comment by feiyu563** [comment]
可以实现，等我下一个版本更新下

**Comment by hebaodanroot** [comment]
好的，这样多个钉钉就不用重复添加了，别的通知也是同理

**Comment by feiyu563** [comment]
4.6的版本已经增加上述功能
