### ISSUE TITLE
关于固定告警级别发送相应告警渠道的灵活性问题

### ISSUE THREAD

**Issue by pzqu** [feiyu563/PrometheusAlert#15]
比如告警级别为3，则是短信告警，但是其他级别就无法发送短信告警。

假如只有一种告警渠道的情况下，例如邮件，是不是可以有一种更灵活的方式把告警发出去？

**Comment by feiyu563** [comment]
这个默认的逻辑里面，微信告警和钉钉告警是不区分级别默认发送的，然后再判断是否达到短信和电话告警级别，如果达到了，会触发短信或者电话告警，同时不影响微信和钉钉的发送。
