### ISSUE TITLE
V4.4.3版本配置飞书告警，自定义模板和测试模板均报错first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by amao-code** [feiyu563/PrometheusAlert#150]
1、程序日志截图
![image](https://user-images.githubusercontent.com/59593082/131969697-ca5271a3-f536-41ca-82f2-2d2a56700954.png)
2、解析的json格式，这里解析的json也没有看到是哪里的报错有这个冒号
![image](https://user-images.githubusercontent.com/59593082/131969773-9235205e-ef2a-40d8-95c1-ed9bff8cddfa.png)
![image](https://user-images.githubusercontent.com/59593082/131969809-3c5e09bf-8801-4f71-9fd2-65a13562cee6.png)
3、这一块应该是哪里的问题呢，是不是飞书的接口有更新了，然后这个版本不匹配，想麻烦作者大大看看

**Comment by feiyu563** [comment]
看报错是你的飞书机器人地址有问题

**Comment by amao-code** [comment]
好的，谢谢作者，我的问题解决了。应该是从使用飞书copy下来的地址有隐藏字符，我确认了是没有空格的。后面把地址先粘贴到一个文本文件，再从文本文件粘贴到配置里面就可以了
