### ISSUE TITLE
告警模板部分信息保存后重新打开显示空白

### ISSUE THREAD

**Issue by j0ck1e** [feiyu563/PrometheusAlert#151]
![图片](https://user-images.githubusercontent.com/22044356/132432034-6c8f3058-e145-45df-a47b-6e65cb38cf88.png)
红框部分填写好内容保存，重新打开页面变空白

![图片](https://user-images.githubusercontent.com/22044356/132432276-05f60673-1284-4fe0-8e37-b551245a93e3.png)
保存内容后红线部分的显示不对

**Comment by stayknight** [comment]
建议把页面调整下，明确测试和不会保存的部分，或者加入相应提示文字。
现在这种情况，用户发现保存失败只会以为是BUG，而只有过来查issue才能得到解答。
