### ISSUE TITLE
短信电话配置位置

### ISSUE THREAD

**Issue by BadMan008** [feiyu563/PrometheusAlert#159]
请教下，发短信手机号配置位置的优先级是？上一级读到了是不是就不走下一级的配置了呢？
手机号配置位置：
1.在自定义模板中配置phone字段:http://xxxxx//prometheusalert?type=alydx&tpl=dx-zidai&phone=手机号
2.在user.csv中配置电话，
3.在rules下面的annotations下配置配置mobile：手机号
4.在app.conf中配置默认电话

以上4种优先级是怎么样的，我现在在1没有配置phone的情况下会读4中默认的，其他2和3中配置的不读取，在1中配置phone还是不读取2，3中配置的手机号。    2和3中配置手机号什么情况下才会生效啊，方便给举个配置示例吗

**Comment by feiyu563** [comment]
号码读取优先级
自定义模板接口：Url中手机号 > CSV文件中的手机号 > app.conf的defaultphone配置
固定模板接口：rules下面的annotations中的号码 > CSV文件中的手机号 > app.conf的defaultphone配置
