### ISSUE TITLE
短信模板信息

### ISSUE THREAD

**Issue by BadMan008** [feiyu563/PrometheusAlert#160]
请教以下短信模板怎么判断annotations下的字段啊？
因为现在rules中annotations中有的包含summary有的包含message有的是description，所以配置{{ range $k,$v:=.alerts }}
告警:{{$v.annotations.description}}
{{end}}
如果annotations下不是description而是message的话，信息就打不出来了，如果写成告警:{{$v.annotations.summary}}:{{$v.annotations.description}}{{$v.annotations.message}} 没有的字段，在短信中就会显示<no value> 很是不美观

怎么加判断如果是description就打印description，如果是message就打印message啊

**Comment by feiyu563** [comment]
建议统一rules的格式来解决，告警的消息统一使用description或message。
