### ISSUE TITLE
关于kubernetes上高可用支持的问题

### ISSUE THREAD

**Issue by suridaddy** [feiyu563/PrometheusAlert#161]
关于PrometheusAlert的高可用支持，请问在哪里可以看到详细介绍？

如果可以，请帮忙解答如下疑惑：
- 如果部署到kubernetes上，高可用支持是如何实现？
- 看exmaple chart实现，貌似可以支持多实例。如果支持多实例，请问多实例之间是否构成集群？如果不构成集群，重复告警如何避免？

**Comment by feiyu563** [comment]
数据库改成mysql或者postgressql即可，多个PrometheusAlert均连接同一个数据库实例就可以组成集群，然后通过Kubernetes service的负载均衡

**Comment by JokerQueue** [comment]
自定义模版加载进内存处理后，多个实例的内存如何更新
