### ISSUE TITLE
钉钉@某个人怎么使用

### ISSUE THREAD

**Issue by Gerrylinux** [feiyu563/PrometheusAlert#163]
目前没有看到相关文档。可以提供个文档，下面截图不是很理解，这个手机号是放在告警模板，还是prometheus 的 rule模板
![image](https://user-images.githubusercontent.com/31839722/137890923-888b29af-71d2-41e6-9ca9-d4175e7f107a.png)

**Comment by feiyu563** [comment]
![image](https://user-images.githubusercontent.com/25146052/141251189-7fa39934-5adf-4c36-816c-d40f6aa5d23d.png)

通过在Url中增加`&at=1539510xxxx`即可
比如 
`http://[prometheusalert_url]:8080/prometheusalert?type=dd&tpl=prometheus-dd&rr=true&ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxx&at=1539510xxxx`
