### ISSUE TITLE
打开告警标题，无法访问正确的prometheus 和alertmanager ip地址

### ISSUE THREAD

**Issue by KyleChou** [feiyu563/PrometheusAlert#17]
http://901877c82a2d:9090/graph?g0.expr=rate%28elasticsearch_indices_docs%7Bes_data_node%3D%22true%22%7D%5B10m%5D%29+%3C+1&g0.tab=1

http://8d861cbf4b5e:9093/

打开后url 变成上面这样的

**Comment by feiyu563** [comment]
这个需要在Prometheus和alertmanager启动配置里面指定各自的地址



---原始邮件---
发件人: "Kyle Chou"<notifications@github.com&gt;
发送时间: 2020年4月8日(周三) 中午11:57
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 打开告警标题，无法访问正确的prometheus 和alertmanager ip地址 (#17)




 
http://901877c82a2d:9090/graph?g0.expr=rate%28elasticsearch_indices_docs%7Bes_data_node%3D%22true%22%7D%5B10m%5D%29+%3C+1&amp;g0.tab=1
 
http://8d861cbf4b5e:9093/
 
打开后url 变成上面这样的

**Comment by feiyu563** [comment]
参考配置启动prometheus和alertmanager
prometheus:
```
--web.external-url=http://xxxx.xxx.com
```

alertmanager:
```
--web.external-url=http://xxxx.xxx.com
```
