### ISSUE TITLE
.git目录过大，有考虑优化下吗？

### ISSUE THREAD

**Issue by Zhang21** [feiyu563/PrometheusAlert#170]
rt

**Comment by feiyu563** [comment]
我尽快做下清理

**Comment by Zhang21** [comment]
可以参考下这两个: 

- <https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-the-git-repository>
- <https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history>

**Comment by feiyu563** [comment]
尝试了下，最终还是需要github官方客服去刷新下缓存才行，我这边已经把没用的文件都清理掉了
