### ISSUE TITLE
增加可匹配目录反向代理的支持

### ISSUE THREAD

**Issue by guvmao** [feiyu563/PrometheusAlert#174]
增加对二级路径的匹配
www.xxx.com/prometheusalert
类似于 
prometheus 的 [ --web.external-url=prometheus ] 选项
grafana 的 [ root_url=%(protocol)s://%(domain)s:%(http_port)s/grafana/ ] 配置项

**Comment by xykong** [comment]
非常需要

**Comment by Zhang21** [comment]
这个功能nginx反代是不是也能实现？

**Comment by guvmao** [comment]
> 这个功能nginx反代是不是也能实现？

如果使用 test.test.com/alert访问
匹配 alert 路由到项目 127.0.0.1:8080 可以访问到首页，
但是点击子页面时会返回其它路由，比如 template、markdowntest、alertrouter... 
还需要对这些进行匹配
@Zhang21
