### ISSUE TITLE
时间显示不对，相差8小时

### ISSUE THREAD

**Issue by zhangqingwen** [feiyu563/PrometheusAlert#18]
PrometheusAlertPrometheus故障告警信息
 InstanceDown
 告警级别: 信息
 开始时间: 2020-04-08T07:25:49.905535979Z
 结束时间: 0001-01-01T00:00:00Z
 故障主机IP: 10.1x.x.x

**Comment by pzqu** [comment]
这个看起来是一个时区问题
UTC 通用标准时，以z来标识

**Comment by feiyu563** [comment]
目前可以通过程序配置文件中的CST时区配置转换下就行了

**Comment by zhangqingwen** [comment]
prometheus:v2.2.1

**Comment by zhangqingwen** [comment]
> 目前可以通过程序配置文件中的CST时区配置转换下就行了

prometheus_cst_time=1  
正常了，谢谢各位！
