### ISSUE TITLE
配置接入ES7.16.2无索引 

### ISSUE THREAD

**Issue by gzwlly** [feiyu563/PrometheusAlert#183]
你好，我配置接入ES7.16.2，完成后无生成索引。请问是否兼容这个版本？

**Comment by Zhang21** [comment]
此功能还在代码分支，暂未发布到新版本，所以之前的包或镜像里没有。等作者发布新版本，或自己拉代码构建。

**Comment by feiyu563** [comment]
可以使用latest的镜像，通常这个镜像就是master分支最新的代码构建
