### ISSUE TITLE
修改prometheusalert 飞书默认模版，但是一直不能启用

### ISSUE THREAD

**Issue by jeffzhao99** [feiyu563/PrometheusAlert#185]
登陆web 界面，在alerttemplate 界面修改默认飞书模版，然后保存模版。但是后面发送的告警还是使用以前的模版，修改的模版没有起作用，请问，怎么能把修改的默认模版启用？

**Comment by Zhang21** [comment]
请注意你使用的接口地址是哪一个！是默认接口地址还是自定义模板接口地址？
默认模板是代码里写死的，自定义模板需要使用自定义模板的接口地址。

**Comment by jeffzhao99** [comment]
使用的是自定义模版，没有配置，现在已经解决，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "feiyu563/PrometheusAlert"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 中午11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [feiyu563/PrometheusAlert] 修改prometheusalert 飞书默认模版，但是一直不能启用 (Issue #185)





 
请注意你使用的接口地址是哪一个！是默认接口地址还是自定义模板接口地址？
 默认模板是代码里写死的，自定义模板需要使用自定义模板的接口地址。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
