### ISSUE TITLE
恢复告警主题颜色能变为绿色吗

### ISSUE THREAD

**Issue by jeffzhao99** [feiyu563/PrometheusAlert#189]
飞书设置的告警模版标题颜色为红色，但是飞书代码这段，resolved 了可以把标题颜色设置为green, 但是一直不行，什么原因？
func PostToFeiShuv2(title, text, Fsurl, userEmail, logsign string) string {
	var color string
	if strings.Count(text, "resolved") > 0 && strings.Count(text, "firing") > 0 {
		color = "orange"
	} else if strings.Count(text, "resolved") > 0 {
		color = "green"
	} else {
		color = "red"
	}

能设置恢复告警信息字体或标题为绿色吗？

**Comment by dong-minglei** [comment]
+1

**Comment by feiyu563** [comment]
参考下面的模版，默认的模版只有告警，没有恢复
```
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }}
{{if eq $v.status "resolved"}}
**[Prometheus恢复信息]({{$v.generatorURL}})**
*[{{$v.labels.alertname}}]({{$var}})*
告警级别：{{$v.labels.level}}
状态: {{$v.status}}
开始时间：{{$v.startsAt}}
结束时间：{{$v.endsAt}}
故障主机IP：{{$v.labels.instance}}
**{{$v.annotations.description}}**
{{else}}
**[Prometheus告警信息]({{$v.generatorURL}})**
*[{{$v.labels.alertname}}]({{$var}})*
告警级别：{{$v.labels.level}}
开始时间：{{$v.startsAt}}
结束时间：{{$v.endsAt}}
故障主机IP：{{$v.labels.instance}}
**{{$v.annotations.description}}**
{{end}}
{{ end }}
```
