### ISSUE TITLE
Adding same template functions in alertmanager

### ISSUE THREAD

**Issue by phoenixgao** [feiyu563/PrometheusAlert#190]
Hi,
In the newly released 4.7, multiple string functions were added that's great!

There are another two functions in alertmanager which provide better grouping for alerts and resolves could them be added too?

The functions:
https://github.com/prometheus/alertmanager/blob/c0a7b75c9cfb0772bdf5ec7362775f5f7798a3a0/template/template.go#L262
https://github.com/prometheus/alertmanager/blob/c0a7b75c9cfb0772bdf5ec7362775f5f7798a3a0/template/template.go#L273

and example use case:
https://github.com/prometheus/alertmanager/blob/c0a7b75c9c/template/default.tmpl#L35

**Comment by feiyu563** [comment]
好的，我会尽快加入更新
