### ISSUE TITLE
支持同时发送到多个钉钉群吗？

### ISSUE THREAD

**Issue by fsckzy** [feiyu563/PrometheusAlert#193]
我的需求是这样的，我的系统里有a和b两种label，配置了两个webhook ，aa和bb。
希望能实现的功能，默认发送到aa这个webhook，当匹配到label b的时候，则两个webhook都要发送告警。

**Comment by feiyu563** [comment]
支持多个，你需要的这个功能在最新的开发分支上的告警路由功能可以实现
