### ISSUE TITLE
服务运行一段时间，连接数据库报错 Error 1243: Unknown prepared statement handler (7) given to mysqld_stmt_execute

### ISSUE THREAD

**Issue by ikewang** [feiyu563/PrometheusAlert#194]
服务刚启动是，能够看到告警模块内容，运行一会之后，服务就会报mysql相关的错误，访问不到mysql，错误信息如下：[value.go:476]  Error 1243: Unknown prepared statement handler (7) given to mysqld_stmt_execute

相关sql：
[ORM]2022/03/22 08:36:32  -[Queries/default] - [FAIL /    db.Query /     0.4ms] - [SELECT T0.`id`, T0.`tpltype`, T0.`tpluse`, T0.`tplname`, T0.`tpl`, T0.`created` FROM `prometheus_alert_d_b` T0 ] - Error 1243: Unknown prepared statement handler (7) given to mysqld_stmt_execute
2022/03/22 08:36:32.491 [1;31m[E][0m [value.go:476]  Error 1243: Unknown prepared statement handler (7) given to mysqld_stmt_execute

**Comment by feiyu563** [comment]
有可能是连接断了，后续我更新下自动重连

**Comment by feiyu563** [comment]
最新的master分支已经更新数据库连接优化
