### ISSUE TITLE
关于时区问题

### ISSUE THREAD

**Issue by snail2sky** [feiyu563/PrometheusAlert#195]
prometheus发给PrometheusAlert的就是错误的时区，慢了8个小时
是改prometheus的的时区，还是在PrometheusAlert中修改呢
在PrometheusAlert的模板中修改的话，有啥参考吗~ 还是直接利用go的方法处理时区的问题

**Comment by feiyu563** [comment]
使用PrometheusAlert 固定模板的可以在app.conf中开启时区配置
要是使用的自定义模板，参考自定义模板有个转换时区的函数处理就行了
