### ISSUE TITLE
定义webhook模板，模板测试报错template: : unexpected EOF

### ISSUE THREAD

**Issue by gls3** [feiyu563/PrometheusAlert#197]
webhook接收到请求体的JSON内容如下：
{
	"replicaSetName": "configs",
	"metricName": "NETWORK_BYTES_IN",
	"created": "2022-03-28T09:19:58Z",
	"groupId": "622ae91a69ba16074ad6d863",
	"typeName": "HOST_METRIC",
	"hostId": "32795b42b58d772c02f4d4656b209197",
	"hostnameAndPort": "127.0.0.1:21000",
	"humanReadable": "Project: yryc\n\nOrganization: Organization 0\n----------------------------------------\n\nOPEN\nNetwork: Bytes In has gone above 1 bits (avg/sec)\n127.0.0.1:21000\nCreated: 2022/03/28 09:19 GMT\nReplica Set: configs\nType: Secondary\nCurrent Value: 1,951.4 bytes\n\n----------------------------------------\n",
	"alertConfigId": "62417bcb69ba16074a44b635",
	"eventTypeName": "OUTSIDE_METRIC_THRESHOLD",
	"links": [{
		"rel": "self",
		"href": "http://127.0.0.1:8083/api/public/v1.0/groups/622ae91a69ba16074ad6d863/alerts/62417dbe69ba16074a44bfd8"
	}],
	"id": "62417dbe69ba16074a44bfd8",
	"updated": "2022-03-28T09:19:58Z",
	"currentValue": {
		"number": 1951.4,
		"units": "BYTES"
	},
	"status": "OPEN"
}

自定义的模板如下：
{{ $replicaSetName := .replicaSetName}}
{{ $metricName := .metricName}}
{{ $created := .created}}
{{ $groupId := .groupId}}
{{ $typeName := .typeName}}
{{ $hostId := .hostId}}
{{ $hostnameAndPort := .hostnameAndPort}}
{{ $humanReadable := .humanReadable}}
{{ $alertConfigId := .alertConfigId}}
{{ $eventTypeName := .eventTypeName}}
{{ $id := .id}}
{{ $updated := .updated}}
{{ $status := .status}}
{{ range $k,$v:=.links }}
{{ range $k2,$v2:=.currentValue }}
{{if eq $status "OPEN"}}
##### {{$humanReadable}}
![Opsmanager]({{$v.href}})
{{ end }}

保存后点击模板测试报错template: : unexpected EOF
不确定是否模板编写有误，希望解答，谢谢

![微信图片_20220329115551](https://user-images.githubusercontent.com/14308641/160530157-ea49d44b-6dcc-4881-83f6-39f441acf5a3.png)

**Comment by feiyu563** [comment]
{{if eq $status "OPEN"}} 错在这
