### ISSUE TITLE
同一个告警，告警恢复之后有一条记录A，有开始时间和结束时间，但是它还有一条开始时间一模一样的显示持续中的记录B

### ISSUE THREAD

**Issue by 0x0-tan** [feiyu563/PrometheusAlert#199]
就是同样的一个告警，告警恢复之后有一条记录A，有开始时间和结束时间，但是它还有一条开始时间一模一样的显示持续中的记录B，github不能传截图，发gitee上了可以看一下

**Comment by feiyu563** [comment]
这是alertmanager转发来的信息，需要从alertmanager上处理
