### ISSUE TITLE
默认的飞书告警模版，希望增加支持图片连接

### ISSUE THREAD

**Issue by ilanni2460** [feiyu563/PrometheusAlert#206]
默认的飞书告警模版，希望增加支持图片连接

**Comment by michael-liumh** [comment]
这个支持的呀。。。

**Comment by ilanni2460** [comment]
@michael-liumh 有没有demo，来个呗

**Comment by michael-liumh** [comment]
新安装的默认模板就有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月16日(周一) 下午2:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 默认的飞书告警模版，希望增加支持图片连接 (Issue #206)




 
@michael-liumh 有没有demo，来个呗

**Comment by michael-liumh** [comment]
![image](https://user-images.githubusercontent.com/40595864/170409453-11224d97-24a9-420e-a8ae-d74f0bb78755.png)
这个就是

**Comment by yuhonglei666** [comment]
@michael-liumh 这是钉钉模板吧。飞书根本不生效，图片展示不出来
