### ISSUE TITLE
docker-compose环境变量

### ISSUE THREAD

**Issue by Zyawn** [feiyu563/PrometheusAlert#207]
在docker-compose中使用环境变量不可以初始化配置文件app.conf吗，例如：
prometheusAlert:
  image: feiyu563/prometheus-alert:latest
  container_name: pa
  environment:
    - PA_OPEN_FEISHU=1
    - PA_LOGIN_USER=user
    - PA_LOGIN_PASSWORD=password

**Comment by feiyu563** [comment]
可以
