### ISSUE TITLE
Grafana-飞书报警和恢复都是一个颜色

### ISSUE THREAD

**Issue by zhushiyang** [feiyu563/PrometheusAlert#212]
如题

**Comment by ilanni2460** [comment]
+1，我这边也遇到同样的问题，而且使用的是最新的docker镜像

**Comment by Ansen** [comment]
发issue前但凡搜索一下也不至于干等

**Comment by feiyu563** [comment]
默认的模板只是参考，高级的应用可以自定义模板内容，实现告警和恢复不同颜色可以通过在模板里面加上判断语句来实现，具体的可以参考默认模板的钉钉和企业微信的写法

**Comment by zhushiyang** [comment]
> 默认的模板只是参考，高级的应用可以自定义模板内容，实现告警和恢复不同颜色可以通过在模板里面加上判断语句来实现，具体的可以参考默认模板的钉钉和企业微信的写法

grafana返回时正常状态字段是.state:ok，飞书告警中没有兼容

**Comment by zhushiyang** [comment]
> 
![image](https://user-images.githubusercontent.com/30135876/167241919-af01798a-75d0-4352-b34e-bbc7f7c6792c.png)

**Comment by putianhui** [comment]
最后怎么解决的，我测试时传入的json有state:ok 这个字段，一样的red的颜色
