### ISSUE TITLE
路由无效

### ISSUE THREAD

**Issue by clcc2019** [feiyu563/PrometheusAlert#213]
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/46099295/167107598-d41d4db9-2478-404d-89f0-c053df485c14.png">
消息还是发送到默认的webhook了

**Comment by feiyu563** [comment]
路由功能是复制消息转发，不会阻断默认的发送，也就是配置了路由的情况下，默认发送的依旧会继续发送，同时也会按照路由配置再发送一次消息

**Comment by clcc2019** [comment]
> 路由功能是复制消息转发，不会阻断默认的发送，也就是配置了路由的情况下，默认发送的依旧会继续发送，同时也会按照路由配置再发送一次消息

但是问题是路由写的另一个地址，并没有收到转发的消息
