### ISSUE TITLE
使用mysql存储，没有告警记录

### ISSUE THREAD

**Issue by clcc2019** [feiyu563/PrometheusAlert#214]
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/46099295/167114581-29102830-9f1b-4c84-8eee-44d9f0d2a319.png">

**Comment by feiyu563** [comment]
1.告警记录功能目前仅支持Prometheus
2.默认不开启告警记录，需要手动去配置文件中打开配置项

**Comment by clcc2019** [comment]
> 1.告警记录功能目前仅支持Prometheus 2.默认不开启告警记录，需要手动去配置文件中打开配置项
开启配置
<img width="505" alt="image" src="https://user-images.githubusercontent.com/46099295/167232234-5268d30d-1ab1-459f-937e-ba937eaed9de.png">
prometheus来源
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/46099295/167232258-7c6ff45d-6c9f-4aa2-aa1c-9b5608d5d045.png">
