### ISSUE TITLE
项目的roadmap的建议

### ISSUE THREAD

**Issue by homerzhou** [feiyu563/PrometheusAlert#216]
我觉得 光做一些告警的转发和模板等，并不会有太大的长期发展性，应该学习 pagerduty 或者 睿象云 ，往报警的后面去做报警事件管理，报警事件的分配和报警事件的追踪，往前可以接替grafana的告警机制（grafana的ngalert虽然已经不错，但是仍然有很多可以改进的）

做成一个可自部署的 pagerdutty 或者睿象云

**Comment by feiyu563** [comment]
感谢建议，我抽空去调研下这些产品
