### ISSUE TITLE
prometheus info级别的告警能否支持屏蔽

### ISSUE THREAD

**Issue by clcc2019** [feiyu563/PrometheusAlert#217]
prometheus info级别的告警能否支持屏蔽，目前是没有content也会调用webhook发送到企业微信
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/46099295/167396060-01cf5926-0cc7-4659-a20c-fa1a2cde5b1f.png">

**Comment by michael-liumh** [comment]
为啥不直接从根源上干掉（或者取消） info 级别的告警？？？

**Comment by clcc2019** [comment]
> 为啥不直接从根源上干掉（或者取消） info 级别的告警？？？

我们有大量来源，只是希望告警通知屏蔽info，记录还在。通过模版控制不展示info级别内容，但是PrometheusAlert仍然会向webhook发送空的内容，路由中配置@了某人的话就是机器人只有@人没有

**Comment by michael-liumh** [comment]
可以添加一个告警路由，将 info 级别的告警扔到一个不用理会的群

**Comment by feiyu563** [comment]
可以在alertmanager上直接沉默掉就行了
