### ISSUE TITLE
grayLog4.2 飞书告警发送失败

### ISSUE THREAD

**Issue by alangong114** [feiyu563/PrometheusAlert#218]
# promethuesAlert 版本
4.7

# 消息body
{"msg_type":"interactive","email":"244217140@qq.com","card":{"config":{"wide_screen_mode":true,"enable_forward":true},"elements":[{"tag":"div","text":{"content":"**[Graylog3告警信息](.check_result.Event.Source)**\r\n\r\n告警索引：graylog_0\r\n开始时间：2022-05-10 09:54:00\r\n告警主机：10.167.169.94:\u003cno value\u003e\r\n**2022-05-10 01:54:00.170 ERROR 1 --- [   scheduling-1] .b.f.m.j.FluentdMultilineJavaApplication : 业务异常\n\norg.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'test' available\n\n\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:816) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1288) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat com.arnoldgalovics.blog.fluentd.multiline.java.FluentdMultilineJavaApplication.logException(FluentdMultilineJavaApplication.java:40) ~[classes!/:na]\n\n\tat jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[na:na]\n\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]\n\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]\n\n\tat org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]\n\n\tat java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]\n\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]\n\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]\n\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]\n\n\tat java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]\n2022-05-10 01:54:00.171 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task\n\njava.lang.RuntimeException: Error happened\n\n\tat com.arnoldgalovics.blog.fluentd.multiline.java.FluentdMultilineJavaApplication.logException(FluentdMultilineJavaApplication.java:43) ~[classes!/:na]\n\n\tat jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[na:na]\n\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]\n\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]\n\n\tat org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]\n\n\tat java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]\n\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]\n\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]\n\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]\n\n\tat java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]\n\nCaused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'test' available\n\n\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:816) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1288) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]\n\n\tat com.arnoldgalovics.blog.fluentd.multiline.java.FluentdMultilineJavaApplication.logException(FluentdMultilineJavaApplication.java:40) ~[classes!/:na]\n\n\t... 11 common frames omitted**\r\n","tag":"lark_md"},"content":"","elements":null},{"tag":"hr","text":{"content":"","tag":""},"content":"","elements":null},{"tag":"note","text":{"content":"","tag":""},"content":"","elements":[{"tag":"lark_md","text":{"content":"","tag":""},"content":"PrometheusAlert告警消息","elements":null}]}],"header":{"title":{"content":"PrometheusAlert告警消息","tag":"plain_text"},"template":"red"}}}

# 程序报错日志
[feishuv2] PrometheusAlert告警消息: {"code":11246,"data":{},"msg":"path: message-\u003ecard-\u003e1th block(div)-\u003eelement(text)-\u003e7th md(code); err_msg: unsupported type of html tag; err_type: validation; "}

提示，飞书提示不支持的type

# 模板配置：

**[日志告警信息](.check_result.Event.Source)**
{{ range $k,$v:=.backlog }}
告警索引：{{$v.index}}
开始时间：{{GetCSTtime $v.timestamp}}
告警主机：{{$v.fields.gl2_remote_ip}}:{{$v.fields.gl_2_remote_port}}
**{{$v.message}}**
{{end}}

**Comment by alangong114** [comment]
测试版本4.8 也有该问题

**Comment by feiyu563** [comment]
可以参考自定义模板的说明文档改下模板的适配就行了

**Comment by xunaidong** [comment]
分享个简易的graylog4的钉钉，需要的字段可以自己配置event的时候自己添加


## 测试xxx系统{{.event_definition_description}}
###### 日志级别：{{.event.fields.level_name}}
###### 开始时间：{{.event.timestamp}}
###### 结束时间：{{.event.timestamp_processing}}
###### 告警应用：{{.event.fields.app_name}}:{{.event.fields.ip}}
###### {{.event.fields.message}}
