### ISSUE TITLE
时区问题：自定义模板为什么是UTC时区

### ISSUE THREAD

**Issue by wanghui122725501** [feiyu563/PrometheusAlert#220]
我这边升v4.8版本，新建模板的时区是UTC时区，导致告警消息差八小时。app.conf下的prometheus_cst_time=1 我也配置了，但是还不能解决问题，我将操作系统和使用的MySQL都调成北京时间了。但是还是不生效哦。麻烦帮忙解决下

**Comment by ambition0222** [comment]
+1

**Comment by Linuxstyle** [comment]
+1
