### ISSUE TITLE
页面访问时间较长

### ISSUE THREAD

**Issue by lihai521** [feiyu563/PrometheusAlert#223]
![image](https://user-images.githubusercontent.com/64959022/170225843-f15023c4-f297-4c56-9a3a-9ed69d824ccc.png)
环境为部署的本地虚拟机，内存、cpu都是正常的，其他的服务访问也很快，但是我部署安装了promethuesalert以后，访问页面点击一个菜单，会转十秒左右，才进入到页面。这是会由什么原因造成的呢？

**Comment by cdryzun** [comment]
调用到国外的链接了，导致很慢，实测版本 `v4.8.1` 存在此问题
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/45552084/174516763-5980515c-f68d-4161-8f53-94e26d73e53b.png">

**Comment by lihai521** [comment]
> 调用到国外的链接了，导致很慢，实测版本 `v4.8.1` 存在此问题 <img alt="image" width="1505" src="https://user-images.githubusercontent.com/45552084/174516763-5980515c-f68d-4161-8f53-94e26d73e53b.png">
> 
> The call to the foreign link, resulting in very slow, live version V4.8.1 exists this problem
感谢。查看本地是这个原因。
![image](https://user-images.githubusercontent.com/64959022/174518585-9705e495-4f01-489e-a64b-c1e1647cf3ce.png)

**Comment by cdryzun** [comment]
1. https://github.com/feiyu563/PrometheusAlert/pull/230

**Comment by cdryzun** [comment]
@lihai521 可以先暂时使用我这个镜像进行缓解 `yangzun/prometheus-alert:v4.8.1`

**Comment by lihai521** [comment]
好哒。谢谢啦-------- 原始邮件 --------发件人： cdryzun ***@***.***>日期： 2022年6月20日周一 11:48收件人： feiyu563/PrometheusAlert ***@***.***>抄送： IDE ***@***.***>, Mention ***@***.***>主    题： Re: [feiyu563/PrometheusAlert] 页面访问时间较长 (Issue #223)

@lihai521 可以先暂时使用我这个镜像进行缓解 yangzun/prometheus-alert:v4.8.1
