### ISSUE TITLE
在prometheusAlert中无法达到分组告警

### ISSUE THREAD

**Issue by evirts** [feiyu563/PrometheusAlert#224]
1、在没有使用prometheusAlert之前，单独使用邮件告警，是可以达到分组告警的，配置文件和效果图如下
配置文件如下
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitor
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.163.com:465'
      smtp_from: 'xx@163.com'
      smtp_auth_username: 'xx@163.com'
      smtp_auth_password: 'xxx'
      smtp_require_tls: false
    route:
      group_by: ['alertname']
      group_wait: 2m
      group_interval: 10s
      repeat_interval: 2m
      receiver: 'web.hook.prometheusalert'
    receivers:
    - name: 'web.hook.prometheusalert'
      email_configs:
      - to: 'prom_test@163.com'
 效果图如下：
![0527](https://user-images.githubusercontent.com/10336478/170611047-3c58d3c8-42e1-43dc-a88d-89b58909fb8b.png)

二、使用prometheusAlert之后，通过钉钉告警，无法达到分组告警
配置文件如下：
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitor
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 60s
      group_interval: 20s
      repeat_interval: 10m
      receiver: 'web.hook.prometheusalert'
    receivers:
    - name: 'web.hook.prometheusalert'
      webhook_configs:
      - url: 'http://192.192.32.97:8080/prometheusalert?type=dd&tpl=prometheus-dd&ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxx'

效果图如下：
![0527-1](https://user-images.githubusercontent.com/10336478/170611394-4d6917ab-c22a-42e3-a512-46117b5a7b35.png)

并没有达到邮件告警中的分组 效果，需要改哪里配置嘛

**Comment by easonboy** [comment]
同问，需要大佬解答一波！！

**Comment by feiyu563** [comment]
url参数新增 split=true，该参数仅针对Prometheus告警消息有效，作用是将Prometheus分组消息拆分成单条发送。默认开启，如果Prometheus一次告警附带的同分组的告警消息条数过多，可能会导致告警消息体过大。如需关闭请在url中加入split=false
