### ISSUE TITLE
自定义模板无法发送消息

### ISSUE THREAD

**Issue by SirBlues** [feiyu563/PrometheusAlert#227]
我用github上Issues推荐的模板，用飞书机器人来做消息发送，发现发不出消息，只能用默认的模板才能办发送，而且默认模板不好看，只要涉及百分比，小数点就一大堆，用容器做，已经做了时间同步，但是告警显示的时间不对，相差8小时，替换模板不生效

**Comment by feiyu563** [comment]
你的问题在文档里面都有写，可以仔细看下文档
