### ISSUE TITLE
告警是否支持了收敛功能？

### ISSUE THREAD

**Issue by junly917** [feiyu563/PrometheusAlert#23]
zabbix、grafana的报警信息转发过来之后，是否可以将告警信息进行收敛？
是否有此功能，如果没有会不会计划增加此功能？

**Comment by feiyu563** [comment]
目前正在计划做方面，需要点时间



---原始邮件---
发件人: "Junly"<notifications@github.com&gt;
发送时间: 2020年4月29日(周三) 上午10:53
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 告警是否支持了收敛功能？ (#23)




 
zabbix、grafana的报警信息转发过来之后，是否可以将告警信息进行收敛？
 是否有此功能，如果没有会不会计划增加此功能？

**Comment by junly917** [comment]
你们有什么具体的方案吗? 目前我在准备做了
参考了网上的方案, 都是将所有的报警推送到redis这类的消息中间件里面去. 之后再做分析报警
不知道你们有什么方案.

**Comment by feiyu563** [comment]
暂时还没有很好的待选方案，主要的问题在于现在接收的信息大多不统一，比如zabbix的目前就是纯文本，给消息过滤和分组带来不小的麻烦

**Comment by Zhang21** [comment]
AlertManger自带了告警收敛，完全可以在上游Alertmanager里实现。我就是在那里做的。
