### ISSUE TITLE
Dashboard从哪进

### ISSUE THREAD

**Issue by ZQiannnn** [feiyu563/PrometheusAlert#231]
为什么windows包跟docker界面不一样？

**Comment by Zhang21** [comment]
那就是两者的前端代码不一致，看下是不是docker tag的commit不一致。

**Comment by feiyu563** [comment]
使用相同版本号的PrometheusAlert，界面都是一套代码，docker版本的镜像tag尽量使用对应版本号的，首次使用可以选择latest。
