### ISSUE TITLE
是否考虑支持一下arm架构

### ISSUE THREAD

**Issue by ssx1235690** [feiyu563/PrometheusAlert#232]
看到https://hub.docker.com/r/feiyu563/prometheus-alert/tags。目前还不支持arm 架构。但是目前有主流使用arm主机的公司存在，是否考虑提供一下arm架构的镜像，

**Comment by Zhang21** [comment]
默认是在x86_64机器上打的包，所以你无法直接使用。

你可以看源码里的`goreleaser.yml`，里面定义了arm架构的打包方式。

你可以在arm架构的机器上，下载源码手动打包(`make`)，或使用`goreleaser`来打包。

**Comment by Zhang21** [comment]
docker buildx也支持多平台构建方式:

```bash
# 示例
docker buildx build --platform linux/arm64,linux/amd64 -t user/test:latest --push .
```

**Comment by lusson-luo** [comment]
既然如此，发版时以后可以加上 arm 版本的二进制吗
