### ISSUE TITLE
重启pod自定义模板丢失问题。

### ISSUE THREAD

**Issue by wangshaojun11** [feiyu563/PrometheusAlert#233]
已解决

**Comment by wangshaojun11** [comment]
自己创建了表，将数据存进来了。
<img width="996" alt="image" src="https://user-images.githubusercontent.com/33712490/175919614-42c93a78-b9ba-40d1-997b-9f15743067f3.png">

修改configmap的配置，重启服务之后，已经加载到pod里面。
db_driver=sqlite3
db_host=prometheusalert-mysql
db_port=3306
db_user=root
db_password=xxxx
db_name=prometheusalert


感觉并没有读mysql的配置，
dashboard上删除自定义的模板，重启还是会出现；
修改mysql中的字段，并不会同步到dashboard上。

**Comment by wangshaojun11** [comment]
已解决

**Comment by bangbangzheng** [comment]
我也遇到这个问题了，怎么解决的？

**Comment by bangbangzheng** [comment]
已经找到了，数据库文件 db/PrometheusAlertDB.db做持久化配置

**Comment by kubehan** [comment]
> 已经找到了，数据库文件 db/PrometheusAlertDB.db做持久化配置

我遇到了，数据不是存到数据库的吗？为什么还需要 db/PrometheusAlertDB.db做持久化配置
