### ISSUE TITLE
飞书告警是否支持合并

### ISSUE THREAD

**Issue by shunyong** [feiyu563/PrometheusAlert#236]
例如：多个命名空间的告警合并成一个消息呢？

**Comment by feiyu563** [comment]
参考： url参数新增 split=true，该参数仅针对Prometheus告警消息有效，作用是将Prometheus分组消息拆分成单条发送。默认开启，如果Prometheus一次告警附带的同分组的告警消息条数过多，可能会导致告警消息体过大。如需关闭请在url中加入split=false

**Comment by yuhonglei666** [comment]
![image](https://github.com/feiyu563/PrometheusAlert/assets/94445273/f42fd4e4-48d3-4d4e-8da0-be29719ccaf3)

**Comment by njqaaa** [comment]
问题：split=false后，的确可以实现告警的合并。 但同时，告警路由就失效了？
例如 alertmanager以自定义label（team&product）进行聚合，当多台服务器同时告警后，通过split=false进行了告警合并。
但此前配置的”告警路由“，全部失效了？

**Comment by njqaaa** [comment]
”告警路由“，有计划对commonLabels进行支持吗？
