### ISSUE TITLE
graylog日志模版无法提起json字段

### ISSUE THREAD

**Issue by sichenhao** [feiyu563/PrometheusAlert#237]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/67303469/182536004-9970bc25-b59a-46ca-97e0-3d3be9a79e8c.png">

**Comment by Peterzhangnoise** [comment]
同样遇到了此问题，不知道这个提取器是按什么规则走的

**Comment by feiyu563** [comment]
用这种 {{.event_definition_description}}
