### ISSUE TITLE
PrometheusAlert密码问题

### ISSUE THREAD

**Issue by fency12** [feiyu563/PrometheusAlert#239]
**想问个问题，alertmanager是直接将告警消息发送到PrometheusAlert的地址并带上模板等参数的，请问alertmanager到PrometheusAlert是怎么认证的？
没有看到哪里有配置认证的地方啊？还是说PrometheusAlert默认的密码不能修改？大家都没碰到这个问题吗？我修改了PrometheusAlert的默认密码，因为我想对外访问，但是alertmanagere指定url重加载报错**

**Comment by feiyu563** [comment]
web页面的密码跟接口无关，可以任意更改配置文件的密码，你的问题需要贴出详细的配置信息来

**Comment by fency12** [comment]
收到。可行
