### ISSUE TITLE
发送钉钉消息的内容如何显示全？

### ISSUE THREAD

**Issue by mengshuai85** [feiyu563/PrometheusAlert#24]
在向钉钉发送消息时，比如发送磁盘使用率过大的消息，不能显示告警详细信息
磁盘是D盘等（volume=“D”）

**Comment by mengshuai85** [comment]
自己傻了，直接在 description 那里写
"{{ $labels.instance }} {{ $labels.volume}}  磁盘占用过高"

**Comment by feiyu563** [comment]
好的，我刚准备告诉你这么做的
