### ISSUE TITLE
数据库无法使用mysql和pgsql

### ISSUE THREAD

**Issue by gzg870815** [feiyu563/PrometheusAlert#245]
mysql：
[ORM]2022/09/02 16:43:55 register db Ping `default`, dial tcp :0: connect: connection refused
panic: unknown DataBase alias name default
goroutine 1 [running]:
github.com/astaxie/beego/orm.getDbAlias(0xf62681, 0x7, 0xc00011e270)
	/go/src/github.com/feiyu563/PrometheusAlert/vendor/github.com/astaxie/beego/orm/db_utils.go:28 +0xf1
github.com/astaxie/beego/orm.SetMaxIdleConns(0xf62681, 0x7, 0xa)
	/go/src/github.com/feiyu563/PrometheusAlert/vendor/github.com/astaxie/beego/orm/db_alias.go:395 +0x35
main.init.0()
	/go/src/github.com/feiyu563/PrometheusAlert/main.go:52 +0x5be

 
pgsql：
[ORM]2022/09/02 16:46:17 register db Ping `default`, dial tcp: address tcp/sslmode=disable: unknown port
panic: unknown DataBase alias name default
goroutine 1 [running]:
github.com/astaxie/beego/orm.getDbAlias(0xf62681, 0x7, 0xc00028e630)
	/go/src/github.com/feiyu563/PrometheusAlert/vendor/github.com/astaxie/beego/orm/db_utils.go:28 +0xf1
github.com/astaxie/beego/orm.SetMaxIdleConns(0xf62681, 0x7, 0xa)
	/go/src/github.com/feiyu563/PrometheusAlert/vendor/github.com/astaxie/beego/orm/db_alias.go:395 +0x35
main.init.0()
	/go/src/github.com/feiyu563/PrometheusAlert/main.go:58 +0xa9a

两个库都可以正常连接 
环境变量指定了：
PA_DB_DRIVER
PA_DB_USER
PA_DB_PASSWORD
PA_DB_NAME
PA_DB_HOST
PA_DB_PORT
是有其它配置我没有注意到？

**Comment by feiyu563** [comment]
尝试直接配置到app.conf文件里面看下
