### ISSUE TITLE
使用Edge浏览器下载Release中的window.zip和linux.zip到Window10后提示病毒并自动删除。

### ISSUE THREAD

**Issue by chinapsu** [feiyu563/PrometheusAlert#246]
![image](https://user-images.githubusercontent.com/6300044/188401990-b33a0053-ab22-49cf-b7a9-11a25760254a.png)
![image](https://user-images.githubusercontent.com/6300044/188402254-09a74bc4-8343-4271-9b66-5e38f2aaefc4.png)
![image](https://user-images.githubusercontent.com/6300044/188402311-e7942049-d4ee-4937-813b-aac1ecd6c8f9.png)

**Comment by Spinestars** [comment]
之前一直是在linux上git clone，今天github死活clone不下来，就下载包，结果和你一样，edge 下载后直接报毒被清理

**Comment by Spinestars** [comment]
4.7没有报毒，4.8就不行了

**Comment by feiyu563** [comment]
应该是因为 PrometheusAlertVoice.exe 语音播报插件的问题，这个插件是用易语言写的，容易被误报，如果用不到的可以解压后删除
