### ISSUE TITLE
告警路由label 与或关系咨询

### ISSUE THREAD

**Issue by hichenxinyu** [feiyu563/PrometheusAlert#247]
请教下一条告警路由下，如果有多个label，是需要同时匹配多个label 才会路由是吗？
下意识以为是或关系，或者能不能提供个开关，一天路由规则下，匹配多个lable(或关系)

这个实用场景是，我们希望把一些label的告警都路由到指定的业务群里，如果是与关系的话，就要创建很多告警路由规则，或关系的话，在一个告警路由规则里维护lable就可以
![image](https://user-images.githubusercontent.com/17958216/188580439-29450621-803b-4a07-8901-ca519378981d.png)

**Comment by feiyu563** [comment]
所有label全部匹配上，路由才生效
