### ISSUE TITLE
华为云短信测试失败，麻烦帮忙看看。

### ISSUE THREAD

**Issue by zliangbj** [feiyu563/PrometheusAlert#249]
华为云短信模板内容：云服务器-通知信息运维告警：${TXT_66}  

prometheus告警内容： 
{"alertname":"nodeFilesystemUsage","class":"node","device":"/dev/vdb1","endpoint":"metrcis","fstype":"ext4","instance":"172.24.253.36:9100","job":"prometheus-huaweicloud-harbor","mountpoint":"/app","namespace":"devops-environment","prometheus":"devops-environment/k8s","service":"prometheus-harbor","severity":"critical"},"commonAnnotations":{"description":"172.24.253.36:9100当前磁盘/app 使用率70%"}

其中短信模板中发送了alertname、description和instance

返回错误信息：
2022/09/15 10:20:41.440 [I] [prometheusalert.go:480]  [1663208441392521102] [hwmessage] {"result":[{"originTo":"15273060073","createTime":"2022-09-15T02:20:41Z","from":"8822090932406","smsMsgId":"45d934fe-fc89-427a-922f-90c1a97af264_220858476","status":"E200028"}],"code":"E000510","description":"The SMS fails to be sent. For details, see status."}

查了一下E200028是说有特殊字符：不能出现.号，应该是：description和instance中包含了.号。
请问该如何解决。谢谢！

想了一下亦有可能是因为华为短信模板内容没和文档中：运维告警：${TXT_66} 完全保持一致造成的？ 请问华为云模板内容是否需要完全匹配： 运维告警：${TXT_66}  。 谢谢！

**Comment by brucejin** [comment]
现在华为云已经不能用 "运维告警：${TXT_66}"做签名了。
在什么都没有配置的情况下，默认的发送短信内容是什么？

**Comment by feiyu563** [comment]
默认的短信内容是模板中渲染之后的文本
