### ISSUE TITLE
配置了路由规则但是没有生效

### ISSUE THREAD

**Issue by orangeops** [feiyu563/PrometheusAlert#251]
2022/09/27 06:40:15.944 [D] [value.go:476]  [1664260815944165449] {"receiver":"prometheus","status":"resolved","alerts":[{"status":"resolved","labels":{"alert_host":"10.0.2.206","alertname":"ServerUseCpu2","eks_cluster":"platform-eks","hosttype":"ec2","instance":"10.0.2.206:9100","prometheus":"kubesphere-monitoring-system/k8s","severity":"Warning"},"annotations":{"description":"IP:10.0.2.206的CPU使用大于50% (当前值: 53)","summary":"10.0.2.206 CPU使用率过高"},"startsAt":"2022-09-27T06:34:45.928Z","endsAt":"2022-09-27T06:37:45.928Z","generatorURL":"http://prometheus-k8s-0:9090/graph?g0.expr=ceil%28100+-+sum+by%28instance%29+%28increase%28node_cpu_seconds_total%7Bjob%3D%22ec2-no-eks%22%2Cmode%3D%22idle%22%7D%5B5m%5D%29%29+%2F+sum+by%28instance%29+%28increase%28node_cpu_seconds_total%7Bjob%3D%22ec2-no-eks%22%7D%5B5m%5D%29%29+%2A+100%29+%3E+50\u0026g0.tab=1","fingerprint":"3036ba3951563c20"}],"groupLabels":{"alertname":"ServerUseCpu2"},"commonLabels":{"alert_host":"10.0.2.206","alertname":"ServerUseCpu2","eks_cluster":"platform-eks","hosttype":"ec2","instance":"10.0.2.206:9100","prometheus":"kubesphere-monitoring-system/k8s","severity":"Warning"},"commonAnnotations":{"description":"IP:10.0.2.206的CPU使用大于50% (当前值: 53)","summary":"10.0.2.206 CPU使用率过高"},"externalURL":"http://alertmanager-main-0:9093","version":"4","groupKey":"{}/{alerttype=~\"^(?:.*)$\"}:{alertname=\"ServerUseCpu2\"}","truncatedAlerts":0}

 2022/09/27 06:40:15.944 [I] [feishu.go:30]  [1664260815944165449] [feishuv2] {"msg_type":"interactive","email":"244217140@qq.com","card":{"config":{"wide_screen_mode":true,"enable_forward":true},"elements":[{"tag":"div","text":{"content":"**ServerUseCpu2** 🌤 resolved

🕒 **Start at**：      2022-09-27 14:34:45

🕓 **End at**：        2022-09-27 14:37:45

🏷️ **Alert Level**：Warning

☸  **主机**：       \u003cno value\u003e

☸  **命名空间**：    \u003cno value\u003e

☸  **pod名称**：    \u003cno value\u003e

☸  **触发告警持续时间**:  \u003cno value\u003e

☸  **告警类型**：    \u003cno value\u003e

☸  **告警内容**：    10.0.2.206 CPU使用率过高

📝 **Alert Detail**：

IP:10.0.2.206的CPU使用大于50% (当前值: 53)

\u003cno value\u003e

📈 [prometheusAlert](https://prometheusalert.platform.miotech.com/)

","tag":"lark_md"},"content":"","elements":null},{"tag":"hr","text":{"content":"","tag":""},"content":"","elements":null},{"tag":"note","text":{"content":"","tag":""},"content":"","elements":[{"tag":"lark_md","text":{"content":"","tag":""},"content":"PrometheusAlert告警消息","elements":null}]}],"header":{"title":{"content":"PrometheusAlert告警消息","tag":"plain_text"},"template":"green"}}}

例如我想让上面的告警发给Ec2host 但是发给了默认的prometheus，这个从那个地方改呢？ 或者为什么我写的规则没有生效
<img width="390" alt="image" src="https://user-images.githubusercontent.com/52404640/192468004-2b6bac54-94a2-4f80-95b5-648c4ebcb226.png">

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/52404640/192468409-bd6d860c-3e71-4ebd-abe0-8865582cd9d1.png">

谢谢大佬

**Comment by feiyu563** [comment]
这是alertmanager的问题，你可以百度或者在群里讨论下
