### ISSUE TITLE
自定义模板接口参数异常！

### ISSUE THREAD

**Issue by czhfe** [feiyu563/PrometheusAlert#256]
[E] [value.go:476]  [1665394381363887488] 自定义模板接口参数异常！

**Comment by feiyu563** [comment]
这是访问的Url缺少必要参数导致

**Comment by JosonQian** [comment]
2024/03/28 16:36:25.999 [D] [value.go:586]  [1711614985999165709] {"receiver":"webhook-ops","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"hostlive","group":"ops","instance":"172.31.41.198:29100","job":"comp","severity":"灾难","user":"prometheus"},"annotations":{"alertgroup":"ops","description":"172.31.41.198:29100 of job comp 无法连接","summary":"172.31.41.198:29100 无法连接"},"startsAt":"2024-03-28T08:35:55.989Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://eef3f3a28d29:9090/graph?g0.expr=up%7Binstance%21%3D%2210.203.32.35%3A29100%22%7D+%3D%3D+0\u0026g0.tab=1","fingerprint":"47a7cfceb0629af2"}],"groupLabels":{"job":"comp"},"commonLabels":{"alertname":"hostlive","group":"ops","instance":"172.31.41.198:29100","job":"comp","severity":"灾难","user":"prometheus"},"commonAnnotations":{"alertgroup":"ops","description":"172.31.41.198:29100 of job comp 无法连接","summary":"172.31.41.198:29100 无法连接"},"externalURL":"http://2d8d47c74f00:9093","version":"4","groupKey":"{}/{group=\"ops\"}:{job=\"comp\"}","truncatedAlerts":0}
2024/03/28 16:36:25.999 [E] [value.go:586]  [1711614985999165709] 自定义模板接口参数异常！

为什么一直提示这个告警内容，我想要的是钉钉这种的，不知道是哪里配置有问题，希望可以得到您的帮助。

2024/03/28 16:23:42.115 [I] [WebTest.go:18]  [1711614222114918429] [dingding] {"msgtype":"markdown","markdown":{"title":"PrometheusAlert","text":"## [PrometheusAlert](https://github.com/feiyu563/PrometheusAlert)\n\n#### 测试告警\n\n###### 告警级别：测试\n\n##### PrometheusAlert\n\n![PrometheusAlert](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/alert-center.png) @15888888888"},"at":{"atMobiles":["15888888888"],"isAtAll":false}}

**Comment by 7hanks** [comment]
> 这是访问的Url缺少必要参数导致

缺少什么参数
