### ISSUE TITLE
报警记录写入elasticsearch8.2.3报400

### ISSUE THREAD

**Issue by AEGEGE** [feiyu563/PrometheusAlert#259]
运行版本feiyu563/prometheus-alert:master
IMAGE ID:16ea89bd064d

2022/10/21 10:49:25.139 [E] [prometheusalert.go:379]  [elasticsearch] Index a prometheusalert alert to es error: elastic: Error 400 (Bad Request)
2022/10/21 10:49:25.154 [E] [prometheusalert.go:379]  [elasticsearch] Index a prometheusalert alert to es error: elastic: Error 400 (Bad Request)

**Comment by Zhang21** [comment]
es插件只适配了 es7。

```
github.com/olivere/elastic/v7 v7.0.32
```
