### ISSUE TITLE
飞书模版不能加html标签嘛？

### ISSUE THREAD

**Issue by HuaxingL** [feiyu563/PrometheusAlert#260]
我在飞书模版中添加了html的颜色标签，但是好像没有效果
![image](https://user-images.githubusercontent.com/111476113/197154434-7050b93a-3b8f-4cdc-adae-dc45b363c8f8.png)

**Comment by feiyu563** [comment]
参考文档中飞书那一节，飞书对于Markdown的支持是有限的
