### ISSUE TITLE
飞书报警恢复卡片颜色不是绿色问题

### ISSUE THREAD

**Issue by chzhuo** [feiyu563/PrometheusAlert#266]
现在飞书报警卡片的颜色是根据模板生成的报警消息里有没有 `resolved` 来判断的。而不是根据输入的 json 判断的。详见代码：
https://github.com/feiyu563/PrometheusAlert/blob/master/controllers/feishu.go#L125-L131

然而默认的 prometheus-fs 模板里，报警恢复里是不会出现 `resolved` 字样，导致消息恢复的样式也是红色的。

目前可用通过在 prometheus-fs 里增加 `resolved` 字样规避

**Comment by chzhuo** [comment]
我现在这么用：
```shell
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }} 状态：**{{$v.status}}** {{if eq $v.status "resolved"}}（恢复）{{else}}（报警）{{end}}
报警名字：**{{$v.labels.alertname}}**  [查看图表]({{$v.generatorURL}})
告警级别：{{$v.labels.severity}}
故障主机：{{$v.labels.instance}}
开始时间：{{TimeFormat $v.startsAt "2006-01-02 15:04:05"}}
结束时间：{{TimeFormat $v.endsAt "2006-01-02 15:04:05"}} 
报警概述：{{$v.annotations.summary}}
报警详情：{{$v.annotations.description}}
{{ end }}
{{ $urimsg:=""}}{{ range $key,$value:=.commonLabels }}{{$urimsg =  print $urimsg $key "%3D%22" $value "%22%2C" }}{{end}}[屏蔽该告警]({{$var}}/#/silences/new?filter=%7B{{SplitString $urimsg 0 -3}}%7D)
```

![image](https://user-images.githubusercontent.com/10919124/200727758-3620ade7-4278-4b67-b935-8fdd701e922c.png)

**Comment by putianhui** [comment]
大兄弟，我借鉴了你的屏蔽告警代码，为啥复制到我的模板里面测试会提示有问题
```bash
{{ $urimsg:=""}}{{ range $key,$value:=.commonLabels }}{{$urimsg =  print $urimsg $key "%3D%22" $value "%22%2C" }}{{end}}[屏蔽该告警]({{$var}}/#/silences/new?filter=%7B{{SplitString $urimsg 0 -3}}%7D)
```
<img width="875" alt="image" src="https://user-images.githubusercontent.com/68322685/218013511-74987452-e1fb-47e0-93b0-5e55ed32e2c1.png">

**Comment by feiyu563** [comment]
版本问题，用最新的版本才有对应的模板函数
