### ISSUE TITLE
prometheus-alert重启失败，提示"register db Ping `default`, disk I/O error: remote I/O error must have one register DataBase alias named `default`"

### ISSUE THREAD

**Issue by Pefeng** [feiyu563/PrometheusAlert#267]
2022/11/14 08:10:07.661 [I] [elasticsearch.go:63]  [elasticsearch] ES returned with code: 200 and version: 7.1.0
[ORM]2022/11/14 08:10:07 register db Ping `default`, disk I/O error: remote I/O error
must have one register DataBase alias named `default`

**Comment by feiyu563** [comment]
可以检查下是不是存储有问题，或者目前权限不可写
