### ISSUE TITLE
使用的相同的镜像 为什么看到的前端是不一样的？

### ISSUE THREAD

**Issue by MagicStarTrace** [feiyu563/PrometheusAlert#272]
![image](https://user-images.githubusercontent.com/15685376/202671395-09123993-9627-4544-b512-665e679ef853.png)
图一使用的镜像是:docker image feiyu563/prometheus-alert(d68864d68c3e)

![image](https://user-images.githubusercontent.com/15685376/202671535-62f9dc6e-7972-44ad-ad49-d11cc74d3b54.png)

图一的是什么情况？

**Comment by 117503445** [comment]
在 #280 合并之前，如果需要使用 Docker 部署最新代码，可以使用 117503445/prometheus-alert 镜像
