### ISSUE TITLE
Docker 镜像构建失败

### ISSUE THREAD

**Issue by 117503445** [feiyu563/PrometheusAlert#273]
## 问题描述

使用 `docker build .` 构建镜像失败了，报错为 

```
Step 17/21 : COPY logs logs
COPY failed: file not found in build context or excluded by .dockerignore: stat logs: file does not exist
```

`https://github.com/feiyu563/PrometheusAlert/actions/runs/3493710895` GitHub Action 也因为同样的原因失败了，这也导致镜像构建推送失败，用 Docker 运行时无法看到最新的功能，见 <https://github.com/feiyu563/PrometheusAlert/issues/272>

## 问题引入点

在 PR #268 中，删除了 `logs` 下的文件，导致 `logs` 文件夹不被 git 追踪了

## 解决方案

1. 修改 Dockerfile, 不复制 logs 文件夹了
2. 新建 `./logs/.gitkeep` 空文件，让 git 追踪 `logs` 文件夹

**Comment by jicki** [comment]
其实创建一个 logs 目录 就可以了

**Comment by 117503445** [comment]
> 其实创建一个 logs 目录 就可以了

这就是第二种做法

**Comment by 117503445** [comment]
在 #280 合并之前，如果需要使用 Docker 部署最新代码，可以使用 117503445/prometheus-alert 镜像

**Comment by 117503445** [comment]
#280 merged
