### ISSUE TITLE
如何使用curl测试webhook

### ISSUE THREAD

**Issue by itcuihao** [feiyu563/PrometheusAlert#277]
服务已经部署了，想先使用curl测试下消息，不过总是报
`自定义模板接口参数异常`
命令如下
` curl -XGET -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' http://0.0.0.0:23333/prometheusalert?type=fs&tpl=prometheus-fs`

**Comment by feiyu563** [comment]
用POST
