### ISSUE TITLE
关于针对不同主机钉不同的人

### ISSUE THREAD

**Issue by MagicStarTrace** [feiyu563/PrometheusAlert#278]
我计划针对不同的业务配置了不同的钉钉通知人

例：
XYZ的业务线，通知xyz的值班人/值班组
@xyz

ABC的业务线，通知abc的值班人/值班组
@abc

请问在PrometheusAlert 怎么样实现业务线的区分?

配置不同的自定义模版?

**Comment by feiyu563** [comment]
通过页面配置不同的路由规则即可
