### ISSUE TITLE
在Web页面修改模板不生效

### ISSUE THREAD

**Issue by Zhang21** [feiyu563/PrometheusAlert#28]
在模板管理修改微信模板(`p-weixin`)后不生效，重启也不生效。还是使用的初始的模板格式，请问是什么原因呢？

以下为修改的模板内容:

```
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }}
[Prometheus告警信息]($v.generatorURL}})
>规则名称: **[{{$v.labels.alertname}}]({{$var}})**
>告警级别: {{$v.labels.level}}
开始时间: {{$v.startsAt}}
结束时间: {{$v.endsAt}}
故障主机: {{$v.labels.instance}}
{{$v.annotations.summary}}
{{$v.annotations.description}}
{{end}}
```

添加了规则名称和`annotations.sumarry`。但告警内容还是初始的格式。

**Comment by feiyu563** [comment]
alertmanager里面使用的接口是自定义模版的页面提示接口URL地址吗，如果用Prometheus默认的接口
`/prometheus/alert` 和 `/prometheus/router` 是用的内置的模版，不是页面上的模版

**Comment by Zhang21** [comment]
@feiyu563 webhook修改为prometheusAlert:8080

```
 10 receivers:
 11 - name: 'web.hook.prometheusalert'
 12   webhook_configs:
 13       - url: 'http://127.0.0.1:8080/prometheus/alert'
```

文档中只看到修改这个webhook地址，请问是还需要修改其它地址吗？

**Comment by Zhang21** [comment]
以下为通知出来的模板格式，就是默认的p-weixin模板格式。

![image](https://user-images.githubusercontent.com/18358275/84354977-6ac6ba00-abf4-11ea-8bce-22d91a6fe707.png)

**Comment by feiyu563** [comment]
https://feiyu563.gitbook.io/prometheusalert/prometheusalert-gao-ji-zi-ding-yi-xiao-xi-mo-ban  自定义模板的参考这个
