### ISSUE TITLE
mysql作为后端数据存储，导入sql，dashboard的模版是乱码的

### ISSUE THREAD

**Issue by Tab-ops** [feiyu563/PrometheusAlert#283]
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/53932327/215709631-6b4803a0-3716-48b3-96be-1d4cbc66abdf.png">

**Comment by feiyu563** [comment]
数据库编码选择UTF8的

**Comment by dxg0716** [comment]
mysql 8.4 版本，创建数据库CREATE DATABASE prometheusalert CHARACTER SET utf8 COLLATE utf8_general_ci; 自定义模版还是乱码，是不能使用8.4版吗

<img width="1540" height="991" alt="Image" src="https://github.com/user-attachments/assets/ec9d7e30-1c69-422e-8a5c-420f37d0d41c" />
