### ISSUE TITLE
有没有grafana发送给飞书的告警模板？

### ISSUE THREAD

**Issue by fency12** [feiyu563/PrometheusAlert#284]
默认的garfana发送飞书的模板不好用，时间也不对，求一个优秀的模板

**Comment by only21tender** [comment]
要等prometheusalter的dashboard上配置告警模板，我也正在尝试中

**Comment by fency12** [comment]
prometheusalter的dashboard上已经有了grafana的告警模板，不过不好用很简单，时间也不对。

**Comment by putianhui** [comment]
我这[有个文档](https://www.putianhui.cn/posts/401076f6f029/#%E9%85%8D%E7%BD%AEprometheusAlert%E4%B8%8AGrafana%E6%97%A5%E5%BF%97%E5%91%8A%E8%AD%A6%E6%A8%A1%E6%9D%BF)  里面有Grafana对接飞书的告警模板

<img width="374" alt="image" src="https://user-images.githubusercontent.com/68322685/217988674-76652171-e3be-4207-bd82-ec0c3b996e58.png">

**Comment by feiyu563** [comment]
Grafana本身可取的参数并不多，这点可以从Grafana原始的json中提取需要的参数展示

**Comment by mifashion** [comment]
> 我这[有个文档](https://www.putianhui.cn/posts/401076f6f029/#%E9%85%8D%E7%BD%AEprometheusAlert%E4%B8%8AGrafana%E6%97%A5%E5%BF%97%E5%91%8A%E8%AD%A6%E6%A8%A1%E6%9D%BF) 里面有Grafana对接飞书的告警模板
> 
> <img alt="image" width="374" src="https://user-images.githubusercontent.com/68322685/217988674-76652171-e3be-4207-bd82-ec0c3b996e58.png">

你这里有些的配置我这边获取不到
