### ISSUE TITLE
模板和告警管理页面的打开加载的fonts能否优化下，经常访问不了

### ISSUE THREAD

**Issue by cdy668** [feiyu563/PrometheusAlert#285]
地址如下：
https://fonts.gstatic.font.im/s/sourcesanspro/v14/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdr3cOWxw.ttf
https://fonts.gstatic.font.im/s/sourcesanspro/v14/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7gujVj9w.ttf
https://fonts.gstatic.font.im/s/sourcesanspro/v14/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwlxdr3cOWxw.ttf

**Comment by einsli** [comment]
我也遇到了同样的问题，也是打不开

**Comment by feiyu563** [comment]
新的版本会优化这块，代码已经提交，有需要的可以自己编译下，或者替换下 views目录下的main.html和login.html即可
