### ISSUE TITLE
同一个告警发送好几次

### ISSUE THREAD

**Issue by Leif160519** [feiyu563/PrometheusAlert#288]
同一个告警，飞书收到好几遍
![image](https://user-images.githubusercontent.com/19452903/222420735-79f1542d-c14c-4a2b-903a-edbbabecc7d6.png)
查看prometheusalert的日志也是打印很多次
![image](https://user-images.githubusercontent.com/19452903/222419826-96f61e4c-2165-4867-9ee3-f86a64a53f01.png)
经常遇到，一直没能解决，希望能给点思路

**Comment by Leif160519** [comment]
有的时候告警发一遍，大部分的时候发两遍

**Comment by feiyu563** [comment]
通常存在几种可能

**Comment by feiyu563** [comment]
通常存在几种可能

**Comment by feiyu563** [comment]
通常存在几种可能
1.alertmanager路由重复发送
2.本身alertmanager发来的聚合消息中就包含了多条重复告警

**Comment by Leif160519** [comment]
目前是这样的情况：
1.alertmanager里显示的告警有一条

**Comment by Leif160519** [comment]
这几天貌似正常了，先关闭了

**Comment by wanglongsxr** [comment]
我今天也出现了同一个告警发出了多次（飞书），而且我确认每个告警我没有重复发送...

**Comment by kof8855** [comment]
假如有一台服务器离线了，需要一个月后才能处理，这期间Prometheus一直产生告警发送到PrometheusAlert，我如何在PrometheusAlert中进行抑制？

**Comment by Leif160519** [comment]
> 假如有一台服务器离线了，需要一个月后才能处理，这期间Prometheus一直产生告警发送到PrometheusAlert，我如何在PrometheusAlert中进行抑制？

直接在alertmanager里屏蔽告警，时间设置30天即可
