### ISSUE TITLE
自定义模板prometheus_cst_time设置不生效

### ISSUE THREAD

**Issue by liuhuan5415** [feiyu563/PrometheusAlert#29]
#转换Prometheus告警消息的时区为CST时区(如默认已经是CST时区，请勿开启)
prometheus_cst_time=1
开启后不生效

**Comment by feiyu563** [comment]
自定义模板将在下一版本中开始支持，敬请关注

**Comment by feiyu563** [comment]
新版本已经集成模板参数，可参照页面的默认模板
