### ISSUE TITLE
飞书发送的恢复消息为什么title是告警消息？

### ISSUE THREAD

**Issue by leon96** [feiyu563/PrometheusAlert#293]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/4475129/223695077-e1df25fc-348e-4302-9a3b-de434079b65e.png">
为什么飞书恢复消息的title是告警消息？
我看代码也没看明白，title是"PrometheusAlert",  Titleend是"故障恢复信息"，为什么会发出”PrometheusAlert告警消息“？

**Comment by jicki** [comment]
使用新版本测试一下.

**Comment by jicki** [comment]
恩，这个 标题，可以在 app.conf 里面的 title 里设置成你想要的。
