### ISSUE TITLE
使用promtehtusalert 4.8 版本出现的问题

### ISSUE THREAD

**Issue by Heyz6** [feiyu563/PrometheusAlert#295]
当前我有一测试接口；未使用 promethesalert 的场景下，只使用 alertmanager 告警；
    - name: mail-receiver
      webhook_configs:
      - url: 'http://192.168.0.10/alerttest/'
        send_resolved: true
alertmanager-secret.yaml如上配置，该测试接口 可以获取到告警信息

可是当我使用 prometheusalert 后；请问我如何配置prometheusalert.yaml 以及 alertmanager-secret.yaml【当前环境中我使用了 open-dingding=1 告警无异常，钉钉可接收】；

**Comment by feiyu563** [comment]
接口是固定的，你写的Url中的接口（url: 'http://192.168.0.10/alerttest/'）不存在，所以无法触发
