### ISSUE TITLE
为什么飞书收到的报警会被自动添加换行符

### ISSUE THREAD

**Issue by qianghong000** [feiyu563/PrometheusAlert#300]
![image](https://user-images.githubusercontent.com/9443696/230882530-02ebc1a1-856f-4cbe-90a6-7171a8e5a0ec.png)

模版内容如下：
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }}
##### {{$v.annotations.description}}
![Prometheus](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/alert-center.png)
{{ end }}

**Comment by lishuailingx** [comment]
模板这样就不会有换行了


{{ range $k,$v:=.alerts }}{{if eq $v.status "resolved"}}**[Prometheus恢复信息]**
告警名称：[{{$v.labels.alertname}}]
告警级别：{{$v.labels.severity}}
{{$v.annotations.address}}
{{$v.annotations.summary}}
**{{$v.annotations.description}}**
⏱ : {{TimeFormat $v.startsAt "2006-01-02 15:04:05"}}
⏲ : {{TimeFormat $v.endsAt "2006-01-02 15:04:05"}} 
{{else}}**[Prometheus告警信息]**
告警名称：[{{$v.labels.alertname}}]
告警级别：{{$v.labels.severity}}
{{$v.annotations.address}}
{{$v.annotations.summary}}
**{{$v.annotations.description}}**
⏱ : {{TimeFormat $v.startsAt "2006-01-02 15:04:05"}}
{{end}}
{{ end }}

![image](https://github.com/feiyu563/PrometheusAlert/assets/39297449/8383734f-841b-4952-ae5e-436a98c6bf6a)
