### ISSUE TITLE
zabbix推送消息到飞书报错

### ISSUE THREAD

**Issue by lingming100** [feiyu563/PrometheusAlert#301]
大佬帮忙看看这个如何解决，谢谢
{"code":11246,"data":{},"msg":"path: message-\u003ecard-\u003e1th block(div)-\u003eelement(text)-\u003e2th md(code); err_msg: unsupported type of html tag; err_type: validation; "}

**Comment by feiyu563** [comment]
unsupported type of html tag  zabbix中的Message配置有html的标记，需要去掉才能行
