### ISSUE TITLE
阿里云短信模版配置

### ISSUE THREAD

**Issue by machfang** [feiyu563/PrometheusAlert#31]
你好，我在页面测试阿里云短信发送时提示，params over length limit is 20，模版按照“prometheus告警:${code}”配置，请问应该如何修改

**Comment by feiyu563** [comment]
需要联系下阿里云的客服，调整下短信参数的长度限制

**Comment by machfang** [comment]
模版中的变量code(PrometheusAlertCenter测试告警)不符合[其他号码（如订单号、密码等）]的变量规范!
这是变量属性选错了吗？

**Comment by feiyu563** [comment]
模板类型选择短信通知，变量属性选其他
参考阿里云的规范：https://help.aliyun.com/document_detail/108253.html?spm=a2c4g.11186623.2.42.368f15ecB6iSHt

**Comment by feiyu563** [comment]
你选的应该是，所以提示不符合规范
![image](https://user-images.githubusercontent.com/25146052/84891238-26dd2480-b0ce-11ea-91b9-cc992b139f9c.png)

**Comment by machfang** [comment]
已经调试成功了，谢谢
