### ISSUE TITLE
为什么接入MySQL Table 'prometheusalert.prometheus_alert_d_b' doesn't exist

### ISSUE THREAD

**Issue by bruce202303** [feiyu563/PrometheusAlert#317]
![image](https://github.com/feiyu563/PrometheusAlert/assets/127083946/ac3dc360-d8c5-476c-bf34-31c842f7c62a)
这里只有insert语句,原始库表结构的SQL;语句没有

**Comment by bruce202303** [comment]
![image](https://github.com/feiyu563/PrometheusAlert/assets/127083946/a3a1ab2c-8fd5-45b7-9794-b649735fc765)

**Comment by feiyu563** [comment]
https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/base-install.md#%E9%85%8D%E7%BD%AEprometheusalert%E4%BD%BF%E7%94%A8mysql%E4%BD%9C%E4%B8%BA%E5%90%8E%E7%AB%AF%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8

按照顺序操作 创建数据库--> 改配置文件--> 启动PrometheusAlert
