### ISSUE TITLE
dingding {"errcode":460101,"errmsg":"description: body 大小不合法;solution:请保持大小在 20000bytes 以内;"}

### ISSUE THREAD

**Issue by davidshanghai** [feiyu563/PrometheusAlert#318]
dingding 的 body 有大小限制， 能否在代码里控制或者分拆一下。

**Comment by feiyu563** [comment]
https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/system-var.md

4.url参数新增 split=true，该参数仅针对Prometheus告警消息有效，作用是将Prometheus分组消息拆分成单条发送。默认开启，如果Prometheus一次告警附带的同分组的告警消息条数过多，可能会导致告警消息体过大。如需关闭请在url中加入split=false
