### ISSUE TITLE
支持按照具体消息发送到单个或多个接收方

### ISSUE THREAD

**Issue by Zhang21** [feiyu563/PrometheusAlert#32]
你好，请问支持按照具体消息发送到单个或多个接收方的配置文档在哪？我没有看到。例如将告警信息发送到多个微信机器人，如何配置？

谢谢！

**Comment by feiyu563** [comment]
prometheus参考：https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/prometheus.md

**Comment by Zhang21** [comment]
按照文档里面的配置，它还是使用的`app.conf`里面默认的webhook发送。

还有一个问题就是使用默认模板里面的主机IP(instance)发送出来没有内容。

![image](https://user-images.githubusercontent.com/18358275/84983770-095e9800-b16c-11ea-8863-dba89811fe35.png)

![image](https://user-images.githubusercontent.com/18358275/84983816-21ceb280-b16c-11ea-8d2a-62ed5a650f96.png)

**Comment by feiyu563** [comment]
你把你现在的alertmanager的配置贴我看下



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年6月18日(周四) 下午2:05
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 支持按照具体消息发送到单个或多个接收方 (#32)




 
按照文档里面的配置，它还是使用的app.conf里面默认的webhook发送。
 
还有一个问题就是使用默认模板里面的主机IP(instance)发送出来没有内容。

**Comment by Zhang21** [comment]
@feiyu563 

![image](https://user-images.githubusercontent.com/18358275/84988672-fb614500-b174-11ea-9cba-41cae534ef00.png)

在规则里配置多个webhook也不生效。

**Comment by feiyu563** [comment]
把PrometheusAlert日志也贴一下，你改完这些rules之后有重新reload prometheus？

**Comment by Zhang21** [comment]
我reload(`curl -xPOST`)了prometheus。
我看了日志，wxurl值是传过来了的，但是PrometheusAlert发送看不到使用的那个webhook，是要改成debug模式吗？

**Comment by feiyu563** [comment]
没有debug模式，默认就是输出所有log。

**Comment by Zhang21** [comment]
哦！反正就是在规则里填写wxurl不生效，模板渲染(markdown)结果有时候会缺少数据。

请问，这是bug还是我配置有问题？

**Comment by feiyu563** [comment]
你配置的接口是默认接口，不是自定义模版接口

**Comment by feiyu563** [comment]
自定义模版接口是`/prometheusalert?type=${type}&tpl=${template}&[ddurl=${ddur}][wxurl=${wxurl}][fsurl=${fsurl}][phone=${phonenumber}]`

**Comment by Zhang21** [comment]
不是，我之前测试自定义模板有点问题，所以我就修改我的rules来适配默认的wx模板。

**Comment by feiyu563** [comment]
你把你日志里面的prometheus的json发我，我测试下

**Comment by feiyu563** [comment]
我自己测试了下，配置多个微信没有问题

**Comment by Zhang21** [comment]
我现在的问题是会缺失数据，好像是PrometheusAlert拿到的数据不完整。

刚刚看日志，为啥有些包含`instance`，有些没有`instance`，所以导致渲染出来的模板数据缺失。

缺失`instance`:

```json
2020/06/18 16:00:59.557 ^[[1;34m[I]^[[0m [value.go:460]  [1592467259557865061] {"receiver":"web\\.hook\\.prometheusalert","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"process-exporte进程不存在","level":"3","severity":"critical"},"annotations":{"description":"process-exporte进程不存在: ","summary":"process-exporte进程不存在: ","wxurl":"https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxx"},"startsAt":"2020-06-18T07:55:39.540051999Z","endsAt":"2020-06-18T08:00:54.540051999Z","generatorURL":"http://sa-Prometheus:9090/graph?g0.expr=sum%28namedprocess_namegroup_states%7Bgroupname%3D%22process-exporte%22Chostname%3D%22sa-Prometheus%2%29+%3D%3D+0\u0026g0.tab=1","fingerprint":"2edc55e3fc26bf16"}],"groupLabels":{"alertname":"process-exporte进程不存在"},"commonLabels":{"alertname":"process-exporte进程不存在","level":"3","severity":"critical"},"commonAnnotations":{"description":"process-exporte进程不存在: ","summary":"process-exporte进程不存在: ","wxurl":"https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxx"},"externalURL":"http://sa-Prometheus.7moor.com:9093","version":"4","groupKey":"{}:{alertname=\"process-exporte进程不存在\"}"}
```

包含`instance`:

```json
2020/06/18 15:13:54.697 ^[[1;34m[I]^[[0m [value.go:460]  [1592464434697371952] {"receiver":"web\\.hook\\.prometheusalert","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"PrometheusTarget不可用","hostname":"sa-Prometheus","instance":"localhost:9256","job":"node-process-exporter","level":"3","severity":"critical"},"annotations":{"description":"Prometheus target sa-Prometheus可用性: 0","summary":"Prometheus target不可用: sa-Prometheus"},"startsAt":"2020-06-18T07:11:34.692512745Z","endsAt":"2020-06-18T07:13:49.692512745Z","generatorURL":"http://sa-Prometheus:9090/graph?g0.expr=up+%3D%3D+0\u0026g0.tab=1","fingerprint":"03115e007606038f"}],"groupLabels":{"alertname":"PrometheusTarget不可用"},"commonLabels":{"alertname":"PrometheusTarget不可用","hostname":"sa-Prometheus","instance":"localhost:9256","job":"node-process-exporter","level":"3","severity":"critical"},"commonAnnotations":{"description":"Prometheus target sa-Prometheus可用性: 0","summary":"Prometheus target不可用: sa-Prometheus"},"externalURL":"http://sa-Prometheus:9093","version":"4","groupKey":"{}:{alertname=\"PrometheusTarget不可用\"}"}
```

**Comment by feiyu563** [comment]
这是Prometheus告警消息本身就不是所有指标都包含instance字段

**Comment by Zhang21** [comment]
好，那我继续测试多个wx接收这个问题。

**Comment by Zhang21** [comment]
关于数据缺失那个问题，我知道原因了。

**Comment by Zhang21** [comment]
我的wxurl还是使用`app.conf`里面的默认项。哎！

![image](https://user-images.githubusercontent.com/18358275/85001650-80a12580-b186-11ea-94b7-821b2c17b3eb.png)

**Comment by feiyu563** [comment]
等明天，我远程你看下，或者你也可以试试最新版本的



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年6月18日(周四) 下午5:10
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 支持按照具体消息发送到单个或多个接收方 (#32)




 
我的wxurl还是使用app.conf里面的默认项。哎！

**Comment by Zhang21** [comment]
我拉一下新代码试试，谢谢你。
我是`linux`版本，运行的`example/linux/PrometheusAlert`。

**Comment by Zhang21** [comment]
@feiyu563 
作者你好，建议将`app.conf`配置文件写成`app.conf.example`，然后本地修改为`app.conf`，将其加入`.gitignore`，方便本地修改但不影响代码库，便于以后直接进行git操作而不会冲突。

**Comment by Zhang21** [comment]
之前是通过下载zip包，配置多个`wxurl`不可用；今天通过`git clone`，配置多个`wxurl`已可用。

**Comment by feiyu563** [comment]
好的，估计是打包的有问题



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年6月22日(周一) 上午10:52
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 支持按照具体消息发送到单个或多个接收方 (#32)




 
之前是通过下载zip包，配置多个wxurl不可用；今天通过git clone，配置多个wxurl已可用。
