### ISSUE TITLE
多实例部署时，内存中的自定义模版如何更新

### ISSUE THREAD

**Issue by JokerQueue** [feiyu563/PrometheusAlert#321]
多实例部署时，各实例内存中的自定义模版如何同步更新，目前看只会更新一个实例，其他实例需要重启重新加载吗。

**Comment by 912988434** [comment]
这种不要用内置的 sqlite 换 称外置的mysql呗

**Comment by JokerQueue** [comment]
> 这种不要用内置的 sqlite 换 称外置的mysql呗

用的是外置的mysql，是缓存不更新，重启才会去查mysql

**Comment by feiyu563** [comment]
打开自定义模板页面或者刷新下对应的实例的自定义模板页面就会刷新
