### ISSUE TITLE
graylog3的消息怎么路由

### ISSUE THREAD

**Issue by sherppard** [feiyu563/PrometheusAlert#33]
目前配置graylog3的webhook地址后，就是用 /graylog3/weixin 的接口，只会默认发给同一个模板。如果我定义了多个模板，就必须使用/prometheusalert的接口跟参数来配置，这样graylog3就有大量的通知器的配置。

**Comment by feiyu563** [comment]
目前确实这样



---原始邮件---
发件人: "WeiZe"<notifications@github.com&gt;
发送时间: 2020年6月18日(周四) 晚上6:20
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] graylog3的消息怎么路由 (#33)




 
目前配置graylog3的webhook地址后，就是用 /graylog3/weixin 的接口，只会默认发给同一个模板。如果我定义了多个模板，就必须使用/prometheusalert的接口跟参数来配置，这样graylog3就有大量的通知器的配置。

**Comment by sherppard** [comment]
好吧，还是感谢开源，这个消息转发平台确实不错，希望继续完善

**Comment by feiyu563** [comment]
等下一版本更新吧
