### ISSUE TITLE
企业微信可否根据不同场景 @到不同人员

### ISSUE THREAD

**Issue by suntianxian** [feiyu563/PrometheusAlert#34]
能否支持对邮件的支持

**Comment by feiyu563** [comment]
待新版本开始集成，已经在开发计划中



---原始邮件---
发件人: "suntianxian"<notifications@github.com&gt;
发送时间: 2020年6月22日(周一) 上午10:07
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 能否支持对邮件的支持 (#34)




 
能否支持对邮件的支持

**Comment by suntianxian** [comment]
企业微信可否根据不同场景 @到不同人员

**Comment by feiyu563** [comment]
后续会增加支持

**Comment by Zhang21** [comment]
@suntianxian  我上次看了企业微信机器人文档，企业微信markdown消息类型不支持@someone。
