### ISSUE TITLE
飞书V2告警中告警描述不显示

### ISSUE THREAD

**Issue by chinaboy007** [feiyu563/PrometheusAlert#346]
模板如下：
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }} 
{{if eq $v.status "resolved"}} 
**[测试环境Prometheus 恢复通知]({{$v.generatorURL}})**
【告警名称】{{$v.labels.alertname}}
【告警级别】{{ $v.labels.severity}}
【告警状态】{{$v.status}}✅
【开始时间】{{GetCSTtime $v.startsAt}}
【结束时间】{{GetCSTtime $v.endsAt}} 
【恢复实例】{{$v.labels.instance}}
【命名空间】 {{$v.labels.namespace}}
【POD名称】 {{$v.labels.pod}}
【告警主题】{{$v.annotations.summary}}
  **{{$v.annotations.description}}**
{{else}} 
**[测试环境Prometheus 报警通知]({{$v.generatorURL}})**
【告警名称】{{$v.labels.alertname}}
【告警级别】{{ $v.labels.severity}}
【告警状态】{{$v.status}}🔥
【开始时间】{{GetCSTtime $v.startsAt}}
【告警实例】{{$v.labels.instance}}
【命名空间】 {{$v.labels.namespace}}
【POD名称】 {{$v.labels.pod}}
【告警主题】{{$v.annotations.summary}}
  **{{$v.annotations.description}}**
{{end}}
{{ end }}

效果如图
![image](https://github.com/feiyu563/PrometheusAlert/assets/5228314/30ed7b55-0de9-4663-a71c-f326ed5b8b7a)

**Comment by jicki** [comment]
你告警规则中是否包含了 description  可以贴一下你的告警规则吗?

**Comment by chinaboy007** [comment]
- alert: KubeStatefulSetReplicasMismatch
        annotations:
          description: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset
            }} has not matched the expected number of replicas for longer than 15
            minutes.
          runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubestatefulsetreplicasmismatch
          summary: Deployment has not matched the expected number of replicas.
        expr: |
          (
            kube_statefulset_status_replicas_ready{job="kube-state-metrics"}
              !=
            kube_statefulset_status_replicas{job="kube-state-metrics"}
          ) and (
            changes(kube_statefulset_status_replicas_updated{job="kube-state-metrics"}[10m])
              ==
            0
          )
        for: 15m
        labels:
          severity: warning

**Comment by chinaboy007** [comment]
> 你告警规则中是否包含了 description 可以贴一下你的告警规则吗?

肯定是有的，我改成这样了
📝【告警详情】 {{ $v.annotations.message }}{{ $v.annotations.description}};{{$v.annotations.summary}}

现在效果如下：
![image](https://github.com/feiyu563/PrometheusAlert/assets/5228314/670b2be4-b9db-42e6-99ab-63a89236a5bc)

**Comment by chinaboy007** [comment]
> 你告警规则中是否包含了 description 可以贴一下你的告警规则吗?

已解决，部分K8S规则默认使用的是 annotations.message.  改成annotations.message 有显示了
