### ISSUE TITLE
请问有arm64的镜像吗？如何构建？

### ISSUE THREAD

**Issue by chinaboy007** [feiyu563/PrometheusAlert#348]
请问有arm64的镜像吗？如何构建？

**Comment by Zhang21** [comment]
在 arm64 架构的机器上拉取代码，安装 golang 环境，然后执行 `make build`。

**Comment by chinaboy007** [comment]
> 在 arm64 架构的机器上拉取代码，安装 golang 环境，然后执行 `make build`。

执行make 报错如下：
go: extracting gopkg.in/ini.v1 v1.66.2
go: extracting github.com/json-iterator/go v1.1.12
go: extracting github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/jmespath/go-jmespath/internal/testify v1.5.1
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/jmespath/go-jmespath/internal/testify v1.5.1
PrometheusAlert/models imports
        github.com/prometheus/client_golang/prometheus imports
        runtime/metrics: malformed module path "runtime/metrics": missing dot in first path element
make: *** [/opt/k8s/kube-prometheus/manifests/add/prometheusalert/PrometheusAlert-master//PrometheusAlert] Error 1

**Comment by chinaboy007** [comment]
已解决，我直接用github提供的Dockerfile构建成功了
