### ISSUE TITLE
微信机器人(wxurl)支持@所有人或某些人吗？

### ISSUE THREAD

**Issue by Zhang21** [feiyu563/PrometheusAlert#35]
wx webhook中是有一个参数，可以指定`@all`还是`@组内某些人`。想请问PrometheusAlert支持吗？

**Comment by feiyu563** [comment]
目前不支持，后面版本会更新上



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年6月22日(周一) 下午2:30
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 微信机器人(wxurl)支持@所有人或某些人吗？ (#35)




 
wx webhook中是有一个参数，可以指定@all还是@组内某些人。想请问PrometheusAlert支持吗？

**Comment by Zhang21** [comment]
好的

**Comment by codech** [comment]
这个大概是哪个版本能实现呢
