### ISSUE TITLE
告警恢复，飞书发送模板还是红色的

### ISSUE THREAD

**Issue by aichengli** [feiyu563/PrometheusAlert#354]
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }}{{if eq $v.status "resolved"}}**[Prometheus恢复信息]({{$v.generatorURL}})**
*[{{$v.labels.alertname}}]({{$var}})*
告警级别：{{$v.labels.severity}}
开始时间：{{$v.startsAt}}
结束时间：{{$v.endsAt}} 
故障主机IP：{{$v.labels.instance}}
**{{$v.annotations.description}}**{{else}}**[Prometheus告警信息]({{$v.generatorURL}})**
*[{{$v.labels.alertname}}]({{$var}})*
告警级别：{{$v.labels.severity}}
开始时间：{{$v.startsAt}}
故障主机IP：{{$v.labels.instance}}
**{{$v.annotations.description}}**{{end}}{{ end }}
{{ $urimsg:=""}}{{ range $key,$value:=.commonLabels }}{{$urimsg =  print $urimsg $key "%3D%22" $value "%22%2C" }}{{end}}[*** 点我屏蔽该告警]({{$var}}/#/silences/new?filter=%7B{{SplitString $urimsg 0 -3}}%7D)

默认模板 {{if eq $v.status "resolved"}}  当我传入状态为resloved的内容是，飞书通知还是红色的。 看了源码没啥问题

**Comment by zhangnan30** [comment]
需要在模板里加个告警状态就好了，如下：
![image](https://github.com/feiyu563/PrometheusAlert/assets/75722774/9f80e6f1-8a01-48a7-9250-06f5e2ac9d94)
![image](https://github.com/feiyu563/PrometheusAlert/assets/75722774/6c18d01b-698c-4e03-9036-cd5ba7f5c2f7)

**Comment by niutendo** [comment]
太溜了

**Comment by aichengli** [comment]
解决了，感觉
