### ISSUE TITLE
飞书告警详情变化

### ISSUE THREAD

**Issue by wiljay** [feiyu563/PrometheusAlert#36]
PrometheusAlert故障告警信息我这里用默认接口接收prometheus的告警的话，会出现PrometheusAlert故障告警信息与PrometheusAlert故障恢复信息。但是我用自定义的模版倒没有这变化。能问下是那个变量控制的吗？
以下是我模版
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }} 
[Prometheus告警信息]({{$v.generatorURL}})
[{{$v.labels.desc}}]
告警级别：{{$v.labels.severity}}
开始时间：{{$v.startsAt}}
结束时间：{{$v.endsAt}}
故障主机IP：{{$v.labels.instance}}
故障描述： {{$v.annotations.summary}}
{{ end }}

**Comment by feiyu563** [comment]
参考#30   
{{ $var := .externalURL}}{{ range $k,$v:=.alerts }}
{{if eq $v.status "resolved"}}
## [Prometheus恢复信息]({{$v.generatorURL}})
#### [{{$v.labels.alertname}}]({{$var}})
###### 告警级别：{{$v.labels.level}}
###### 开始时间：{{$v.startsAt}}
###### 结束时间：{{$v.endsAt}}
###### 故障主机IP：{{$v.labels.instance}}
##### {{$v.annotations.description}}
![Prometheus](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/alert-center.png)
{{else}}
## [Prometheus告警信息]({{$v.generatorURL}})
#### [{{$v.labels.alertname}}]({{$var}})
###### 告警级别：{{$v.labels.level}}
###### 开始时间：{{$v.startsAt}}
###### 结束时间：{{$v.endsAt}}
###### 故障主机IP：{{$v.labels.instance}}
##### {{$v.annotations.description}}
![Prometheus](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/alert-center.png)
{{end}}
{{ end }}

**Comment by chenHony666** [comment]
大佬们，这个externalURL怎么定义的？我的连接ip和端口不对
