### ISSUE TITLE
阿里云发送短信失败，原因是包含了URL，请问有什么办法可以格式化instance字段吗？

### ISSUE THREAD

**Issue by bee2287448** [feiyu563/PrometheusAlert#366]
你好，我是使用prometheus调用阿里云发送短信的，之前一直是好用的，最近发现短信发送不出来了，原因是阿里云短信可能现在更严格了。不允许包含URL。如截图所示：  像发出的告警中，instance 这个参数它阿里短信识别出来是URL，请问有办法在模板的时候对instance这个进行格式化吗，例如将 . 换成 _  这样就应该不会识别为URL。
alertname = exporter_status
alertstd = yes
appdesc = K&S
instance = ws008220.contoso.com:9182
还有那种blackbox监控url instance 也会显示  https://www.test123.com 可以格式化把前面的https去掉吗？

![alert1](https://github.com/feiyu563/PrometheusAlert/assets/120633853/7be83af2-cd68-4ecb-a1e6-22dec3e020a1)

**Comment by Zhang21** [comment]
Prometheus relabel 可以重写 instance

**Comment by Zhang21** [comment]
做网络黑盒探测，可以试下 easeprobe，比 blackbox 好配置。

**Comment by bee2287448** [comment]
谢谢，已经用relabel解决了。

**Comment by bee2287448** [comment]
谢谢，已经用relable 的方式解决了。
