### ISSUE TITLE
飞书告警模板能测试成功，但告警测试中的飞书告警测试有问题，请求帮助

### ISSUE THREAD

**Issue by zxr2333** [feiyu563/PrometheusAlert#378]
显示{"code":11246,"data":{},"msg":"path: message-\u003ecard; err_msg: invalid at user; err_type: validation; "}

某条日志：
{
    "msg_type": "interactive",
    "email": "xxxxxxxxxxx@qq.com",
    "card": {
        "config": {
            "wide_screen_mode": true,
            "enable_forward": true
        },
        "elements": [
            {
                "tag": "div",
                "text": {
                    "content": "[PrometheusAlert](https://github.com/feiyu563/PrometheusAlert)\n\n测试告警\n\n告警级别：测试\n\nPrometheusAlert\n\n![PrometheusAlert](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/alert-center.png)\u003cat email=xxxxxxxxxxx@qq.com id=xxxxxxxxxxx@qq.com\u003e\u003c/at\u003e",
                    "tag": "lark_md"
                },
                "content": "",
                "elements": null
            },
            {
                "tag": "hr",
                "text": {
                    "content": "",
                    "tag": ""
                },
                "content": "",
                "elements": null
            },
            {
                "tag": "note",
                "text": {
                    "content": "",
                    "tag": ""
                },
                "content": "",
                "elements": [
                    {
                        "tag": "lark_md",
                        "text": {
                            "content": "",
                            "tag": ""
                        },
                        "content": "PrometheusAlert",
                        "elements": null
                    }
                ]
            }
        ],
        "header": {
            "title": {
                "content": "PrometheusAlert",
                "tag": "plain_text"
            },
            "template": "red"
        }
    }
}

中间content配置具体是在哪

**Comment by zxr2333** [comment]
已解决，忽略该报错，但请务必检查alertmanager的配置文件，不然时间太久没办法接收到告警信息。

**Comment by vonvww** [comment]
我也是这个问题，请问怎么解决的呢？

**Comment by zxr2333** [comment]
这个是要选用合适的告警模板，在作者的模板分享那找个能用的就行



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月19日 17:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [feiyu563/PrometheusAlert] 飞书告警模板能测试成功，但告警测试中的飞书告警测试有问题，请求帮助 (Issue #378) |

我也是这个问题，请问怎么解决的呢？
