### ISSUE TITLE
微信告警恢复，颜色我能修改为绿色吗？

### ISSUE THREAD

**Issue by Zhang21** [feiyu563/PrometheusAlert#39]
使用md格式的微信机器人（webhook是支持的），默认的告警颜色是红色。

我能将告警恢复的颜色自定义为其它颜色吗？例如绿色。这样用于更直观的区别是告警还是恢复。在此程序中需要如何修改？

**Comment by feiyu563** [comment]
当然可以，参照下微信webhook的说明文档就行了



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年7月6日(周一) 下午4:28
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 微信告警恢复，颜色我能修改为绿色吗？ (#39)




 
使用md格式的微信机器人（webhook是支持的），默认的告警颜色是红色。
 
我能将告警恢复的颜色自定义为其它颜色吗？例如绿色。这样用于更直观的区别是告警还是恢复。在此程序中需要如何修改？

**Comment by Zhang21** [comment]
意思是需要在自定义模板上加上`<font color=xxx>xxx</font>`这个。

修改自定义模板又要替换alertmanger的访问地址。

能不能直接修改程序的默认模板？

**Comment by Zhang21** [comment]
但是我只需要恢复是绿色，告警我还是需要使用红色。我还是不知道在PrometheusAlert程序哪儿修改？ 能麻烦给个文档地址吗？谢谢！

还有，我觉得告警红色，恢复绿色可以直接写成PrometheusAlert默认。

**Comment by feiyu563** [comment]
暂时只有自定义模板接口可以修改，其他的接口都是固定模板



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年7月6日(周一) 晚上9:14
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 微信告警恢复，颜色我能修改为绿色吗？ (#39)




 
意思是需要在自定义模板上加上<font color=xxx&gt;xxx</font&gt;这个。
 
修改自定义模板又要替换alertmanger的访问地址。
 
能不能直接修改程序的默认模板？

**Comment by Zhang21** [comment]
但是自定义模板里面，如何区分是告警信息还是恢复信息？ @feiyu563

**Comment by Zhang21** [comment]
主要是如果使用自定义模板，在alertmanager里面的webhook地址就需要修改为特定模板的地址。

如果直接让模板以类似配置文件的方式，在启动的时候加载，是不是更好一些。这样我也不需要自定义模板，直接修改本地配置文件模板。

**Comment by Zhang21** [comment]
我个人觉得，把模板剥离成配置文件的格式不是更好些？

由于本人不会go，所以没看到程序的默认模板是写死在哪儿的。

**Comment by feiyu563** [comment]
#30  这个里面记录的有恢复告警的写法

**Comment by Zhang21** [comment]
好的，我先测试测试。

**Comment by feiyu563** [comment]
固定模板是方便对编程语言和监控系统不熟悉的人能方便配置接入到PrometheusAlert

**Comment by feiyu563** [comment]
自定义模板是最为推荐的一种方式

**Comment by Zhang21** [comment]
哦，看到日志了。模板是写入数据库里面去了。

**Comment by Zhang21** [comment]
> 自定义模板是最为推荐的一种方式

关于自定义模板我有一个问题，就是我使用自定义模板后，修改了alertmanager里的配置。那不是我所有告警都只能使用这一个模板？那我是不是需要在alertmanager receiver中配置多个地址？

**Comment by feiyu563** [comment]
alertmanager本身就可以通过路由配置多个地址



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年7月7日(周二) 上午10:37
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 微信告警恢复，颜色我能修改为绿色吗？ (#39)




  
自定义模板是最为推荐的一种方式
  
关于自定义模板我有一个问题，就是我使用自定义模板后，修改了alertmanager里的配置。那不是我所有告警都只能使用这一个模板？那我是不是需要在alertmanager receiver中配置多个地址？

**Comment by Zhang21** [comment]
我在微信机器人里面没有看到红色，但默认模板有红色。请问怎么配置的呢？

**Comment by Zhang21** [comment]
已找到，使用`#FF0000`这个格式。

**Comment by Zhang21** [comment]
使用自建模板的webhook地址，自建模板里面地址写死了，`app.conf`就不生效了，自定义的wxurl也不生效了。

如何解决？我改了数据库也不起作用。没找到默认的告警模板在代码何处。

@feiyu563

**Comment by Zhang21** [comment]
使用自建模板的webhook地址，自建模板里面地址写死了，`app.conf`就不生效了，自定义的wxurl也不生效了。

如何解决？我改了数据库也不起作用。没找到默认的告警模板在代码何处。

@feiyu563

**Comment by feiyu563** [comment]
没明白什么意思

**Comment by Zhang21** [comment]
> 没明白什么意思

@feiyu563 @xmx0632  请问两位的alertmanger是怎么配置的？

我按照文档配置，那不是wxurl已经被写死了？那自己配置的其它机器人是否就不生效了？还有就是，`app.conf`里面配置是否也不生效了？时间转换这些都不生效。

> 找到需要使用的自定义消息模版，复制表格中路径一列的地址内容，并将地址中[xxxxx]中的地址或手机号替换成你实际的配置，将其粘贴到对应的WebHook地址配置中即可。

<br>

我只是像使用自定义的模板，但我还是需要继续使用`app.conf`里面的内容。关于多个机器人，关于时区等等。怎么解决？

**Comment by Zhang21** [comment]
我能不能只填写模板地址，不填写其它配置，让它从`app.conf`里取读取？

我使用sqlite3连数据库都改了，使用默认的接口还是不生效。

这个默认的告警模板是写死在代码里面的了吗？我连数据库都改了，哎！

**Comment by feiyu563** [comment]
除了/prometheusalert 这个接口的，其他接口都是固定模板，无法更改模板的，新版本已经解决时区，多个机器人地址等问题

**Comment by Zhang21** [comment]
@feiyu563 好的，我等下一版测试以下。issue就先不关。

我还有一个疑问，为什么不直接把告警模板写在配置文件里面？这样就不需要sqlite数据库操作，也不需要自定义模板，直接改原模板就完了。
这样把模板从代码中拿出来，也解决了代码硬编码的问题。不是挺好的吗？何必搞得这么复杂！

在程序启动的时候去加载告警模板配置文件不就好了吗？

谢谢！

**Comment by feiyu563** [comment]
咱们默认支持的接入端和手机输出端太多，每个接入端和手机输出端都需要对应一个模板，通过配置文件不适合新手使用

**Comment by Zhang21** [comment]
把所有告警模板写入配置，启动时加载进行。新手使用的化，不修改就是用默认的，和写入代码中一样啊。

**Comment by feiyu563** [comment]
你觉得Prometheus和zabbix哪个操作体验会更好一点



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年7月8日(周三) 上午10:01
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 微信告警恢复，颜色我能修改为绿色吗？ (#39)




 
把所有告警模板写入配置，启动时加载进行。新手使用的化，不修改就是用默认的，和写入代码中一样啊。

**Comment by Zhang21** [comment]
我是运维，现在由于云原生这些，都在往Prometheus上迁了。 现在都是往metrics的趋势上走了。

**Comment by Zhang21** [comment]
你好，这个默认写在代码里的模板在哪个位置，我想手动去修改。

因为告警恢复也是和告警一样的颜色，很不直观。我想直接修改代码，自己编译二进制。

作者你也比较忙，这些功能不知道什么时候能上，我也去看了以下go的文档，大概看得懂一些了。

@feiyu563

**Comment by feiyu563** [comment]
在 Prometheus.go里面



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年8月10日(周一) 上午10:18
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 微信告警恢复，颜色我能修改为绿色吗？ (#39)




 
你好，这个默认写在代码里的模板在哪个位置，我想手动去修改。
 
因为告警恢复也是和告警一样的颜色，很不直观。我想直接修改代码，自己编译二进制。
 
作者你也比较忙，这些功能不知道什么时候能上，我也去看了以下go的文档，大概看得懂一些了。
 
@feiyu563

**Comment by Zhang21** [comment]
修改了`controller/prometheus.go`里面的微信机器人告警恢复格式:

```
wxtext = "[" + Title + "Prometheus" + titleend + "](" + RMessage.GeneratorUrl + ")\n>**[" + RMessage.Labels.Alertname + "](" + message.Externalurl + ")**\n> <font color=\"info\"> 告警级别: </font>" + AlertLevel[nLevel] + "\n> <font color=\"info\"> 开始时间: </font>" + At + "\n> <font color=\"info\"> 结束时间: </font>" + Et + "\n> <font color=\"info\"> 实例地址: </font>" + RMessage.Labels.Instance + "\n <font color=\"info\">" + RMessage.Annotations.Description + "</font>"
```

测试没什么问题。效果如下：

![image](https://user-images.githubusercontent.com/18358275/89772150-2001e980-db34-11ea-973a-cb68a2efe5cb.png)


<br>

我这里把issue关了，看作者你需不需要把这个改到代码里。 @feiyu563

**Comment by feiyu563** [comment]
这个下一版本会直接支持自定义模板的



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年8月10日(周一) 晚上6:06
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 微信告警恢复，颜色我能修改为绿色吗？ (#39)




 
修改了controller/prometheus.go里面的微信机器人告警恢复格式:
 wxtext = "[" + Title + "Prometheus" + titleend + "](" + RMessage.GeneratorUrl + ")\n&gt;**[" + RMessage.Labels.Alertname + "](" + message.Externalurl + ")**\n&gt; <font color=\"info\"&gt; 告警级别: </font&gt;" + AlertLevel[nLevel] + "\n&gt; <font color=\"info\"&gt; 开始时间: </font&gt;" + At + "\n&gt; <font color=\"info\"&gt; 结束时间: </font&gt;" + Et + "\n&gt; <font color=\"info\"&gt; 实例地址: </font&gt;" + RMessage.Labels.Instance + "\n <font color=\"info\"&gt;" + RMessage.Annotations.Description + "</font&gt;"  
测试没什么问题。效果如下：
 

 
 
我这里把issue关了，看作者你需不需要把这个改到代码里。 @feiyu563
