### ISSUE TITLE
模板中变量的值在哪里能修改吗？

### ISSUE THREAD

**Issue by xiaoya-create** [feiyu563/PrometheusAlert#392]
![image](https://github.com/feiyu563/PrometheusAlert/assets/53814170/9ff0e50b-5105-497d-bd85-96d45cadb87b)

**Comment by jicki** [comment]
alertname 不就是你 告警规则的名称吗？

**Comment by xiaoya-create** [comment]
> alertname 不就是你 告警规则的名称吗？

不好意思，圈错地方了，这个变量：$v.generatorURL 这个变量获取的值不太对，哪里可以更改吗

**Comment by jicki** [comment]
> > alertname 不就是你 告警规则的名称吗？
> 
> 不好意思，圈错地方了，这个变量：$v.generatorURL 这个变量获取的值不太对，哪里可以更改吗

这个是 prometheus 告警返回地址.

你看一下在 prometheus 内配置的  --web.external-url	 是什么
