### ISSUE TITLE
Feishu 报警无法@用户

### ISSUE THREAD

**Issue by KasterZhang** [feiyu563/PrometheusAlert#393]
![image](https://github.com/feiyu563/PrometheusAlert/assets/40155960/f1d4a315-a187-44ef-8222-fc96979a8670)
这里是不是写死了呀？

**Comment by cyenng** [comment]
使用uid是可以的

**Comment by hedaweiii** [comment]
> updated

大佬，请教一下，uid是指什么？飞书的id太抽象了，一个openid，userid，user_id

**Comment by cyenng** [comment]
> > updated
> 
> 大佬，请教一下，uid是指什么？飞书的id太抽象了，一个openid，userid，user_id

https://open.feishu.cn/document/faq/trouble-shooting/how-to-obtain-user-id  可以参考下官方文档

**Comment by feiyu563** [comment]
飞书目前支持 uid，email等，任意一个都行
