### ISSUE TITLE
多条告警不能汇聚，导致webhook被限流

### ISSUE THREAD

**Issue by lxl2562** [feiyu563/PrometheusAlert#395]
1条告警包含了20几条同样的告警，分了20几条发，导致飞书 钉钉webhook限流

如何聚合成一条发出去

**Comment by lxl2562** [comment]
![b202a27bb8bb1cd28239643cbe36056](https://github.com/feiyu563/PrometheusAlert/assets/66810859/0557faa3-4990-490e-901c-c43d4cf918bf)
还是分3条发出来

**Comment by lxl2562** [comment]
![e25cfda826eed739f300589bac7c4ad](https://github.com/feiyu563/PrometheusAlert/assets/66810859/70732105-70d2-412b-bb1c-ca9d517b137c)

**Comment by zxl00** [comment]
> 1条告警包含了20几条同样的告警，分了20几条发，导致飞书 钉钉webhook限流
> 
> 如何聚合成一条发出去

用webhook，应该是可以的，具体的你可以自行测试一下

**Comment by feiyu563** [comment]
参考这个：https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/system-var.md
