### ISSUE TITLE
PrometheusAlert:can't find templatefile in the path:views/index.html

### ISSUE THREAD

**Issue by ethanfang139** [feiyu563/PrometheusAlert#398]
版本：4.9

![image](https://github.com/feiyu563/PrometheusAlert/assets/171530673/2b788915-ea9c-416c-a3b5-9163b1de2573)

**Comment by ethanfang139** [comment]
相同也会出现PrometheusAlert:can't find templatefile in the path:views/login.html

**Comment by feiyu563** [comment]
进入到prometheusalert目录下执行启动命令
