### ISSUE TITLE
【功能】增加告警记录对 ES 8.x 版本的支持

### ISSUE THREAD

**Issue by Zhang21** [feiyu563/PrometheusAlert#399]
目前已支持 ES 7.x。

<br/>

参考:

- <https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/index.html>
- <https://github.com/elastic/go-elasticsearch>

**Comment by Zhang21** [comment]
由于 es 8.x 适配了 es 7.x ，因此 go-elasticsearch 7.x 最新版本本可以适配 es 8.x 版本

**Comment by LiaoSirui** [comment]
连接 v8.16.1 时发生错误：

```bash
[elasticsearch] Error getting response: tls: failed to verify certificate: x509: cannot validate certificate for 192.168.248.84 because it doesn't contain any IP SANs
```

看起来并不是兼容的

**Comment by LiaoSirui** [comment]
im so sorry 

我才注意到 release 4.9.1 并未合并您的请求：<https://github.com/feiyu563/PrometheusAlert/blob/v4.9.1/go.mod>
