### ISSUE TITLE
钉钉如何实现ding某人，我想在rules里面配置

### ISSUE THREAD

**Issue by reaperhero** [feiyu563/PrometheusAlert#40]

**Comment by feiyu563** [comment]
正在准备实现这块，目前还在开发



---原始邮件---
发件人: "reaperhero"<notifications@github.com&gt;
发送时间: 2020年7月9日(周四) 中午11:06
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 钉钉如何实现ding某人，我想在rules里面配置 (#40)

**Comment by reaperhero** [comment]
大佬，加油

**Comment by Passeng-LUCA** [comment]
大佬，加油，期待这个功能

**Comment by yinglingqihang** [comment]
大佬 加油

**Comment by xiaosadexiaohai** [comment]
大佬 加油
我也很需要这个功能!~

**Comment by xiaosadexiaohai** [comment]
@feiyu563 大佬 有空看看这个功能

**Comment by fency12** [comment]
大佬 加油
我也很需要这个功能!~

**Comment by feiyu563** [comment]
PrometheusAlert master分支上已经集成了钉钉，企业微信，飞书V2机器人 @某人的 功能，有需要的可以自己测试下
