### ISSUE TITLE
telegram机器人不支持markdown? 

### ISSUE THREAD

**Issue by boy530** [feiyu563/PrometheusAlert#403]
譬如同样发送： \*\*告警名称\*\* , 
如果手动发送，字体就加粗了  **告警名称** ，
但是通过机器人发送出来，就还是显示字符 \*\*告警名称\*\*
请问哪位知道原因？
怎样才能把这个参数传递进去呢？ PARSE_MODE="Markdown"
谢谢

**Comment by feiyu563** [comment]
4.9.1版本已经合并
