### ISSUE TITLE
有没有提供示例的json，作为一个小白无法测试模板正确与否

### ISSUE THREAD

**Issue by wowkow** [feiyu563/PrometheusAlert#405]

**Comment by wowkow** [comment]
![65ce9692-7c09-4be6-bb08-afaed4d057d3](https://github.com/feiyu563/PrometheusAlert/assets/42179485/4c909873-6902-4fdf-a24c-505def97502a)
如何测试呢

**Comment by zxl00** [comment]
文档里有的
https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/system-customtpl.md

**Comment by boy530** [comment]
其实很简单，你只要发一条自然就明白了。

**Comment by wowkow** [comment]
> 文档里有的 https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/system-customtpl.md

感谢大佬
