### ISSUE TITLE
使用模板的获取时间，跟实际时间不符，有没有大佬遇到过，模板配置为开始时间：{{TimeFormat $v.startsAt "2006-01-02 15:04:05"}}

### ISSUE THREAD

**Issue by wowkow** [feiyu563/PrometheusAlert#406]
![Uploading 79428b9e-2a4d-4d82-ad78-6a8c4017c8e9.jpeg…]()

**Comment by wowkow** [comment]
![Uploading 79428b9e-2a4d-4d82-ad78-6a8c4017c8e9.jpeg…]()

**Comment by dkaiyun** [comment]
{{GetCSTtime  $v.startsAt}}
