### ISSUE TITLE
PrometheusAlert 无法处理 webhook 接收到的和 web 端模板测试的 JSON 内容 [D] [value.go:586]  [1720056309675801231] 

### ISSUE THREAD

**Issue by DesistDaydream** [feiyu563/PrometheusAlert#409]
![image](https://github.com/feiyu563/PrometheusAlert/assets/39847025/941085e7-03b3-45e4-919b-d3bbc42e9a29)

![image](https://github.com/feiyu563/PrometheusAlert/assets/39847025/c2d12ad8-3403-4648-8cf2-4a23e6468f24)

在 web 端通过 “告警测试” 标签页可正常处理，且 bot 可接收到消息

但是，通过 webhook 发送的数据、“模板管理-自定义模板” 中的“模板测试”无法处理 JSON 数据。已知 JSON 正常，使用的程序默认的模板。

无法找到开启 DeBUG 日志的方式，找不到 value.go:586 代码所在处。

> 另: 如何通过配置文件在启动时加载自定义模板？

**Comment by feiyu563** [comment]
自定义模板的测试需要填充消息协议json内容和机器人地址才能正常
