### ISSUE TITLE
运行时指定配置文件和 views 等文件位置

### ISSUE THREAD

**Issue by Bowser1704** [feiyu563/PrometheusAlert#41]
例如： 将可执行文件放在 `/opt/prometheusalert/PrometheusAlert`

```bash
# 执行命令，只会在当前目录寻找配置文件和 view、db 等文件夹。
/opt/prometheusalert/PrometheusAlert
```
导致的问题是无法利用 systemd 管理服务。会找不到配置文件等东西。

建议 ：`Db_name:= "./db/PrometheusAlertDB.db"` 等都改为使用 app.config 默认值。 并且添加参数指定 config。

**Comment by feiyu563** [comment]
可以在Service文件中指定 `WorkingDirectory=` 即可.
