### ISSUE TITLE
钉钉告警现在无法@人

### ISSUE THREAD

**Issue by silentdark** [feiyu563/PrometheusAlert#411]
以前是可以的，不知道从啥时候开始@人变成了普通文字
软件版本是最新4.9.1版本

**Comment by dellnoantechnp** [comment]
没问题   `ddurl=https://xxxx&at=1380000000`   记得是这样的

**Comment by silentdark** [comment]
哦，现在钉钉的markdown格式at是没有高亮效果了，提示效果还是有的
