### ISSUE TITLE
[需求]webhook支持企业微信应用转发告警消息

### ISSUE THREAD

**Issue by nondevops** [feiyu563/PrometheusAlert#42]
[需求]webhook支持企业微信应用转发告警消息
需求描述：
当今互联网使用企业微信作为IM及时沟通工具较多，也用企业微信应用发送相关告警及其他消息给指定的人的需求也比较常见。如通知某某某拿快递等等，鉴于此，希望webhook增加对企业微信应用的支持兼容。

功能点：
企业微信APP应用的核心参数可在app.conf配置；
![image](https://user-images.githubusercontent.com/12181410/90641904-56421600-e264-11ea-8c7c-d50f77603291.png)

企业微信APP应用支持API消息接收；
![image](https://user-images.githubusercontent.com/12181410/90641847-432f4600-e264-11ea-8b93-1ea8b288a4ce.png)
![image](https://user-images.githubusercontent.com/12181410/90641953-60fcab00-e264-11ea-8d09-8fa94b889788.png)

支持图文格式的消息内容收发；

支持markdown格式的消息内容收发；

支持文本格式的消息内容收发；

支持语音格式的消息内容收发；

支持任务卡片格式的消息内容收发；

更多请参考企业微信API文档：
https://work.weixin.qq.com/api/doc/90001/90143/90372

影响：
将完善消息通知通道，提升通道覆盖率；

请酌情考虑，谢谢。

**Comment by Zhang21** [comment]
@feiyu563 可以参考alertmanager的wechat通知: <https://github.com/prometheus/alertmanager/blob/master/notify/wechat/wechat.go>

这个就是alertmanager自带的对企业微信api的支持。

**Comment by w6m6** [comment]
+1。
