### ISSUE TITLE
报警日志无法插入数据库

### ISSUE THREAD

**Issue by ChronosSong** [feiyu563/PrometheusAlert#423]
报错: Data too long for column 'labels' at row 1
详细日志如下：
[ORM]2024/08/02 02:23:24  -[Queries/default] - [FAIL /     db.Exec /     2.7ms] - 
[INSERT INTO `alert_record` (`alertname`, `alert_level`, `labels`, `instance`, `starts_at`, `ends_at`, `summary`, `description`, `alert_status`, `created_time`, `updated_by`, `updated_time`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] 
- `InstanceDown`, ``, `{"agentpool":"fdsaf","alertname":"InstanceDown","beta_kubernetes_io_arch":"amd64","beta_kubernetes_io_instance_type":"fdsafdasf","beta_kubernetes_io_os":"linux","failure_domain_beta_kubernetes_io_region":"dfsafdsaf","failure_domain_beta_kubernetes_io_zone":"0","instance":"gfdsfgfdsgfsd","job":"kubernetes-nodes","kubernetes_azure_com_agentpool":"gfdsfsa","kubernetes_azure_com_cluster":"fgdsagfdsafa,"kubernetes_azure_com_consolidated_additional_properties":"fdsafdsafdsafdsa","kubernetes_azure_com_kubelet_identity_client_id":"gdasgdsafasdf","kubernetes_azure_com_mode":"user","kubernetes_azure_com_network_policy":"none","kubernetes_azure_com_node_image_version":"gsagdsafdsafafd","kubernetes_azure_com_nodepool_type":"VirtualMachineScaleSets","kubernetes_azure_com_os_sku":"Ubuntu","kubernetes_azure_com_role":"agent","kubernetes_io_arch":"amd64","kubernetes_io_hostname":"gfdsfgfdsgfsd","kubernetes_io_os":"linux","kubernetes_io_role":"agent","node_kubernetes_io_instance_type":"fdsafdsa","severity":"page","topology_kubernetes_io_region":"fdsafdasf","topology_kubernetes_io_zone":"0"}`, `gfdsfgfdsgfsd`, `2024-08-02 10:23:14`, `0001-01-01 08:00:00`, `Instance gfdsfgfdsgfsd down`, `gfdsfgfdsgfsd of job kubernetes-nodes has been down for more than 5 minutes.`, `firing`, `2024-08-02 02:23:24.358525977 +0000 UTC`, ``, `2024-08-02 02:23:24.358526077 +0000 UTC` - Error 1406 (22001): Data too long for column 'labels' at row 1

**Comment by feiyu563** [comment]
最新的版本有更新过数据库字段的长度，可以试下
