### ISSUE TITLE
企业微信收不到告警信息

### ISSUE THREAD

**Issue by Tomas-zhang** [feiyu563/PrometheusAlert#426]
配置app.conf如下：
![image](https://github.com/user-attachments/assets/1f05b572-f476-4cbc-8daf-5e9f88207061)
prometheus已有告警
![image](https://github.com/user-attachments/assets/fd3236ac-34a1-4645-8ad3-7cf3b3f4df5b)
但企业微信未收到告警信息，请教是哪里的问题

**Comment by Tomas-zhang** [comment]
急，在线等，请大佬指导下

**Comment by feiyu563** [comment]
看下你的alertmanager的配置是不是有问题

**Comment by Tomas-zhang** [comment]
> 看下你的alertmanager的配置是不是有问题

感谢大佬，确实是alertmanager配置写错了。

**Comment by Tomas-zhang** [comment]
fixed
