### ISSUE TITLE
自定义的模版如何进行持久化？

### ISSUE THREAD

**Issue by bindyou** [feiyu563/PrometheusAlert#429]
我使用k8s部署的PrometheusAlert，自定义了模版内容，当pod重启后模板便恢复成为原始内容，我尝试挂载了自定义的prometheus-alert-template.json，但是没有效果，请问应该修改哪里来实现模版的持久化？

**Comment by bwdeng1** [comment]
持久化这个-PrometheusAlertDB.db

**Comment by feiyu563** [comment]
或者改为其他支持的数据库系统
