### ISSUE TITLE
是否可以按照调用url所传入的值决定告警方式，而不是根据告警级别来固定告警方式？

### ISSUE THREAD

**Issue by minibear2333** [feiyu563/PrometheusAlert#43]
假设只有邮件短信两种告警方式，想要自己决定，所有告警级别全部发邮件，或者1，2发邮件，3，4，5发短信。
如果可以通过Url传入参数来决定，会更加灵活。
我看到如下位置的代码，部分是支持的根据url来解析告警通知方式的

https://github.com/feiyu563/PrometheusAlert/blob/92ce2ebe1fd6616b1d894930a050ab1361659519/controllers/prometheus.go#L126

建议短信和电话也切换成这种方式，如果您认同我的看法请告知我，我将会协助您一起修改

**Comment by feiyu563** [comment]
自定义模板的接口可以支持通过URL作为参数指定告警通知的方式。结合alertmanger的路由可以做到更精确的告警路由，老的`/prometheus/alert` 和 `/prometheus/router` 接口主要是早期为了方便部分用户而设计的，后面还是比较推荐使用自定义模板接口，相对老的接口会更加灵活一些。
