### ISSUE TITLE
prometheus接收告警信息时，重复代码过多

### ISSUE THREAD

**Issue by minibear2333** [feiyu563/PrometheusAlert#44]
以下两行所定义的router
https://github.com/feiyu563/PrometheusAlert/blob/92ce2ebe1fd6616b1d894930a050ab1361659519/routers/router.go#L21
https://github.com/feiyu563/PrometheusAlert/blob/92ce2ebe1fd6616b1d894930a050ab1361659519/routers/router.go#L22

在此文件内的两个函数有大量重复代码，是否可以合并优化？
https://github.com/feiyu563/PrometheusAlert/blob/92ce2ebe1fd6616b1d894930a050ab1361659519/controllers/prometheus.go#L84
https://github.com/feiyu563/PrometheusAlert/blob/92ce2ebe1fd6616b1d894930a050ab1361659519/controllers/prometheus.go#L207

**Comment by feiyu563** [comment]
已经合并
