### ISSUE TITLE
helm部署的prometheusalert服务

### ISSUE THREAD

**Issue by haerr** [feiyu563/PrometheusAlert#440]
服务扩容成两个pod节点后， 又修改成一个pod，服务发送告警消息至飞书总是多发一条相同的告警消息
![image](https://github.com/user-attachments/assets/31def088-6e8f-40d7-869e-5d96aa4951d7)

**Comment by scofieldYang** [comment]
可以看日志的，接收了几个告警，匹配了几个路由，这都会导致多发
