### ISSUE TITLE
prometheus，alertmanager配置密码后，prometheusalert无法发送报警信息了

### ISSUE THREAD

**Issue by 505100745** [feiyu563/PrometheusAlert#441]
由于漏扫扫出来Prometheus Alertmanager告警管理器 存在未授权访问漏洞，给prometheus，alertmanager配置密码后，prometheusalert无法发送报警信息了，这个需要怎么配置下呢？有没有遇到同样问题的？

**Comment by ilanni2460** [comment]
@505100745 肯定是你配置漏了哪些东西，我这边也是配置了认证信息，现在照常可以接收告警信息

**Comment by feiyu563** [comment]
prometheusalert只负责接收消息，只要alertmanager能发出消息，就不会影响
