### ISSUE TITLE
4.9.1的表结构和SQL都对不上

### ISSUE THREAD

**Issue by liang2025** [feiyu563/PrometheusAlert#453]
表结构是7个字段，SQL只给了6个数据

**Comment by liang2025** [comment]
都不测试就上线，全是问题BUG。

**Comment by feiyu563** [comment]
SQL是默认数据，可用可不用，程序会自动修正表结构

**Comment by liang2025** [comment]
我知道是默认数据，可用可不用，但是程序一直报错无法启动，而程序也并没有自动修正表结构。还有，4.8版本的configmap是正常，但到了4.9，data数据全写到一行，对日后的维护很有影响。懂的自己会去看代码，调整数据，对应上表结构，修改CONFIGMAP。但这对用户来说，还要自己去改原始代码BUG， 这就有点... ...

**Comment by calacaly** [comment]
按照官方的说法，要改template/deployment.yaml

其中容器启动命令改为

command: ['sh', '-c', "/app/PrometheusAlert"]

就修改这一个就能正常启动
