### ISSUE TITLE
飞书告警测试报错：code:11246

### ISSUE THREAD

**Issue by socake** [feiyu563/PrometheusAlert#461]
2024/11/24 00:02:29.580 [I] [feishu.go:30]  [1732377749580084638] [feishuv2] {"msg_type":"interactive","email":"xxxxxxxxxxx@qq.com","card":{"config":{"wide_screen_mode":true,"enable_forward":true},"elements":[{"tag":"div","text":{"content":"[PrometheusAlert](https://github.com/feiyu563/PrometheusAlert)\n\n测试告警\n\n告警级别：测试\n\nPrometheusAlert\n\n![PrometheusAlert](https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/images/alert-center.png)\u003cat user_id=xxxxxxxxxxx@qq.com id=xxxxxxxxxxx@qq.com email=xxxxxxxxxxx@qq.com\u003e\u003c/at\u003e","tag":"lark_md"},"content":"","elements":null},{"tag":"hr","text":{"content":"","tag":""},"content":"","elements":null},{"tag":"note","text":{"content":"","tag":""},"content":"","elements":[{"tag":"lark_md","text":{"content":"","tag":""},"content":"PrometheusAlert","elements":null}]}],"header":{"title":{"content":"PrometheusAlert","tag":"plain_text"},"template":"red"}}}

2024/11/24 00:02:29.830 [I] [feishu.go:30]  [1732377749580084638] [feishuv2] PrometheusAlert: {"code":11246,"data":{},"msg":"ErrCode: 100290; ErrMsg: there is an invalid user resource (at/person) in your card; ErrorValue: x**********@******; "}

**Comment by feiyu563** [comment]
该报错是由于飞书API更新导致，已经在master分支同步修正测试功能部分代码，待下次release正式发布  https://github.com/feiyu563/PrometheusAlert/commit/c17bba3fda98fa896154c92e90ec88b267b57c00

**Comment by WuWeeeee** [comment]
作者大大什么时候发布下一次release
