### ISSUE TITLE
新手遇到安装了部署的问题，提示需要安装了 CRDs

### ISSUE THREAD

**Issue by jaysey** [feiyu563/PrometheusAlert#462]
$ helm install -n monitoring . --generate-name
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "chart-1732591547-prometheusalert" namespace: "" from "": no matches for kind "Ingress" in version "extensions/v1beta1"
ensure CRDs are installed first

我看了当前目录，没有任何关于 CRDs 的文件，也没有chart-1732591547-prometheusalert 这个服务，我的 prometheus 是通过 helm 安装的 opration 社区版本，请各位大拿指导，谢谢。

**Comment by ysicing** [comment]
ingress版本比较低了，自己参考高版本改一下

**Comment by jaysey** [comment]
> ingress版本比较低了，自己参考高版本改一下

好的，多谢大拿。
