### ISSUE TITLE
测试阿里云短信通道报参数错误

### ISSUE THREAD

**Issue by luyebb** [feiyu563/PrometheusAlert#48]
页面提示：
![image](https://user-images.githubusercontent.com/5848479/89282255-d3bf3100-d67d-11ea-8e30-5190a269ab40.png)
日志显示：
![image](https://user-images.githubusercontent.com/5848479/89282351-f81b0d80-d67d-11ea-8333-eb0f1908e0ec.png)

**Comment by liangxiaowxylk** [comment]
我也遇到同样的情况

**Comment by feiyu563** [comment]
参考这个说明文档 https://github.com/feiyu563/PrometheusAlert/blob/master/doc/readme/aliyun.md

注意两个地方：
1.开通阿里云短信和语音需要配置的模版请使用如下，${code}为变量名称，请勿替换。如 ：prometheus告警:${code}
2.短信模版类型选择：短信通知 ，如果需要选择变量属性，请选择其他。

**Comment by feiyu563** [comment]
如果依旧不行，则需要找下阿里云的客服开通下限制

**Comment by liangxiaowxylk** [comment]
您好 非常感谢回复.我试了下还是不行,您能说下可能的原因吗 是开通什么限制
















在 2020-08-17 17:15:28，"feiyu563" <notifications@github.com> 写道：

如果依旧不行，则需要找下阿里云的客服开通下限制

**Comment by feiyu563** [comment]
开通下单个短信模板变量允许的字符长度



---原始邮件---
发件人: "xiaoliang"<notifications@github.com&gt;
发送时间: 2020年8月17日(周一) 下午5:56
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 测试阿里云短信通道报参数错误 (#48)




 您好 非常感谢回复.我试了下还是不行,您能说下可能的原因吗 是开通什么限制
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 在 2020-08-17 17:15:28，"feiyu563" <notifications@github.com&gt; 写道：
 
 如果依旧不行，则需要找下阿里云的客服开通下限制
