### ISSUE TITLE
[展望] 感觉此软件可发展为一个消息中心

### ISSUE THREAD

**Issue by Zhang21** [feiyu563/PrometheusAlert#49]
感觉这个软件可以发展成为一个消息转换和发送中心，而不仅仅限于告警。

可接收各种不同软件源的消息，通过PrometheusAlert处理，发送给各种接收软件。

后面感觉可以改名为**MessageCenter**。

```
告警类:
  prometheus                                                                    wx
  grafana                                                                      dingding
  zabbix                                                                       ali
代码类:                                                                         tx
  gitlab                                                                       hw
  gogs                                                                         email
构建类:           -------->  PrometheusAlert   -------->                        feishu
  jenkins                                                                        ...
  bamboo
任务类:
  redmine
  jira
...
```

**Comment by feiyu563** [comment]
非常感谢对PrometheusAlert的认可。

**Comment by Zhang21** [comment]
@feiyu563 

作者你好。我最近看了go官方文档，想学习此项目的源代码，并进一步学习go。

对于此项目的源代码，我该怎么入手学习呢？可能以后也需要添加一些自己的需求。

Thx!

**Comment by feiyu563** [comment]
推荐你可以简单学习下beego框架，然后从项目的Prometheus.go开始，整个项目基本都是基于这个一路写的



---原始邮件---
发件人: "Leslie Zhang"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 上午9:32
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] [展望] 感觉此软件可发展为一个消息中心 (#49)




 
@feiyu563
 
作者你好。我最近看了go官方文档，想学习此项目的源代码，并进一步学习go。
 
对于此项目的源代码，我该怎么入手学习呢？可能以后也需要添加一些自己的需求。
 
Thx!

**Comment by Zhang21** [comment]
好的，谢谢你。
