### ISSUE TITLE
高可用优化建议及通用性建议

### ISSUE THREAD

**Issue by minibear2333** [feiyu563/PrometheusAlert#50]
1. 引入SQLite来本地存储模板，不方便扩展成多实例，要不要考虑去掉或者增加开关？
2. 接入的数据格式默认是prometheus，其他服务不太方便接入，考虑增加更通用的接口？
3. 没有失败重试或日志的功能

**Comment by feiyu563** [comment]
1.高可用方面，下一版本准备提供MySQL和sqlite两个选项
2.接入的数据其实提供了很多接口，目前全能的接口主要是自定义模板接口
3.失败重试方面确实还没集成的很好，这个后期会逐步优化，日志后期也会继续优化

**Comment by Zhang21** [comment]
@feiyu563 @minibear2333 失败重试，程序要怎么判断呢？异步的化，不好判断返回状态。

**Comment by feiyu563** [comment]
失败重试主要针对消息接收端，比如短信电话这些，一般都有回调接口查询发送状态，目前重启只有腾讯语音有这部分逻辑

**Comment by feiyu563** [comment]
4.3版本已经更新支持mysql作为存储
