### ISSUE TITLE
飞书是否可以支持不同场景@某人

### ISSUE THREAD

**Issue by D-wenhao** [feiyu563/PrometheusAlert#52]
如题

**Comment by feiyu563** [comment]
后续版本会集成



---原始邮件---
发件人: "D-hero."<notifications@github.com&gt;
发送时间: 2020年9月1日(周二) 晚上8:54
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 飞书是否可以支持不同场景@某人 (#52)




 
如题

**Comment by herozabbix** [comment]
大佬加油。希望可以尽快实现这个功能，

**Comment by jicki** [comment]
我也需要这个功能，希望能快点出来呀。。

**Comment by feiyu563** [comment]
PrometheusAlert master分支上已经集成了钉钉，企业微信，飞书V2机器人 @某人的 功能，有需要的可以自己测试下
