### ISSUE TITLE
aliyun公共号码池电话号码配置报错

### ISSUE THREAD

**Issue by ne1000** [feiyu563/PrometheusAlert#58]
配置

`
    open-alydh=1
    #阿里云电话主账号AccessKey的ID
    ALY_DH_AccessKeyId=2VXfRPdQbRU
    #阿里云电话接口密钥
    ALY_DH_AccessSecret=zGDaF2VXfRPdQbRU0Ia
    #阿里云电话被叫显号，必须是已购买的号码
    ALY_DX_CalledShowNumber=
    #阿里云电话文本转语音（TTS）模板ID
    ALY_DH_TtsCode=TTS_1960992

`

报错
{"RequestId":"BA69B4AC-ADF5-4E55-8758-EBD7EE67E8D7","Message":"模板变量缺少对应参数值","Code":"isv.TEMPLATE_MISSING_PARAMETERS"}

**Comment by feiyu563** [comment]
应该是你的模板问题，不是像是号码池的问题

**Comment by ne1000** [comment]
@feiyu563 谢谢，已解决

**Comment by fys05** [comment]
我也遇到了这个问题，怎么解决的呀
