### ISSUE TITLE
go-sqlite3 requires cgo to work

### ISSUE THREAD

**Issue by dbaicss** [feiyu563/PrometheusAlert#62]
启动服务报错信息如下:
register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
must have one register DataBase alias named `default`

**Comment by feiyu563** [comment]
容器运行报错？

**Comment by feiyu563** [comment]
使用新版本的容器镜像，这个应该是老的镜像有问题
