### ISSUE TITLE
关于PromtheusAlert一些功能的疑问

### ISSUE THREAD

**Issue by BoxuanChen** [feiyu563/PrometheusAlert#64]
请问现在版本的PromtheusAlert可以实现根据告警消息的内容决定发给某个人, 或者某个组吗?
而不是根据告警label进行分发告警,

**Comment by feiyu563** [comment]
这个你可以利用rules中phone，ddurl,wxurl,fsurl这些字段来分发消息

**Comment by BoxuanChen** [comment]
您好, 有配置的示例吗? 
我的意思是比如说我有一个关于主机内存的告警, 我想根据告警内容中hostname这个值来分发告警, 比如A主机发给A组的人, B主机发给B组的人. 
这样可以实现这种功能吗? 如果用原生的promtheus+alertmanager就只能写好几个相同的rules配上不同的label来实现.

**Comment by feiyu563** [comment]
这个需要配合alertmanager的消息分组来实现了



---原始邮件---
发件人: "BoxuanChen"<notifications@github.com&gt;
发送时间: 2020年10月14日(周三) 下午4:41
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 关于PromtheusAlert一些功能的疑问 (#64)




 
您好, 有配置的示例吗?
 我的意思是比如说我有一个关于主机内存的告警, 我想根据告警内容中hostname这个值来分发告警, 比如A主机发给A组的人, B主机发给B组的人.
 这样可以实现这种功能吗? 如果用原生的promtheus+alertmanager就只能写好几个相同的rules配上不同的label来实现.

**Comment by BoxuanChen** [comment]
alertmanager可以支持这个功能吗? 
你说的是通过写多个告警rule么

**Comment by feiyu563** [comment]
你可以搜索下alertmanager的路由功能



---原始邮件---
发件人: "BoxuanChen"<notifications@github.com&gt;
发送时间: 2020年10月14日(周三) 晚上6:11
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 关于PromtheusAlert一些功能的疑问 (#64)




 
alertmanager可以支持这个功能吗?
 你说的是通过写多个告警rule么
