### ISSUE TITLE
自定义告警消息模版中如何对startsat等时间属性进行格式化啊？

### ISSUE THREAD

**Issue by w6m6** [feiyu563/PrometheusAlert#65]
比如按照“YYYY--MM--DD" 进行显示？

**Comment by feiyu563** [comment]
这部分目前需要改下源代码



---原始邮件---
发件人: "magic.chen"<notifications@github.com&gt;
发送时间: 2020年10月20日(周二) 下午4:26
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 自定义告警消息模版中如何对startsat等时间属性进行格式化啊？ (#65)




 
比如按照“YYYY--MM--DD" 进行显示？

**Comment by w6m6** [comment]
我看的有一个getCSTdate的函数，目前还有别的函数么？

**Comment by feiyu563** [comment]
暂时只有这一个



---原始邮件---
发件人: "magic.chen"<notifications@github.com&gt;
发送时间: 2020年10月20日(周二) 晚上6:12
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 自定义告警消息模版中如何对startsat等时间属性进行格式化啊？ (#65)




 
我看的有一个getCSTdate的函数，目前还有别的函数么？

**Comment by w6m6** [comment]
好的。多谢。
