### ISSUE TITLE
alertmanager传过来的时间怎么格式化？

### ISSUE THREAD

**Issue by missops** [feiyu563/PrometheusAlert#67]
"startsAt":"2020-10-29T21:14:30.202054226+08:00" 

怎么在自定义模板里面格式化成: 2020-10-29 21:14:30 这样子的？

**Comment by feiyu563** [comment]
目前还没有提供格式转换这方面的函数，但是你可以搜索下go模版函数，里面好像有个可以截取字符串的，然后在自定义模版里面自己做下拼接就行了。
目前只有非UTC时间转换成CST时间的函数会自动处理时间，并格式化成你需要的样子，但是你这个时间本身已经是CST的了

**Comment by missops** [comment]
Go 模板里面一般是.Format "2006 Jan 02" 这样处理，但是在自定义模板内这样设置不能成功。
