### ISSUE TITLE
/prometheus/alert路径无法访问

### ISSUE THREAD

**Issue by lugoing** [feiyu563/PrometheusAlert#68]
按照 https://feiyu563.gitbook.io/prometheusalert/prometheusalert-gao-jing-yuan-pei-zhi/prometheus-pei-zhi 中的介入配置，第一种方式，
webhook_configs:
  - url: 'http://[prometheusalert_url]:8080/prometheus/alert'
我设置为
http://172.17.80.210:9133/prometheus/alert
好像是无法访问到这个地址？

**Comment by zhaoxuezhi888** [comment]
你的端口不是8080么，访问9133不行把？

**Comment by lugoing** [comment]
> 0

我改过了是9133，网页版本可以访问，点网页上的test，微信也能收到通知，但是配置进alertmanage就收到通知了。。

**Comment by lugoing** [comment]
> 你的端口不是8080么，访问9133不行把？

我改过了是9133，网页版本可以访问，点网页上的test，微信也能收到通知，但是配置进alertmanage就收到通知了。。

**Comment by lugoing** [comment]
方法2可以发送通知。我再测试下方法1
