### ISSUE TITLE
支持公司自己语音系统。电话告警

### ISSUE THREAD

**Issue by jiangnanora** [feiyu563/PrometheusAlert#70]
目前看支持了阿里云、腾讯云、华为云；但我司有自己的语音系统，这块如何配置

**Comment by feiyu563** [comment]
需要自己在现有的源码基础上稍加改动一下，适配你们自己的接口应该就可以了



---原始邮件---
发件人: "jiangnanora"<notifications@github.com&gt;
发送时间: 2020年11月2日(周一) 下午5:16
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 支持公司自己语音系统。电话告警 (#70)




 
目前看支持了阿里云、腾讯云、华为云；但我司有自己的语音系统，这块如何配置
