### ISSUE TITLE
请问怎么在grafana里添加飞书v2的webhook

### ISSUE THREAD

**Issue by jitangshaobing** [feiyu563/PrometheusAlert#71]
![image](https://user-images.githubusercontent.com/13791128/97954656-14def280-1ddf-11eb-8813-e9bc886c5956.png)
grafana/feishu 好像不行，不能触发消息
![image](https://user-images.githubusercontent.com/13791128/97954694-317b2a80-1ddf-11eb-8d9f-47ff2d8ce430.png)
这里告警测试正常

**Comment by situjianxiong** [comment]
同问 我试了feishu2,feishuv2都不行

**Comment by feiyu563** [comment]
飞书V2的目前只能支持自定义模版的接口。比如打开 `http://你部署的PrometheusAlert的地址/template` ，找到最下面的
![image](https://user-images.githubusercontent.com/25146052/98635872-aeb71a00-2360-11eb-8d43-7d1c8f576469.png)


注意里面的`路径`一栏：
比如我的：`http://你部署的PrometheusAlert的地址/prometheusalert?type=fsv2&tpl=prometheus-fsv2&fsurl=飞书v2机器人地址`
