### ISSUE TITLE
prometheusalert可以支持user.csv吗

### ISSUE THREAD

**Issue by Zyawn** [feiyu563/PrometheusAlert#72]
目前使用腾讯云语音告警，
想要使用user.csv分日期对不同手机号拨打电话并且使用自定义模板，
看了下源码，prometheus/router 那边不支持使用自定义模板，prometheusalert 那边不去遍历user.csv
请问有什么方案可以满足吗？

**Comment by feiyu563** [comment]
我下一版本增进下支持吧

**Comment by qingfengfenga** [comment]
我想问一下，当前不支持user.csv的话，是不是只能在配置文件的全局配置（defaultphone=）配置固定的号码，而且只能配置一个

**Comment by feiyu563** [comment]
号码可以配置多个，主要看你用的什么接口，
defaultphone只支持一个号码，其他的接口都支持多个


---原始邮件---
发件人: "qingfengfenga"<notifications@github.com&gt;
发送时间: 2020年11月18日(周三) 中午11:07
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] prometheusalert可以支持user.csv吗 (#72)




 
我想问一下，当前不支持user.csv的话，是不是只能在配置文件的全局配置（defaultphone=）配置固定的号码，而且只能配置一个

**Comment by qingfengfenga** [comment]
我当前主要使用的是Grafana到阿里云语音服务，单个接口 比如alydh这个接口，怎么配置多个电话，我这里没找到配置文件具体的配置项。
还有当前grafana支持user.csv吗？我配置了，没有生效

**Comment by qingfengfenga** [comment]
代码里只找到这4个参数，不是特别熟悉go，具体配置文件的单个接口的电话有配置示例的话发我一下吧，感谢
![image](https://user-images.githubusercontent.com/41416092/99482508-0411ad80-2997-11eb-9842-5a62f7c7e5db.png)

**Comment by qingfengfenga** [comment]
非常抱歉，我这边测试了Grafana可以支持user.csv，看代码 目前只有腾讯云支持备用联系人，我这边想要支持阿里云的备用联系人的话，参照tengxunstatus.go写阿里云的文件，router.go添阿里云的规则，这样可以吗

**Comment by feiyu563** [comment]
这样是可以的，现在自定义模版接口已经增加对user.csv的支持了。
