### ISSUE TITLE
求大神帮写个阿里云的模板

### ISSUE THREAD

**Issue by zhenglin305** [feiyu563/PrometheusAlert#73]
求大神帮写个阿里云的模板，不太会GO模板
日志接收到的内容：
`2020/11/09 10:54:15.390 [D] [value.go:460]  [1604919255390532604] alertName=memory+use&alertState=ALERT&curValue=12.45&dimensions=%7BinstanceId%3Di-wz91151k3aczmrbi8skk%2C+userId%3D20615031%7D&expression=%24Average%3E%3D10&instanceName=S1Z-DAE%2F10.11.1.14&metricName=%E5%86%85%E5%AD%98%E4%BD%BF%E7%94%A8%E7%8E%87&metricProject=acs_ecs&namespace=acs_ecs&preTriggerLevel=WARN&rawMetricName=vm.MemoryUtilization&ruleId=i-wz91151k3aczmrbi8skk_02959e0b-28f8-46a7-82a5-bb7522b5ec88&signature=%2BuWXy8wvm8h%2FJ%2FGSPDxvKdSCjqI%3D&timestamp=1604919253334&triggerLevel=WARN&userId=20615031`

消息相关内容
![image](https://user-images.githubusercontent.com/66998320/98532996-5da21a00-22bd-11eb-91c6-e3bb56f8d4cf.png)

相关参数说明
https://help.aliyun.com/document_detail/60714.html

![image](https://user-images.githubusercontent.com/66998320/98533265-b40f5880-22bd-11eb-9f2e-116f0ac8510a.png)

**Comment by feiyu563** [comment]
你这收到的消息是URL中的参数，有点像是form的post，你可以用go的form接收下json数据，模板就很简单了，参照我项目里面的自定义模板就行，里面有很多
