### ISSUE TITLE
阿里云电话模版

### ISSUE THREAD

**Issue by qingfengfenga** [feiyu563/PrometheusAlert#75]
阿里云没有模版，用自定义模版的话，按文档在Grafana里面配置完这个 http://[YOUR-PrometheusAlert-URL]/prometheusalert 
，测试发送会超时报错，prometheusalert也没任何日志输出。 

```
这么配置主要是为了方便调试和获取到Prometheus告警消息接口的JSON协议内容，其他的如grafana、graylog、sonarqube等支持WebHook的系统可以直接在控制台页面配置上http://[YOUR-PrometheusAlert-URL]/prometheusalert自定义消息模版的接口即可
```

**Comment by feiyu563** [comment]
用默认的短信或者电话就可以



---原始邮件---
发件人: "qingfengfenga"<notifications@github.com&gt;
发送时间: 2020年11月12日(周四) 晚上6:59
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 阿里云电话模版 (#75)




 
阿里云没有模版，用自定义模版的话，按文档在Grafana里面配置完这个 http://[YOUR-PrometheusAlert-URL]/prometheusalert
 ，测试发送会超时报错，prometheusalert也没任何日志输出。
 这么配置主要是为了方便调试和获取到Prometheus告警消息接口的JSON协议内容，其他的如grafana、graylog、sonarqube等支持WebHook的系统可以直接在控制台页面配置上http://[YOUR-PrometheusAlert-URL]/prometheusalert自定义消息模版的接口即可

**Comment by feiyu563** [comment]
记得改下模板的类型

**Comment by feiyu563** [comment]
默认的是腾讯云的，改成阿里云就行

**Comment by qingfengfenga** [comment]
抱歉，这里是我链路有问题，已解决

**Comment by qingfengfenga** [comment]
好的，感谢
