### ISSUE TITLE
阿里云报错

### ISSUE THREAD

**Issue by qingfengfenga** [feiyu563/PrometheusAlert#76]
抱歉，这个问题要再问一下
```
注意事项：开通阿里云短信和语音需要配置的模版请使用如下，${code}为变量名称，请勿替换：prometheus告警:${code}
```
这个是没有配置是导致下面这个错误的原因吧，阿里云语音模版已经配置了 ${code}，测试报下面的错误
```
{"RequestId":"7073B98D-E4E0-4D56-8FF2-7A1B586F506A","Message":"模板变量缺少对应参数值","Code":"isv.TEMPLATE_MISSING_PARAMETERS"}
```
我是要在 PrometheusAlert 的模版里面加上 ${code}这个变量吗？ 具体该怎么写，文档翻了一遍，没找到对应的示例（grafana到阿里云语音的模版）

**Comment by qingfengfenga** [comment]
阿里云语音模版里面的变量，需要写到那里呢，我这边尝试在  PrometheusAlert 的模版里面 写了没用，直接用 json内的变量也是没用，都是报  isv.TEMPLATE_MISSING_PARAMETERS 
![image](https://user-images.githubusercontent.com/41416092/99024552-cb8e6000-25a1-11eb-9558-19f0d9b90dbe.png)

**Comment by feiyu563** [comment]
只需要在阿里云的语音模板里面写的是 xx告警${code} 就可以，只要一个这样的变量，不能写多个，比如xx告警${code}，xx运维${data} 这样是不行的

**Comment by qingfengfenga** [comment]
好的，明白了，感谢。
另外我这边这个已经配置为0，但是grafana还是会拨打恢复电话，这个是grafana的问题吗，其他的报警源会不会这样
phonecallresolved=0

**Comment by feiyu563** [comment]
这个配置主要针对的是Prometheus，grafana是在页面上配置的



---原始邮件---
发件人: "qingfengfenga"<notifications@github.com&gt;
发送时间: 2020年11月16日(周一) 晚上6:45
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 阿里云报错 (#76)




 
好的，明白了，感谢。
 另外我这边这个已经配置为0，但是grafana还是会拨打恢复电话，这个是grafana的问题吗，其他的报警源会不会这样
 phonecallresolved=0

**Comment by qingfengfenga** [comment]
好的，grafana配置的话，把这个模版改一下就可以了吧
![image](https://user-images.githubusercontent.com/41416092/99339871-e32b5880-28c1-11eb-8f34-1171bce64721.png)

**Comment by feiyu563** [comment]
对的
