### ISSUE TITLE
能不能在发送alert的时候记录到mysql里

### ISSUE THREAD

**Issue by linux-xiayun** [feiyu563/PrometheusAlert#8]
hello，由于对golang不是很熟悉，现在有个想法是把报警记录更新到数据库中，便于调用查询，能提供下prometheus对应的数据库操作么

**Comment by feiyu563** [comment]
其实你完全可以直接查询Prometheus的数据就行了，Prometheus本身也是时序型的数据库，如果需要展示的话，结合grafana效果更好



---原始邮件---
发件人: "xiayun"<notifications@github.com&gt;
发送时间: 2020年1月22日(周三) 中午1:38
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 能不能在发送alert的时候记录到mysql里 (#8)



hello，由于对golang不是很熟悉，现在有个想法是把报警记录更新到数据库中，便于调用查询，能提供下prometheus对应的数据库操作么

**Comment by linux-xiayun** [comment]
感谢回复，本来想记录报警历史，现在业务场景根据您提供的方式直接查询当前alert数据，谢谢------------------ 原始邮件 ------------------
发件人: "feiyu563"<notifications@github.com>
发送时间: 2020年1月22日(星期三) 下午2:11
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com>;
抄送: "xiayun"<896365105@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [feiyu563/PrometheusAlert] 能不能在发送alert的时候记录到mysql里 (#8)


其实你完全可以直接查询Prometheus的数据就行了，Prometheus本身也是时序型的数据库，如果需要展示的话，结合grafana效果更好 
 
 
 
 ---原始邮&#x4EF6;--- 
 发&#x4EF6;人: "xiayun"<notifications@github.com&gt; 
 发送时间: 2020年1月22日(周三) 中午1:38 
 收&#x4EF6;人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
 主题: [feiyu563/PrometheusAlert] 能不能在发送alert的时候记录到mysql里 (#8) 
 
 
 
 hello，由于对golang不是很熟悉，现在有个想法是把报警记录更新到数据库中，便于调用查询，能提供下prometheus对应的数据库操作么 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by JayWu890225** [comment]
Hi ,
您这个项目作用是连接多监控系统，比如zabbix/grafana/prometheus，如果有把告警信息做持久化，感觉会更好。因为做了持久化后，可以做后续的分析以及优化甚至可以根据告警内容作出系统自我修复的功能。
如果像您之前回复的去prometheus内部查询，这样就等于绑定了监控工具，这跟你初衷应该相悖吧。

期待您的回复。

**Comment by feiyu563** [comment]
我先备注下，确实是个比较好的建议，原本我是打算做个无状态的应用，因为大部分告警系统本身已经有告警统计的功能



---原始邮件---
发件人: "JayWu890225"<notifications@github.com&gt;
发送时间: 2020年2月10日(周一) 晚上7:05
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 能不能在发送alert的时候记录到mysql里 (#8)



Hi ,
 您这个项目作用是连接多监控系统，比如zabbix/grafana/prometheus，如果有把告警信息做持久化，感觉会更好。因为做了持久化后，可以做后续的分析以及优化甚至可以根据告警内容作出系统自我修复的功能。
 如果像您之前回复的去prometheus内部查询，这样就等于绑定了监控工具，这跟你初衷应该相悖吧。
 
期待您的回复。

**Comment by bogeit** [comment]
不知道大佬能不能支持下发送飞书的接口。 @feiyu563

**Comment by feiyu563** [comment]
可以，我抽空调研下，先加入到下一版本开发计划



---原始邮件---
发件人: "bogeit"<notifications@github.com&gt;
发送时间: 2020年3月10日(周二) 中午1:34
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 能不能在发送alert的时候记录到mysql里 (#8)



不知道大佬能不能支持下发送飞书的接口。 @feiyu563

**Comment by bogeit** [comment]
谢谢大佬。 @feiyu563

**Comment by pzqu** [comment]
> Hi ,
> 您这个项目作用是连接多监控系统，比如zabbix/grafana/prometheus，如果有把告警信息做持久化，感觉会更好。因为做了持久化后，可以做后续的分析以及优化甚至可以根据告警内容作出系统自我修复的功能。
> 如果像您之前回复的去prometheus内部查询，这样就等于绑定了监控工具，这跟你初衷应该相悖吧。
> 
> 期待您的回复。

@JayWu890225 @linux-xiayun @feiyu563 

我个人认为不应该加到mysql中做持久化，因为这个工具本身作为webhook调用的方式，理应做的轻量，减少耦合。

个人认为最好的一种方式是把他按照业界规，设计成类似exporter的采集源，供prometheus或者其他监控采集

**Comment by feiyu563** [comment]
@pzqu 目前的计划也是在下一版本中集成metrics，尽可能的做到无状态化

**Comment by feiyu563** [comment]
@bogeit 飞书现已经支持

**Comment by bogeit** [comment]
> @bogeit 飞书现已经支持

收到，我会尽快完成测试，到时来反馈结果，谢谢大佬的更新。

**Comment by bogeit** [comment]
收到，我会尽快完成测试，到时来反馈结果，谢谢大佬的更新。 @feiyu563

**Comment by feiyu563** [comment]
目前已经初步集成了Prometheus的metrics来导出一些指标，目前还在测试阶段，部分信息可能还不是特别全面，欢迎使用最新的版本测试。
