### ISSUE TITLE
关于钉钉@所有人的问题

### ISSUE THREAD

**Issue by imshi** [feiyu563/PrometheusAlert#80]
需求：有多个用于接收告警的组，想实现默认情况下不@所有人，只在特定组@所有人
当前配置不生效（没有@）：
1、全局配置关闭@所有人：dd_isatall=0
2、在alertmanager的webhook_configs块的url中设置dd_isatall为1，如：'http://1.2.3.4:9095/prometheusalert?type=dd&tpl=prometheus-dd&ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxxx&dd_isatall=1‘
请问是这个@是只有全局配置起作用呢还是我配置有误，麻烦指导下，感谢~

**Comment by feiyu563** [comment]
目前还不支持@个人或者组的功能，这一部分后续会完善，关闭@所有人是在配置文件 app.conf中配置即生效

**Comment by imshi** [comment]
好的，感谢

**Comment by imshi** [comment]
close
