### ISSUE TITLE
grafana -> 阿里云电话的问题

### ISSUE THREAD

**Issue by qingfengfenga** [feiyu563/PrometheusAlert#83]
抱歉，再次打扰，我这边还有点问题不明白，想确认一下
我这边，grafana -> 阿里云电话，经测试支持如下：
```
1、只配全局置默认联系人（只支持默认单个联系人）
2、user.csv按日期配置不同的联系人，user.csv方式，同一日期只支持单一联系人对吗（同一日期配置多个联系人只有第一个生效，只有腾讯电话支持备用联系人。）
```
grafana -> 阿里云电话的模式 下：
我现在还是只能按日期配置单个联系人，如果配置按日期多个人轮询、多个人同时通知现在还不支持对吗，还是我这边配置的不对。

**Comment by feiyu563** [comment]
默认是没有同时按日期通知多个人，user.csv的方式默认按顺序通知当前日期的人，失败才会继续通知其他人，如果不使用user.csv的方式，是可以支持通知多人的

**Comment by qingfengfenga** [comment]
1、这个，失败的话继续通知的是示例表上的备用联系人吗，还是其他日期的联系人
```
user.csv的方式默认按顺序通知当前日期的人，失败才会继续通知其他人
```
2、不使用user.csv，多人怎么配置，有示例吗
```
如果不使用user.csv的方式，是可以支持通知多人的
```

**Comment by feiyu563** [comment]
1.备用联系人
2.使用自定义模板接口，参数里面用，分割多个号码即可

**Comment by qingfengfenga** [comment]
明白了，感谢解答
