### ISSUE TITLE
telegram 配置问题

### ISSUE THREAD

**Issue by topicgit** [feiyu563/PrometheusAlert#84]
问题一： 配置 TG_MODE_CHAN=0  TG_USERID=xxxx 
使用这个配置日志报错，chat_id 是空，无法发送

问题二： TG_MODE_CHAN=1   TG_CHANNAME=xxxx
请问这个TG_CHANNAME 怎么配置，是在哪里获取；我配置为channel的id会给我加上@，但是会报错日志
`2020/11/28 17:05:38 Endpoint: sendMessage, params: map[chat_id:@-16666272 text:故障主机IP 172.31.5.38:9100172.31.5.38:9100 sys_load1占用过高 2.18]
2020/11/28 17:05:39 Endpoint: sendMessage, response: {"ok":false,"error_code":400,"description":"Bad Request: chat not found"}`

我想的是可以向tg的群组里面发送消息，您这用的是channel， 我应该如何配置， 谢谢。
@ysicing @feiyu563

**Comment by ysicing** [comment]
推送给群组应该和个人类似，没具体研究， 个人需要个人的ID，目测群组需要群组的ID。

```
# 推送个人
open-tg=1
TG_TOKEN
TG_MODE_CHAN=0
TG_USERID=

# 推送频道
open-tg=1
TG_TOKEN
TG_MODE_CHAN=1
TG_CHANNAME="@ysicing_notice"
```

![image](https://user-images.githubusercontent.com/8605565/100515481-854b1a80-31b7-11eb-8631-2966c6d28936.png)

# 附上我的测试示例
![image](https://user-images.githubusercontent.com/8605565/100515522-c0e5e480-31b7-11eb-9765-fd35f4e5922a.png)

**Comment by topicgit** [comment]
> 推送给群组应该和个人类似，没具体研究， 个人需要个人的ID，目测群组需要群组的ID。
> 
> ```
> # 推送个人
> open-tg=1
> TG_TOKEN
> TG_MODE_CHAN=0
> TG_USERID=
> 
> # 推送频道
> open-tg=1
> TG_TOKEN
> TG_MODE_CHAN=1
> TG_CHANNAME="@ysicing_notice"
> ```
> 
> ![image](https://user-images.githubusercontent.com/8605565/100515481-854b1a80-31b7-11eb-8631-2966c6d28936.png)
> 
> # 附上我的测试示例
> ![image](https://user-images.githubusercontent.com/8605565/100515522-c0e5e480-31b7-11eb-9765-fd35f4e5922a.png)
> 
> 频道: https://t.me/ysicing_notice/456
> 
> @topicgit

非常感谢，已经可以，找到问题了，必须创建public类型的channel才行
