### ISSUE TITLE
绝对路径执行访问报错找不到index.html

### ISSUE THREAD

**Issue by charnet1019** [feiyu563/PrometheusAlert#85]
![image](https://user-images.githubusercontent.com/18616254/101133814-6da2e480-3644-11eb-9af0-e0c5ec370026.png)

**Comment by feiyu563** [comment]
脚本启动需要先cd 到对应目录，service方式启动，需要加workdir参数指定PrometheusAler的目录



---原始邮件---
发件人: "charnet1019"<notifications@github.com&gt;
发送时间: 2020年12月4日(周五) 下午3:22
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 绝对路径执行访问报错找不到index.html (#85)

**Comment by luanxinchen** [comment]
这是我的service文件，可以参考下
```
[root@it-prometheus-master PrometheusAlert]# cat ../services/promalert.service
[Unit]
Description=PrometheusAlert
After=network.service

[Service]
User=root
Group=root
Type=simple
WorkingDirectory=/root/prometheus/PrometheusAlert/
ExecStart=/root/prometheus/PrometheusAlert/PrometheusAlert
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
