### ISSUE TITLE
飞书是否可以增加签名校验配置项

### ISSUE THREAD

**Issue by charnet1019** [feiyu563/PrometheusAlert#86]
增加签名校验配置项防止api泄露

**Comment by feiyu563** [comment]
目前尚未有这方面的计划，但后期可能增加隐藏数据库字段来保存api接口地址



---原始邮件---
发件人: "charnet1019"<notifications@github.com&gt;
发送时间: 2020年12月8日(周二) 晚上8:36
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 飞书是否可以增加签名校验配置项 (#86)




 
增加签名校验配置项防止api泄露
