### ISSUE TITLE
granfana 报警没有内容没有实例信息呢

### ISSUE THREAD

**Issue by zdong08** [feiyu563/PrometheusAlert#87]
` {"dashboardId":1,"evalMatches":[{"value":0.01,"metric":"node_load5{instance=\"10.104.19.65:9100\", job=\"db\"}","tags":{"__name__":"node_load5","instance":"10.104.19.65:9100","job":"db"}}],"message":"test","orgId":1,"panelId":199,"ruleId":3,"ruleName":"Panel Title alert","ruleUrl":"http://localhost:3000/d/9CWBz0bik/?tab=alert\u0026viewPanel=199\u0026orgId=1","state":"alerting","tags":{},"title":"[Alerting] Panel Title alert"}`
grangfa 报警内容如上，报警信息只有msssage test  没有tags ，这个怎么修改呢

**Comment by feiyu563** [comment]
grafana的tag好像是在
![image](https://user-images.githubusercontent.com/25146052/102051392-799a5d80-3e1f-11eb-9eb9-cd3b4071b81c.png)

**Comment by zdong08** [comment]
我的确实没有呢 模板也是用的默认的

**Comment by feiyu563** [comment]
那个是你自己加的tag



---原始邮件---
发件人: "zdong08"<notifications@github.com&gt;
发送时间: 2020年12月14日(周一) 下午5:11
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] granfana 报警没有内容没有实例信息呢 (#87)




 
我的确实没有呢 模板也是用的默认的
