### ISSUE TITLE
告警收到的变量信息如何定义

### ISSUE THREAD

**Issue by liaoqiArno** [feiyu563/PrometheusAlert#88]
k8s集群里接入的企业微信告警
```
PrometheusAlertPrometheus故障告警信息
KubePodCrashLooping
告警级别:信息
开始时间:2020-12-07T07:44:35.095800493Z
结束时间:0001-01-01T00:00:00Z
故障主机IP:10.0.1.16:8443


```
但是我点开的链接地址是这样的
http://prometheus-k8s-0:9090/graph?g0.expr=rate%28kube_pod_container_status_restarts_total%7Bjob%3D%22kube-state-metrics%22%7D%5B15m%5D%29+%2A+60+%2A+5+%3E+0&g0.tab=1

请问下如何把http://prometheus-k8s-0:9090 修改成我的真实地址

**Comment by feiyu563** [comment]
prometheus启动时候加这个参数  --web.external-url=



---原始邮件---
发件人: "liaoqiArno"<notifications@github.com&gt;
发送时间: 2020年12月17日(周四) 中午11:02
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 告警收到的变量信息如何定义 (#88)




 
k8s集群里接入的企业微信告警
 PrometheusAlertPrometheus故障告警信息 KubePodCrashLooping 告警级别:信息 开始时间:2020-12-07T07:44:35.095800493Z 结束时间:0001-01-01T00:00:00Z 故障主机IP:10.0.1.16:8443  
但是我点开的链接地址是这样的
 http://prometheus-k8s-0:9090/graph?g0.expr=rate%28kube_pod_container_status_restarts_total%7Bjob%3D%22kube-state-metrics%22%7D%5B15m%5D%29+%2A+60+%2A+5+%3E+0&amp;g0.tab=1
 
请问下如何把http://prometheus-k8s-0:9090 修改成我的真实地址
