### ISSUE TITLE
没有支持Email通知方式吗

### ISSUE THREAD

**Issue by anywgchao** [feiyu563/PrometheusAlert#9]

**Comment by feiyu563** [comment]
email的一般告警系统默认已经自带了，所以就没有再重复开发这方面的



---原始邮件---
发件人: "ywhere"<notifications@github.com&gt;
发送时间: 2020年2月4日(周二) 中午11:23
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 没有支持Email通知方式吗 (#9)
