### ISSUE TITLE
helm 部署错误

### ISSUE THREAD

**Issue by herryhw** [feiyu563/PrometheusAlert#91]
我使用helm部署pod报如下错误：
register db Ping `default`, dial tcp 127.0.0.1:3306: connect: connection refused
must have one register DataBase alias named `default`

**Comment by feiyu563** [comment]
这是配置文件开启了MySQL做存储，但是MySQL的配置不对



---原始邮件---
发件人: "herryhw"<notifications@github.com&gt;
发送时间: 2020年12月24日(周四) 晚上6:21
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] helm 部署错误 (#91)




 
我使用helm部署pod报如下错误：
 register db Ping default, dial tcp 127.0.0.1:3306: connect: connection refused
 must have one register DataBase alias named default

**Comment by herryhw** [comment]
这个我是直接用的helm里面的配置，没有做任何修改，为什么会有mysql?

**Comment by herryhw** [comment]
> 这是配置文件开启了MySQL做存储，但是MySQL的配置不对
> […](#)
> ---原始邮件--- 发件人: "herryhw"<notifications@github.com&gt; 发送时间: 2020年12月24日(周四) 晚上6:21 收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [feiyu563/PrometheusAlert] helm 部署错误 (#91) 我使用helm部署pod报如下错误： register db Ping default, dial tcp 127.0.0.1:3306: connect: connection refused must have one register DataBase alias named default — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我用的git上的helm的默认配置，没有做任何修改，怎么会有mysql? 不太明白。

**Comment by feiyu563** [comment]
你看下helm的config目录下面的app.conf是不是开启了MySQL

**Comment by herryhw** [comment]
> 你看下helm的config目录下面的app.conf是不是开启了MySQL

没有，我用的git上的helm默认配置，app.conf里面没有配置mysql的。用的全是默认配置，没有做任何修改。

**Comment by feiyu563** [comment]
OK，我一会测试一下

**Comment by herryhw** [comment]
> OK，我一会测试一下

好的，谢谢，麻烦帮忙解决。

**Comment by herryhw** [comment]
> OK，我一会测试一下

找到原因了，用的是master的代码下的helm，app.conf没有mysql的配置，我换成release里面的helm的可以了
