### ISSUE TITLE
在微信中关注企业号接收到消息提示"暂不支持此消息类型，请在企业微信中查看"

### ISSUE THREAD

**Issue by yu921** [feiyu563/PrometheusAlert#94]
在企业微信中告警可以正常显示告警内容，
但是在微信中关注企业号提示"暂不支持此消息类型，请在企业微信中查看"

是因为消息的类型是”markdown“引起的吗？

**Comment by feiyu563** [comment]
这个目前没有测试过直接在微信中查看



---原始邮件---
发件人: "yu921"<notifications@github.com&gt;
发送时间: 2021年1月15日(周五) 晚上7:37
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 在微信中关注企业号接收到消息提示"暂不支持此消息类型，请在企业微信中查看" (#94)




 
在企业微信中告警可以正常显示告警内容，
 但是在微信中关注企业号提示"暂不支持此消息类型，请在企业微信中查看"
 
是因为消息的类型是”markdown“引起的吗？

**Comment by yu921** [comment]
有办法将消息的类型修改为Txt格式吗？
 配置文件中说明写的
   “# 消息类型, 暂时只支持markdown
   “ # WorkWechat_Msgtype = "markdown"”

**Comment by feiyu563** [comment]
text格式的不支持消息文本的格式化，目前目前还没提供



---原始邮件---
发件人: "yu921"<notifications@github.com&gt;
发送时间: 2021年1月18日(周一) 下午4:33
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "feiyu563"<244217140@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] 在微信中关注企业号接收到消息提示"暂不支持此消息类型，请在企业微信中查看" (#94)




 
有办法将消息的类型修改为Txt格式吗？
 配置文件中说明写的
 “# 消息类型, 暂时只支持markdown
 “ # WorkWechat_Msgtype = "markdown"”
