### ISSUE TITLE
腾讯云电话告警失效

### ISSUE THREAD

**Issue by dgthomugo** [feiyu563/PrometheusAlert#96]
之前用4.2版本的时候，按照说明是能配通腾讯云电话告警的，最近不知道是不是因为腾讯云电话告警的接口发生了变更，最近的电话告警失效了，老是打不出来电话。

**Comment by feiyu563** [comment]
日志里面有报错吗，或者你可以点下页面测试按钮看下



---原始邮件---
发件人: "张梦豪@探索中心"<notifications@github.com&gt;
发送时间: 2021年1月22日(周五) 下午3:28
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 腾讯云电话告警失效 (#96)




 
之前用4.2版本的时候，按照说明是能配通腾讯云电话告警的，最近不知道是不是因为腾讯云电话告警的接口发生了变更，最近的电话告警失效了，老是打不出来电话。
