### ISSUE TITLE
PrometheusAlert无法识别传入的多个phone号码，告警时生效的是配置中的默认电话

### ISSUE THREAD

**Issue by fzusuny** [feiyu563/PrometheusAlert#97]
您好，我在alertmanager的webhook_configs中配置了多个号码，格式如：
'http://[prometheusalert地址]/prometheusalert?type=alydh&tpl=aliyun-phone&phone=号码1,号码2,号码3'
但是实际上phone=后的参数似乎都没有生效，生效的永远是配置中的

```txt
#默认拨打号码(页面测试短信和电话功能需要配置此项)
defaultphone= 实际生效号码
```
是配置中缺少配置吗，还是defaultphone配置后url传入的参数都不生效

**Comment by feiyu563** [comment]
你看下你的阿里云后台是否有号码白名单或者拨号失败的，通常只有失败的情况下会使用默认号码



---原始邮件---
发件人: "fzusuny"<notifications@github.com&gt;
发送时间: 2021年1月22日(周五) 晚上6:28
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] PrometheusAlert无法识别传入的多个phone号码，告警时生效的是配置中的默认电话 (#97)




 
您好，我在alertmanager的webhook_configs中配置了多个号码，格式如：
 'http://[prometheusalert地址]/prometheusalert?type=alydh&amp;tpl=aliyun-phone&amp;phone=号码1,号码2,号码3'
 但是实际上phone=后的参数似乎都没有生效，生效的永远是配置中的
 #默认拨打号码(页面测试短信和电话功能需要配置此项) defaultphone= 实际生效号码  
是配置中缺少配置吗，还是defaultphone配置后url传入的参数都不生效

**Comment by fzusuny** [comment]
解决了，我们使用的是k8s部署，拉取的是一周前的latest镜像。我把镜像tag改为4.0.2后问题解决
新版本中传参无效，生效的是默认配置：
![image](https://user-images.githubusercontent.com/37660537/105483322-a6764600-5ce4-11eb-94fa-a3110da042bc.png)
4.0.2版本中正常：
![image](https://user-images.githubusercontent.com/37660537/105483459-d7ef1180-5ce4-11eb-89ae-792e61619f79.png)

**Comment by feiyu563** [comment]
OK



---原始邮件---
发件人: "fzusuny"<notifications@github.com&gt;
发送时间: 2021年1月22日(周五) 晚上7:07
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "feiyu563"<244217140@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [feiyu563/PrometheusAlert] PrometheusAlert无法识别传入的多个phone号码，告警时生效的是配置中的默认电话 (#97)




 
解决了，我们使用的是k8s部署，拉取的是一周前的latest镜像。我把镜像tag改为4.0.2后问题解决
 新版本中传参无效，生效的是默认配置：
 
 4.0.2版本中正常：
