### ISSUE TITLE
自定义钉钉模板开启了prometheus_cst_time=1无效

### ISSUE THREAD

**Issue by guoqingg** [feiyu563/PrometheusAlert#99]
默认钉钉模板开启调整时区有效，自定义钉钉模板无效，时间还是夏令营时

**Comment by feiyu563** [comment]
自定义模板里面有单独的函数处理，具体可参考自定义模板的说明文档



---原始邮件---
发件人: "国庆"<notifications@github.com&gt;
发送时间: 2021年1月27日(周三) 下午4:02
收件人: "feiyu563/PrometheusAlert"<PrometheusAlert@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [feiyu563/PrometheusAlert] 自定义钉钉模板开启了prometheus_cst_time=1无效 (#99)




 
默认钉钉模板开启调整时区有效，自定义钉钉模板无效，时间还是夏令营时

**Comment by guoqingg** [comment]
多谢
